symfony/recipes-contrib

hostnet/form-handler-bundle/1.2/manifest.json
Added the hostnet/form-handler-bundle: https://github.com/hostnet/form-handler-bundle/wiki
=> Added hostnet/form-handler-bundle/1.2

pomm-project/pomm-bundle/2.3/etc/packages/pomm.yaml, pomm-project/pomm-bundle/2.3/etc/routing/dev/pomm.yaml, pomm-project/pomm-bundle/2.3/manifest.json
https://github.com/pomm-project/pomm-bundle
=> Add pomm bundle recipe

php-amqplib/rabbitmq-bundle/1.12/etc/packages/old_sound_rabbit_mq.yaml, php-amqplib/rabbitmq-bundle/1.12/manifest.json
Official Symfony bundle https://github.com/php-amqplib/RabbitMqBundle (761 stars)
=> Add OldSoundRabbitMqBundle recipe

misd/phone-number-bundle/1.2/etc/packages/libphonenumber.yaml, misd/phone-number-bundle/1.2/manifest.json
Reverts symfony/recipes-contrib#30
=> Revert "Added MisdPhoneNumberBundle"

wemakecustom/doctrine-naming-strategy-bundle/1.0/etc/packages/wmc_doctrine_naming_strategy.yaml, wemakecustom/doctrine-naming-strategy-bundle/1.0/manifest.json
This is a recipe for an alternative doctrine naming strategy (table and column names) I've been using for a couple of years. It'd be nice to be able to use it with Flex, using the auto-configuration :)
=> WMC's Doctrine Naming Strategy Recipe

snc/redis-bundle/2.0/etc/packages/snc_redis.yaml, snc/redis-bundle/2.0/manifest.json
* The most popular Redis bundle for Symfony
* 3 million downloads
* https://github.com/snc/SncRedisBundle
=> Added SncRedisBundle

enqueue/dbal/0.4/manifest.json, enqueue/fs/0.4/manifest.json
=> Add enqueue\dbal message queue transport.

hautelook/alice-bundle/1.4/etc/packages/dev/hautelook_alice.yaml, hautelook/alice-bundle/1.4/manifest.json
About this bundle:
* ~1,100,000 downloads
* https://github.com/hautelook/AliceBundle
=> Add HautelookAliceBundle recipe

stof/doctrine-extensions-bundle/1.2/etc/packages/stof_doctrine_extensions.yaml, stof/doctrine-extensions-bundle/1.2/manifest.json
About this bundle:
The most popular one for integration of the gedmo/doctrine-extensions.
6.5 million downloads
https://github.com/stof/StofDoctrineExtensionsBundle
@stof  as the author of the bundle
=> Add StofDoctrineExtensionsBundle recipe

friendsofsymfony/rest-bundle/2.2/etc/packages/fos_rest.yaml, friendsofsymfony/rest-bundle/2.2/manifest.json
About this bundle:
Is a popular bundle for the rapid development of RESTful applications and applications.
8.2 million downloads
https://github.com/FriendsOfSymfony/FOSRestBundle
@FriendsOfSymfony as the authors of the bundle
=> Add FOSRestBundle recipe

jolicode/gif-exception-bundle/1.0/manifest.json
=> Add recipe for GifExceptionBundle

orbitale/cms-bundle/2.0/etc/packages/orbitale_cms.yaml, orbitale/cms-bundle/2.0/etc/routing/orbitale_cms.yaml, orbitale/cms-bundle/2.0/manifest.json, orbitale/cms-bundle/2.0/src/Entity/Category.php, orbitale/cms-bundle/2.0/src/Entity/Page.php, orbitale/cms-bundle/3.0/etc/packages/orbitale_cms.yaml, orbitale/cms-bundle/3.0/etc/routing/orbitale_cms.yaml, orbitale/cms-bundle/3.0/manifest.json, orbitale/cms-bundle/3.0/src/Entity/Category.php, orbitale/cms-bundle/3.0/src/Entity/Page.php
=> https://github.com/Orbitale/CmsBundle
Lightweight CMS with already built-in Page and Category entities.
I'd like to propose a ready-to-use EasyAdmin integration, but I think I might need to create a "pack" as proposed by @fabpot in his post.
What do you think?
=> Added OrbitaleCmsBundle

php-http/httplug-bundle/1.6/config/packages/httplug.yaml
=> Do not use logger plugin since it has external dependency.

endroid/asset/1.0/config/packages/endroid_asset.yaml, endroid/asset/1.0/manifest.json, endroid/cm-sms/1.4/config/packages/dev/endroid_cm_sms.yaml, endroid/cm-sms/1.4/config/packages/endroid_cm_sms.yaml, endroid/cm-sms/1.4/config/routes/endroid_cm_sms.yaml, endroid/cm-sms/1.4/manifest.json, endroid/flusher/1.0/config/packages/endroid_flusher.yaml, endroid/flusher/1.0/manifest.json, endroid/import/1.0/config/packages/endroid_import.yaml, endroid/import/1.0/config/routes/endroid_import.yaml, endroid/import/1.0/manifest.json
=> Add recipes for endroid libraries

sensiolabs/connect-bundle/4.0/config/packages/sensio_labs_connect.yaml, sensiolabs/connect-bundle/4.0/config/routes/sensio_labs_connect.yaml, sensiolabs/connect-bundle/4.0/manifest.json
=> Add support for SensioLabs Connect bundle

endroid/asset/1.0/config/packages/endroid_asset.yaml, endroid/asset/1.0/manifest.json, endroid/cm-sms/1.4/config/packages/endroid_cm_sms.yaml, endroid/cm-sms/1.4/manifest.json
=> Remove asset and set required parameter

nelmio/security-bundle/2.4/config/packages/nelmio_security.yaml, nelmio/security-bundle/2.4/manifest.json
=> Add NelmioSecurityBundle

spomky-labs/jose-bundle/2.2/manifest.json, spomky-labs/lexik-jose-bridge/1.0/config/packages/spomky_labs_lexik_jose_bridge_bundle.yaml, spomky-labs/lexik-jose-bridge/1.0/manifest.json, spomky-labs/lexik-jose-bridge/1.0/post-install.txt
This PR adds `spomky-labs/lexik-jose-bridge` v1.0.
=> Adds Spomky-Labs Lexik Jose Bridge v1.0

bukashk0zzz/filter-bundle/2.0/config/packages/bukashk0zzz_filter.yaml, bukashk0zzz/filter-bundle/2.0/manifest.json
=> Add Bukashk0zzz FilterBundle

symfony-cmf/seo-bundle/2.0/config/packages/cmf_seo_bundle.yaml, symfony-cmf/seo-bundle/2.0/config/routes/cmf_seo_bundle.yaml, symfony-cmf/seo-bundle/2.0/manifest.json
This is the first recipe of the Symfony CMF. And i start with adding the seo-bundle
=> create recipe for Symfony CMF SeoBundle

enqueue/amqp-bunny/0.7/manifest.json, enqueue/amqp-bunny/0.8/manifest.json, enqueue/amqp-ext/0.7/manifest.json, enqueue/amqp-ext/0.8/manifest.json, enqueue/amqp-lib/0.7/manifest.json, enqueue/amqp-lib/0.8/manifest.json, enqueue/dbal/0.8/manifest.json, enqueue/gearman/0.7/manifest.json, enqueue/gearman/0.8/manifest.json, enqueue/gps/0.7/manifest.json, enqueue/pheanstalk/0.8/manifest.json, enqueue/rdkafka/0.7/manifest.json, enqueue/rdkafka/0.8/manifest.json, enqueue/redis/0.7/manifest.json, enqueue/sqs/0.7/manifest.json, enqueue/stomp/0.7/manifest.json
It contains changes previously introduced in https://github.com/symfony/recipes-contrib/pull/92 but for some reason lost while rebasing.
=> Enqueue lost packages.

symfony-cmf/routing-bundle/2.0/config/packages/cmf_routing_bundle.yaml, symfony-cmf/routing-bundle/2.0/manifest.json
This adds the reciepe of routing bundle. I will try to experiment with its result a little bit tonight.
*ToDo*
=> Cmf routing bundle reciepe

mediamonks/rest-api-bundle/3.0/config/packages/mediamonks_rest_api.yaml, mediamonks/rest-api-bundle/3.0/manifest.json
I'm the creator of both the bundle and the package it uses.
=> Add mediamonks/rest-api-bundle

pierstoval/character_manager/0.5/config/packages/pierstoval_character_manager.yaml, pierstoval/character_manager/0.5/config/routing/pierstoval_character_manager.yaml, pierstoval/character_manager/0.5/manifest.json, pierstoval/character_manager/0.5/src/CharacterGenerator/Step01.php, pierstoval/character_manager/0.5/src/Entity/Character.php
Used by at least 2 projects internally at @StudioAgate, projects I wish to migrate to Flex 😉
=> Add PierstovalCharacterManagerBundle

mailgun/mailgun-php/2.3/config/packages/mailgun.yaml, mailgun/mailgun-php/2.3/manifest.json
Make sure one can add Mailgun client library. 
There is an integration with SwiftMailer at: https://github.com/tehplague/swiftmailer-mailgun-bundle
Should I consider that in this recipe or or not?
=> Added mailgun api client

cache/adapter-bundle/1.1/config/packages/cache_adapter.yaml, cache/adapter-bundle/1.1/manifest.json, cache/adapter-bundle/1.1/post-install.txt, cache/cache-bundle/1.0/config/packages/cache.yaml, cache/cache-bundle/1.0/manifest.json
=> Adding php-cache's adapter-bundle and cache-bundle

leogout/seo-bundle/1.0/config/packages/leogout_seo.yaml, leogout/seo-bundle/1.0/manifest.json
As the config is essentially keywords and titles, I didn't added any default values or ENV parameters. I've also referenced the bundle's config to make it simpler for the user.
=> Added leogout-seo bundle

doctrine/mongodb-odm-bundle/3.3/config/packages/doctrine_mongodb.yaml, doctrine/mongodb-odm-bundle/3.3/manifest.json
Fix https://github.com/symfony/recipes-contrib/issues/75
=> Set mongodb-odm-bundle default database

xcore/inline-editing-bundle/1.2/config/packages/xcore_inline.yaml, xcore/inline-editing-bundle/1.2/config/routes/xcore_inline.yaml, xcore/inline-editing-bundle/1.2/manifest.json
=> Add XcoreCMSInlineEditingBundle recipe

happyr/linkedin-api-client/1.0/config/packages/linkedin.yaml, happyr/linkedin-api-client/1.0/manifest.json
=> Added LinkedIn API client

orbitale/easyimpress-bundle/1.0/config/packages/orbitale_easy_impress.yaml, orbitale/easyimpress-bundle/1.0/config/presentations/home.yaml, orbitale/easyimpress-bundle/1.0/config/routes/orbitale_easy_impress.yaml, orbitale/easyimpress-bundle/1.0/manifest.json
=> https://github.com/Orbitale/EasyImpressBundle
=>  Add Orbitale EasyImpressBundle

overblog/graphiql-bundle/0.1/config/routes/dev/graphiql.yaml, overblog/graphiql-bundle/0.1/manifest.json, overblog/graphiql-bundle/0.1/post-install.txt
=> OverblogGraphiQLBundle: Added recipe for ^0.1.0

bukashk0zzz/liip-imagine-serialization-bundle/2.0/config/packages/bukashk0zzz_liip_imagine_serialization.yaml, bukashk0zzz/liip-imagine-serialization-bundle/2.0/manifest.json
=> :heavy_plus_sign: Add Bukashk0zzz LiipImagineSerializationBundle

willdurand/geocoder-bundle/5.0/config/packages/bazinga_geocoder.yaml, willdurand/geocoder-bundle/5.0/manifest.json
=> Adding support for GeocoderBundle 5.

eightpoints/guzzle-bundle/7.0/config/packages/dev/eight_points_guzzle.yaml, eightpoints/guzzle-bundle/7.0/config/packages/eight_points_guzzle.yaml, eightpoints/guzzle-bundle/7.0/manifest.json
This bundle integrates Guzzle 6.x into Symfony. Guzzle is a PHP framework for building RESTful web service clients.
=> Add recipe for eightpoints/guzzle-bundle

nelmio/solarium-bundle/2.4/config/packages/nelmio_solarium.yaml, nelmio/solarium-bundle/2.4/manifest.json
=> Add NelmioSolariumBundle v2.4 recipe

odolbeau/datagen/1.0/manifest.json
=> Add odolbeau/datagen recipe

sg/datatablesbundle/1.0/config/routes/sg_datatables_bundle.yaml, sg/datatablesbundle/1.0/manifest.json
This PR adds recipes for the SgDatatablesBundle (PR https://github.com/stwe/DatatablesBundle/pull/716)
#SymfonyConHackday2017
=> Added SgDatatablesBundle recipe

mailxpert/apibundle/0.1/config/packages/mailxpert_apibundle.yaml, mailxpert/apibundle/0.1/config/routes/mailxpert_apibundle.yaml, mailxpert/apibundle/0.1/manifest.json, mailxpert/apibundle/0.1/src/Entity/AccessToken.php
=> mailxpert apibundle

dekalee/cdn77-bundle/1.4/config/packages/dekalee_cdn77.yaml, dekalee/cdn77-bundle/1.4/manifest.json
=> dekalee-cdn77-bundle recipe

fresh/doctrine-enum-bundle/6.0/manifest.json
I put to the recipe a default directory for custom Doctrine types which are handled by this bundle
=> Add fresh/doctrine-enum-bundle

dama/doctrine-test-bundle/4.0/config/packages/test/dama_doctrine_test_bundle.yaml, dama/doctrine-test-bundle/4.0/manifest.json
This replaces https://github.com/symfony/recipes-contrib/pull/103
=> Add recipe for dama/doctrine-test-bundle

omines/datatables-bundle/0.1/config/packages/datatables.yaml, omines/datatables-bundle/0.1/manifest.json
=> Add datatables bundle

knplabs/github-api/2.6/manifest.json
We do not need to escape quotes like this.
=> Backticks is not needed

rokka/client-bundle/1.0/config/packages/rokka.yaml, rokka/client-bundle/1.0/manifest.json
=> add rokka/client-bundle to flex

endroid/flusher/1.0/config/packages/endroid_flusher.yaml, endroid/flusher/1.0/manifest.json
=> Remove recipe

helios-ag/fm-elfinder-bundle/7.0/config/packages/fm_elfinder.yaml, helios-ag/fm-elfinder-bundle/7.0/config/routes/fm_elfinder.yaml, helios-ag/fm-elfinder-bundle/7.0/manifest.json
This pull request adds a recipe for FMElfinderBundle which has been updated to support Symfony 4
=> Added recipe for FMElfinderBundle

qandidate/toggle-bundle/1.0/config/packages/qandidate_toggle.yaml, qandidate/toggle-bundle/1.0/manifest.json
=> added recipe for QandidateToggleBundle

mmucklo/queue-bundle/3.0/config/packages/dtc_queue.yaml, mmucklo/queue-bundle/3.0/config/routes/dtc_queue.yaml, mmucklo/queue-bundle/3.0/manifest.json, mmucklo/queue-bundle/3.0/post-install.txt
=> Adding mmucklo/queue-bundle

wisembly/amqp-bundle/1.4/config/packages/wisembly_amqp.yaml, wisembly/amqp-bundle/1.4/manifest.json
Update the flex recipe for Wisembly AmqpBundle (1.4 and 2.0 versions which were released today).
I wasn't sure if duplicating (as 1.4 and 2.0 have the same config), but I did it anyway for consistency.
=> Wisembly amqp

liip/monitor-bundle/2.6/config/packages/monitor.yaml, liip/monitor-bundle/2.6/manifest.json, liip/monitor-bundle/2.6/post-install.txt
=> add recipe for liip/monitor-bundle:2.6.*

leapt/im-bundle/2.0/config/packages/leapt_im.yaml, leapt/im-bundle/2.0/config/routes/leapt_im.yaml, leapt/im-bundle/2.0/manifest.json
=> Add Leapt ImBundle

wow-apps/symfony-slack-bot/3.2/config/packages/wow_apps_slack.yaml, wow-apps/symfony-slack-bot/3.2/manifest.json
Added Symfony Slack Bot Bundle
=> Added Symfony Slack Bot Bundle

msgphp/eav-bundle/0.2/config/packages/msgphp_eav.php, msgphp/eav-bundle/0.2/manifest.json, msgphp/eav-bundle/0.2/src/Entity/Eav/Attribute.php, msgphp/eav-bundle/0.2/src/Entity/Eav/AttributeValue.php, msgphp/user-bundle/0.3/config/packages/msgphp_user.php, msgphp/user-bundle/0.3/manifest.json, msgphp/user-bundle/0.3/src/Entity/User/User.php
I tweaked the bundles to be installed without any errors. This should be the final step.
Working app: https://github.com/msgphp/symfony-demo-app
Blog post: https://medium.com/@ro0NL/building-a-new-symfony-user-bundle-b4fe5a9d9d80
It's a work in progress due the fact the used packages have no stable tag yet. 
For now;
```bash
$ composer create-project symfony/skeleton
$ cd skeleton
$ composer require msgphp/domain:@dev msgphp/eav:@dev msgphp/user:@dev msgphp/eav-bundle msgphp/user-bundle
```
=> Added MsgPhp bundles

tilleuls/forgot-password-bundle/1.0/config/packages/coop_tilleuls_forgot_password.yaml, tilleuls/forgot-password-bundle/1.0/config/routes/coop_tilleuls_forgot_password.yaml, tilleuls/forgot-password-bundle/1.0/manifest.json
Add [CoopTilleulsForgotPasswordBundle](https://github.com/coopTilleuls/CoopTilleulsForgotPasswordBundle) recipe
=> Add CoopTilleulsForgotPasswordBundle recipe

endroid/twitter/2.0/config/packages/endroid_twitter.yaml
=> Update endroid/twitter services

sonata-project/core-bundle/3.9/config/packages/sonata_project/sonata_core.yaml, sonata-project/core-bundle/3.9/manifest.json
=> Add SonataCoreBundle with minimal configuration

webinarium/symfony-lazysec/2.0/config/packages/lazysec.yaml, webinarium/symfony-lazysec/2.0/config/packages/lazysec_translations.yaml, webinarium/symfony-lazysec/2.0/manifest.json
=> Add webinarium/symfony-lazysec package

ywh/cvss-bundle/1.0/config/packages/ywh_doctrine_encryption.yaml, ywh/cvss-bundle/1.0/manifest.json
Add recipe for YesWeHack cvss bundle that provides integration for
[Cvss](https://github.com/yeswehack/cvss).
Common Vulnerability Scoring System (CVSS) provides a robust and useful scoring system for IT vulnerabilities.
See https://www.first.org/cvss for more informations.
=> Add YWH Cvss Bundle

wandi/easyadmin-plus-bundle/0.1/config/routes/easy_admin_plus.yaml, wandi/easyadmin-plus-bundle/0.1/config/routes/wandi_easy_admin_plus.yaml, wandi/easyadmin-plus-bundle/0.1/manifest.json
=> Add recipe for EasyAdminPlus bundle

mmucklo/queue-bundle/4.0/config/packages/dtc_queue.yaml, mmucklo/queue-bundle/4.0/config/routes/dtc_queue.yaml, mmucklo/queue-bundle/4.0/manifest.json, mmucklo/queue-bundle/4.0/post-install.txt
=> Add recipe for mmucklo/queue-bundle v4.0

nuboxdevcom/maintenance-bundle/2.0/config/packages/ndc_maintenance.yaml, nuboxdevcom/maintenance-bundle/2.0/manifest.json
Recipe for nuboxdevcom/maintenance-bundle@2.*
=> Recipe for nuboxdevcom/maintenance-bundle

broadway/broadway-bundle/0.4/config/packages/broadway.yaml, broadway/broadway-bundle/0.4/manifest.json, broadway/event-store-dbal/0.2/config/packages/broadway_event_store_dbal.yaml, broadway/event-store-dbal/0.2/manifest.json, broadway/event-store-mongodb/0.2/config/packages/broadway_event_store_mongodb.yaml, broadway/event-store-mongodb/0.2/manifest.json, broadway/read-model-elasticsearch/0.3/config/packages/broadway_read_model_elasticsearch.yaml, broadway/read-model-elasticsearch/0.3/manifest.json, broadway/read-model-mongodb/0.2/config/packages/broadway_read_model_mongodb.yaml, broadway/read-model-mongodb/0.2/manifest.json
=> add recipes for Broadway

knplabs/dictionary-bundle/2.0/config/packages/knp_dictionary.yaml, knplabs/dictionary-bundle/2.0/manifest.json
Recipe for https://github.com/KnpLabs/DictionaryBundle
=> Add KNPLabs Dictionary bundle recipe

sonata-project/admin-bundle/3.31/config/packages/sonata_admin.yaml, sonata-project/admin-bundle/3.31/config/routes/sonata_admin.yaml, sonata-project/admin-bundle/3.31/manifest.json
=> add sonata admin bundle

onurb/doctrine-yuml-bundle/1.1/config/routes/dev/yuml.yaml, onurb/doctrine-yuml-bundle/1.1/manifest.json
=> add onurb/doctrine-yuml-bundle recipe

beelab/test-bundle/2.0/manifest.json
=> add recipe for BeelabTestBundle

nella/monolog-tracy-bundle/2.0/config/packages/nella_monolog_tracy.yaml, nella/monolog-tracy-bundle/2.0/manifest.json
Bundle URL: https://github.com/nella/monolog-tracy-bundle
=> Add recipe for nella/monolog-tracy-bundle

shivas/versioning-bundle/3.1/manifest.json
Adding recipe for https://packagist.org/packages/shivas/versioning-bundle version 3.1 and higher.
=> Add recipe for ShivasVersioningBundle

flagception/flagception-bundle/3.0/config/packages/flagception.yaml, flagception/flagception-bundle/3.0/manifest.json
Add the FlagceptionBundle ( https://packagist.org/packages/flagception/flagception-bundle ).
It's a feature toggle system.
=> Add flagception bundle recipe

symfony-bundles/redis-bundle/2.0/config/packages/sb_redis.yaml, symfony-bundles/redis-bundle/2.0/manifest.json
=> Add recipe for SymfonyBundlesRedisBundle

google/apiclient/2.0/config/packages/google_apiclient.yaml, google/apiclient/2.0/manifest.json
Added Client and Secret key values in config.
Very useful for most of the calls which require these two values.
=> Added Client and Secret keys

lexik/maintenance-bundle/2.1/config/packages/lexik_maintenance.yaml, lexik/maintenance-bundle/2.1/manifest.json
=> Create recipe for lexik/maintenance-bundle

.travis.yml
=> Display the list of packages being required during testing

goetas/twital-bundle/1.3/config/packages/twital.yaml, goetas/twital-bundle/1.3/manifest.json
This is a recipe for https://github.com/goetas/twital-bundle
A fully compatible Twig template engine with enhanced syntax.
=> Add twital bundle recipe

cache/adapter-bundle/1.1/config/packages/cache_adapter.yaml, cache/adapter-bundle/1.1/manifest.json
=> Removing incompativle environment variable usage.

mediamonks/sonata-media-bundle/2.0/config/packages/mediamonks_sonata_media.yaml, mediamonks/sonata-media-bundle/2.0/config/routes/mediamonks_sonata_media.yaml, mediamonks/sonata-media-bundle/2.0/manifest.json, mediamonks/sonata-media-bundle/2.0/post-install.txt, mediamonks/sonata-media-bundle/2.0/src/Entity/Media.php
=> Add recipe for MediaMonks Sonata Media Bundle 2.0

kriswallsmith/buzz/0.17/config/packages/buzz.yaml, kriswallsmith/buzz/0.17/manifest.json
Note, version 0.17 is not released yet.
=> Added recipe for Buzz

msgphp/eav-bundle/0.2/src/Entity/Eav/Attribute.php, msgphp/eav-bundle/0.2/src/Entity/Eav/AttributeValue.php
=>  [MsgPhpEavBundle] enable doctrine mapping

beelab/recaptcha2-bundle/2.0/config/packages/beelab_recaptcha2.yaml, beelab/recaptcha2-bundle/2.0/manifest.json, beelab/recaptcha2-bundle/2.0/post-install.txt
=> add BeelabRecaptcha2Bundle

sebtm/inwx-api-bundle/0.1/manifest.json
=> Add recipe for sebtm/inwx-api-bundle

nelmio/alice/3.2/config/packages/nelmio_alice.yaml, nelmio/alice/3.2/manifest.json
=> Add nelmio alice

nelmio/api-doc-bundle/3.0/config/routes/nelmio_api_doc.yaml
=> [TYPO] nelmio/api-doc-bundle

msgphp/user-bundle/0.2/src/Entity/User/User.php
=> [MsgPhpUserBundle] Add ORM GeneratedValue annotation

sonata-project/media-bundle/3.13/config/packages/sonata_media.yaml, sonata-project/media-bundle/3.13/config/routes/sonata_media.yaml, sonata-project/media-bundle/3.13/manifest.json, sonata-project/media-bundle/3.13/public/upload/media/.gitignore
=> Add sonata-project/media-bundle recipe

thecodingmachine/tdbm-bundle/5.0/config/packages/tdbm.yaml, thecodingmachine/tdbm-bundle/5.0/manifest.json
This PR adds support for the tdbm-bundle: https://github.com/thecodingmachine/tdbm-bundle
=> Add tdbm-bundle recipe

elephantly/kahlan-bundle/0.9/manifest.json
=> Add recipe for elephantly/kahlan-bundle

phpfastcache/phpfastcache-bundle/3.0/config/packages/phpfastcache.yaml, phpfastcache/phpfastcache-bundle/3.0/manifest.json
=> Add recipe for phpfastcache/phpfastcache-bundle

weglot/translate-bundle/0.6/post-install.txt
=> Updating weglot/translate-bundle recipe

beelab/tag-bundle/1.3/config/packages/beelab_tag.yaml, beelab/tag-bundle/1.3/manifest.json, beelab/tag-bundle/1.3/post-install.txt, beelab/tag-bundle/1.3/src/Entity/Tag.php
=> add recipe for BeelabTagBundle

sonata-project/notification-orm-pack/1.0/config/packages/sonata_notification_orm.yaml, sonata-project/notification-orm-pack/1.0/manifest.json, sonata-project/notification-orm-pack/1.0/src/Entity/SonataNotificationMessage.php
=> Add sonata-project/notification-orm-pack recipe

sonata-project/media-orm-pack/1.0/config/packages/sonata_media_orm.yaml, sonata-project/media-orm-pack/1.0/manifest.json, sonata-project/media-orm-pack/1.0/src/Entity/SonataMediaGallery.php, sonata-project/media-orm-pack/1.0/src/Entity/SonataMediaGalleryHasMedia.php, sonata-project/media-orm-pack/1.0/src/Entity/SonataMediaMedia.php
=> Add sonata-project/media-orm-pack recipe

redirectionio/proxy-symfony/0.1/config/packages/redirectionio.yaml, redirectionio/proxy-symfony/0.1/manifest.json
This PR add a recipe for [redirection.io proxy](https://github.com/redirectionio/proxy-symfony)
=> Add recipe for redirection.io proxy

mmucklo/grid-bundle/4.0/config/packages/dtc_grid.yaml
=> mmucklo/grid-bundle: change to support bootstrap 4.1 and update default jQuery

sonata-project/media-orm-pack/1.0/config/packages/sonata_media_orm.yaml, sonata-project/media-orm-pack/1.0/post-install.txt, sonata-project/media-orm-pack/1.0/src/Entity/SonataMediaMedia.php
This PR will allow to update database schema after installation `sonata-project/classification-bundle` with new recipe from #389
=> Fix recipes for sonata-project/media-orm-pack

webinarium/symfony-lazysec/2.1/config/packages/lazysec.yaml, webinarium/symfony-lazysec/2.1/manifest.json
=> Add support for Symfony 4.1 to 'webinarium/symfony-lazysec'

sonata-project/page-bundle/3.9/config/packages/sonata_page.yaml, sonata-project/page-bundle/3.9/config/routes/sonata_page.yaml, sonata-project/page-bundle/3.9/manifest.json, sonata-project/page-bundle/3.9/src/Entity/SonataPageBlock.php, sonata-project/page-bundle/3.9/src/Entity/SonataPagePage.php, sonata-project/page-bundle/3.9/src/Entity/SonataPageSite.php, sonata-project/page-bundle/3.9/src/Entity/SonataPageSnapshot.php
=> Add recipe for sonata-project/page-bundle

sonata-project/translation-bundle/2.3/config/packages/sonata_translation.yaml, sonata-project/translation-bundle/2.3/manifest.json
=> Add recipe for sonata-project/translation-bundle

sonata-project/classification-bundle/3.7/config/packages/sonata_classification.yaml, sonata-project/classification-bundle/3.7/manifest.json, sonata-project/classification-bundle/3.7/src/Entity/SonataClassificationCategory.php, sonata-project/classification-bundle/3.7/src/Entity/SonataClassificationCollection.php, sonata-project/classification-bundle/3.7/src/Entity/SonataClassificationContext.php, sonata-project/classification-bundle/3.7/src/Entity/SonataClassificationTag.php
=> Add recipe for sonata-project/classification-bundle

dekalee/mailjet-bundle/0.5/config/packages/dekalee_mailjet.yaml, dekalee/mailjet-bundle/0.5/manifest.json, dekalee/mailjet-bundle/0.5/post-install.txt
=> add dekalee mailjet bundle configuration

lepiaf/sapient-bundle/0.1/config/packages/sapient.yaml, lepiaf/sapient-bundle/0.1/manifest.json, lepiaf/sapient-bundle/0.1/post-install.txt
=> Add sapient-bundle recipe

contentful/contentful-bundle/3.0/config/packages/contentful.yaml, contentful/contentful-bundle/3.0/manifest.json, contentful/contentful-bundle/3.0/post-install.txt
=> Add support for ContentfulBundle

netbull/security-bundle/1.0/config/packages/netbull_security.yaml, netbull/security-bundle/1.0/manifest.json
=> removed unnecessary config

silasjoisten/sonata-multiupload-bundle/2.1/config/packages/sonata_multi_upload.yaml, silasjoisten/sonata-multiupload-bundle/2.1/manifest.json
=> new recipe for silasjoisten/sonata-multiupload-bundle

leapt/core-bundle/2.2/config/packages/leapt_core.yaml, leapt/core-bundle/2.2/manifest.json
=> Add Leapt Core bundle recipe

atlas/symfony/1.0/manifest.json
=> Add recipe "atlas/symfony"

toiba/fullcalendar-bundle/6.2/config/routes/fullcalendar.yaml, toiba/fullcalendar-bundle/6.2/manifest.json
=> Add recipe for toiba/fullcalendar-bundle

sebtm/inwx-api-bundle/0.2/config/packages/inwx_api.yaml, sebtm/inwx-api-bundle/0.2/manifest.json
=> Add updated recipe for inwx-api-bundle v0.2

hwi/oauth-bundle/0.6/post-install.txt
Q | A
-- | --
License | MIT
In a previous commit the firewall was changed to main in the configuration. This should be changed too.
=> Firewall was changed to main.

enqueue/messenger-adapter/0.1/manifest.json
=> Enable Enqueue's messenger bundle

tsantos/serializer-bundle/1.0/config/packages/prod/tsantos_serializer.yaml, tsantos/serializer-bundle/1.0/config/packages/test/tsantos_serializer.yaml, tsantos/serializer-bundle/1.0/config/packages/tsantos_serializer.yaml, tsantos/serializer-bundle/1.0/manifest.json
=> Add tsantos serializer recipe

pugx/geo-form-bundle/0.2/config/packages/pugx_geo_form.yaml, pugx/geo-form-bundle/0.2/manifest.json, pugx/geo-form-bundle/0.2/post-install.txt
=> add recipe for PUGXGeoFormBundle

birkof/netopia-mobilpay-bundle/1.0/config/packages/netopia_mobilpay.yaml, birkof/netopia-mobilpay-bundle/1.0/manifest.json
=> Add SMS Payment method on Netopia mobilpay bundle

slot/mandrill-bundle/1.1/config/packages/slot_mandrill.yaml, slot/mandrill-bundle/1.1/manifest.json
=> add slot/mandrill-bundle

expertcoder/swiftmailer-send-grid-bundle/2.0/config/packages/expert_coder_swiftmailer_send_grid.yaml
Typo found in provided config file
=> Fix recipe for ExpertCoder Swiftmailer SendGrid Bundle

squizlabs/php_codesniffer/3.0/manifest.json, squizlabs/php_codesniffer/3.0/phpcs.xml.dist
=> Add basic squizlabs/php_codesniffer configuration

contao/core-bundle/4.6/manifest.json
=> Add missing gitignore paths to the Contao recipe

jolicode/jolitypo/1.0/config/packages/joli_typo.yaml, jolicode/jolitypo/1.0/manifest.json
=> Add recipe for jolicode/jolitypo

enqueue/mongodb/0.8/manifest.json
=> [enqueue][mongodb] Add manifest for enqueue\mongodb package.

enqueue/fs/0.8/manifest.json
fixes https://github.com/php-enqueue/enqueue-dev/issues/520
=> [enqueue][fs] Fix file transport DSN

ruwler/ruwler-sdk-bundle/1.0/config/packages/ruwler_sdk.yaml, ruwler/ruwler-sdk-bundle/1.0/manifest.json
=> Add ruwler recipe

liip/imagine-bundle/1.8/post-install.txt
=> replace imagine.yaml to liip_imagine.yaml which is the correct filename

anezi/locale-extension/1.0/config/packages/anezi_locale_extension.yaml, anezi/locale-extension/1.0/manifest.json
=> Added anezi/locale-extension recipe.

overblog/graphql-bundle/0.12/config/packages/graphql.yaml, overblog/graphql-bundle/0.12/config/routes/graphql.yaml, overblog/graphql-bundle/0.12/manifest.json, overblog/graphql-bundle/0.12/post-install.txt, overblog/graphql-bundle/0.9/post-install.txt
=> [OverblogGraphQLBundle] Init 0.12 and fix doc link in post install

hautelook/alice-bundle/2.1/manifest.json
Also replaces a useless section. /cc @theofidry
=> AliceBundle: create the fixtures/ dir

knpuniversity/oauth2-client-bundle/1.20/config/packages/knpu_oauth2_client.yaml, knpuniversity/oauth2-client-bundle/1.20/config/packages/post-install.txt, knpuniversity/oauth2-client-bundle/1.20/manifest.json
=> Knpuniversity oauth2 client bundle

hautelook/alice-bundle/2.1/post-install.txt
=> [AliceBundle] Add a post install message

beelab/tag-bundle/1.3/src/Entity/Tag.php
See https://github.com/Bee-Lab/BeelabTagBundle/issues/11
=> fix compatibility with interface

liuggio/statsd-client-bundle/1.6/config/packages/liuggio_stats_d_client.yaml, liuggio/statsd-client-bundle/1.6/manifest.json
=> add liuggio/statsd-client-bundle

sylius/refund-plugin/0.4/config/packages/sylius_refund.yaml, sylius/refund-plugin/0.4/config/routes/sylius_refund.yaml, sylius/refund-plugin/0.4/manifest.json
=> Add a recipe for sylius/refund-plugin

sylius/customer-order-cancellation-plugin/0.2/config/routes/sylius_customer_order_cancellation.yaml, sylius/customer-order-cancellation-plugin/0.2/manifest.json
=> Add a recipe for sylius/customer-order-cancellation-plugin

sylius/invoicing-plugin/0.5/config/packages/sylius_invoicing.yaml, sylius/invoicing-plugin/0.5/config/routes/sylius_invoicing.yaml, sylius/invoicing-plugin/0.5/manifest.json
=> Add a recipe for sylius/invoicing-plugin

sylius/customer-reorder-plugin/1.0/config/packages/sylius_customer_reorder.yaml, sylius/customer-reorder-plugin/1.0/config/routes/sylius_customer_reorder.yaml, sylius/customer-reorder-plugin/1.0/manifest.json
=> Add a recipe for sylius/customer-reorder-plugin

sylius/admin-order-creation-plugin/0.6/config/packages/sylius_admin_order_creation.yaml, sylius/admin-order-creation-plugin/0.6/config/routes/sylius_admin_order_creation.yaml, sylius/admin-order-creation-plugin/0.6/manifest.json
=> Add a recipe for sylius/admin-order-creation-plugin

misd/phone-number-bundle/1.3/config/packages/misd_phone_number.yaml, misd/phone-number-bundle/1.3/manifest.json, misd/phone-number-bundle/1.3/post-install.txt
=> Adds misd/phone-number-bundle v1.3

eko/feedbundle/1.2/config/packages/eko_feed.yaml, eko/feedbundle/1.2/manifest.json
=> Add recipe for eko/feedbundle

core23/lastfm-bundle/0.4/config/packages/core23_lastfm.yaml, core23/lastfm-bundle/0.4/manifest.json
=> Added core23/lastfm-bundle

core23/gdpr-bundle/0.2/config/packages/core23_gdpr.yaml, core23/gdpr-bundle/0.2/manifest.json
=> Added core23/gdpr-bundle

core23/shariff-bundle/3.0/config/packages/core23_shariff.yaml, core23/shariff-bundle/3.0/config/routes/core23_shariff.yaml, core23/shariff-bundle/3.0/manifest.json
=> Added core23/shariff-bundle

core23/matomo-bundle/1.1/config/packages/core23_matomo.yaml, core23/matomo-bundle/1.1/manifest.json
=> Added core23/matomo-bundle

friendsofsymfony/ckeditor-bundle/2.0/config/packages/fos_ckeditor.yaml, friendsofsymfony/ckeditor-bundle/2.0/manifest.json
closes https://github.com/FriendsOfSymfony/FOSCKEditorBundle/issues/142
=> Add recipe for FOSCKEditorBundle

birkof/netopia-mobilpay-bundle/1.0/config/packages/netopia_mobilpay.yaml, birkof/netopia-mobilpay-bundle/1.0/manifest.json
=> Netopia mobilpay bundle update

liuggio/statsd-client-bundle/1.6/manifest.json
=> update statsd bundle manifest

m-adamski/symfony-schedule-bundle/1.0/config/packages/schedule.yaml, m-adamski/symfony-schedule-bundle/1.0/manifest.json
=> Added recipes for Schedule Bundle

ajardin/docker-symfony/0.2/bin/docker-upgrade, ajardin/docker-symfony/0.2/manifest.json, ajardin/docker-symfony/0.2/post-install.txt
=> Add recipe for ajardin/docker-symfony

scheb/two-factor-bundle/3.16/config/packages/scheb_two_factor.yaml, scheb/two-factor-bundle/3.16/config/routes/scheb_two_factor.yaml, scheb/two-factor-bundle/3.16/manifest.json
Recipe for version 3.x of https://github.com/scheb/two-factor-bundle
=> Add recipe for scheb/two-factor-bundle

core23/facebook-bundle/0.4/config/packages/core23_facebook.yaml, core23/facebook-bundle/0.4/manifest.json
=> Added core23/facebook-bundle

dekalee/mailjet-bundle/2.1/config/packages/dekalee_mailjet.yaml, dekalee/mailjet-bundle/2.1/manifest.json, dekalee/mailjet-bundle/2.1/post-install.txt
Add configuration for debug capabilities offered by mailjet
complete documentation
=> Update mailjet bundle configuration

emanuilnikolov/igdb-api-bundle/1.0/config/packages/en_igdb_api.yaml, emanuilnikolov/igdb-api-bundle/1.0/manifest.json
=> Add recipe for IgdbApiBundle

m-adamski/symfony-mailer-bundle/1.0/config/packages/mailer.yaml, m-adamski/symfony-mailer-bundle/1.0/manifest.json
=> Added recipes for Mailer Bundle

google/recaptcha/1.1/config/packages/google_recaptcha.yaml
=> Fix Google ReCaptcha RequestMethod injection

merceslab/spreadsheet-client-bundle/1.0/config/packages/merces_lab_spreadsheet_client.yaml, merceslab/spreadsheet-client-bundle/1.0/manifest.json, merceslab/spreadsheet-client-bundle/1.0/post-install.txt
=> Add recipe for merceslab/spreadsheet-client-bundle

artprima/prometheus-metrics-bundle/1.0/config/packages/prometheus_metrics.yaml, artprima/prometheus-metrics-bundle/1.0/config/packages/test/prometheus_metrics.yaml, artprima/prometheus-metrics-bundle/1.0/config/routes/metrics.yaml, artprima/prometheus-metrics-bundle/1.0/manifest.json
=> add support for artprima/prometheus-metrics-bundle

nyholm/psr7/1.0/config/packages/nyholm_psr7.yaml, nyholm/psr7/1.0/manifest.json
=> Recipe for nyholm/psr7:1.0

jms/serializer-bundle/3.0/config/packages/dev/jms_serializer.yaml, jms/serializer-bundle/3.0/config/packages/jms_serializer.yaml, jms/serializer-bundle/3.0/config/packages/prod/jms_serializer.yaml, jms/serializer-bundle/3.0/manifest.json
=> Add jms/serializer-bundle v3 recipes

tgalopin/html-sanitizer-bundle/1.0/config/packages/html_sanitizer.yaml, tgalopin/html-sanitizer-bundle/1.0/manifest.json
=> Create tgalopin/html-sanitizer-bundle recipe

gheb/data-migrations-bundle/1.3/config/packages/data_migrations.yaml, gheb/data-migrations-bundle/1.3/manifest.json
=> create gheb\data-migrations-bundle recipe

enqueue/async-command/0.9/config/packages/enqueue_async_command.yaml, enqueue/async-command/0.9/manifest.json, enqueue/async-event-dispatcher/0.9/config/packages/enqueue_async_event_dispatcher.yaml, enqueue/async-event-dispatcher/0.9/manifest.json, enqueue/enqueue-bundle/0.9/config/packages/enqueue.yaml, enqueue/enqueue-bundle/0.9/config/packages/test/enqueue.yaml, enqueue/enqueue-bundle/0.9/manifest.json, enqueue/job-queue-pack/0.9/config/packages/enqueue_job_queue.yaml, enqueue/job-queue-pack/0.9/manifest.json, enqueue/wamp/0.9/manifest.json
fixes https://github.com/php-enqueue/enqueue-dev/issues/600
=> Add receipes for Enqueue 0.9.

mailjet/mailjet-bundle/1.0/config/packages/mailjet.yaml, mailjet/mailjet-bundle/1.0/manifest.json
Related : https://github.com/mailjet/mailjetBundle/issues/7
=> Add mailjet/mailjet-bundle recipe

ramsey/uuid-doctrine/1.3/config/packages/ramsey_uuid_doctrine.yaml
=> removed whitespace an use string explicitely

nyholm/psr7/0.3/config/packages/nyholm_psr7.yaml, nyholm/psr7/1.0/config/packages/nyholm_psr7.yaml
=> Fixed typo in nyholm/psr7

.travis.yml
=> Fix the Flex server endpoint

friends-of-behat/symfony-extension/2.0/behat.yml.dist, friends-of-behat/symfony-extension/2.0/config/services_test.yaml, friends-of-behat/symfony-extension/2.0/features/demo.feature, friends-of-behat/symfony-extension/2.0/manifest.json, friends-of-behat/symfony-extension/2.0/post-install.txt, friends-of-behat/symfony-extension/2.0/tests/Behat/DemoContext.php
Most of this PR was heavily inspired by [Behat/Symfony2Extension recipe](https://github.com/symfony/recipes/tree/master/behat/symfony2-extension/2.1/), which basically has the same purpose but the implementation differs. It includes the exemplary feature & its implementation so that the extensions configurations might be compared more easily.
The stable release is coming in the next few days.
=> Provide recipe for FriendsOfBehat/SymfonyExtension v2

doctrine/mongodb-odm-bundle/3.3/config/packages/doctrine_mongodb.yaml, doctrine/mongodb-odm-bundle/3.3/manifest.json
=> [doctrine_mongodb] adding fallback env vars

doctrine/mongodb-odm-bundle/3.3/config/packages/doctrine_mongodb.yaml, doctrine/mongodb-odm-bundle/3.3/config/packages/prod/doctrine_mongodb.yaml
=> [doctrine_mongodb] add a metadata cache in prod

kunicmarko/jms-messenger-adapter/0.1/config/packages/jms_messenger.yaml, kunicmarko/jms-messenger-adapter/0.1/manifest.json
=> Add jms-messenger-adapter

neo4j/neo4j-bundle/0.4/config/packages/neo4j.yaml
* Fixed ENV var name: NEO4J_DEFAULT_CONNECTION => NEO4J_DEFAULT_CONNECTION_DSN
=> neo4j.yaml fixes

endroid/guide-bundle/2.0/config/packages/endroid_guide.yaml, endroid/guide-bundle/2.0/config/routes/endroid_guide.yaml, endroid/guide-bundle/2.0/manifest.json
Not needed anymore because the package provides its own installation.
=> Remove guide bundle

mcfedr/awspushbundle/6.11/config/packages/awspush.yaml, mcfedr/awspushbundle/6.11/manifest.json, mcfedr/awspushbundle/6.11/post-install.txt
=> Add AWS push bundle

contentful/contentful-bundle/4.0/config/packages/contentful.yaml, contentful/contentful-bundle/4.0/manifest.json, contentful/contentful-bundle/4.0/post-install.txt
This PR adds support for ContentfulBundle 4.0, which uses a configuration format different from the previous 3.0 (also available with Symfony Flex).
=> Add support for ContentfulBundle 4.0

spomky-labs/lexik-jose-bridge/2.0/config/packages/spomky_labs_lexik_jose_bridge_bundle.yaml
Fix https://github.com/Spomky-Labs/lexik-jose-bridge/issues/44
=> Wrong key index

coka/api-bundle/3.0/config/packages/oka_api.yaml, coka/file-bundle/3.0/config/packages/oka_file.yaml, coka/file-bundle/3.0/manifest.json, coka/pagination-bundle/3.0/config/packages/oka_pagination.yaml, coka/pagination-bundle/3.0/manifest.json
=> * Add a recipe for coka/pagination-bundle

msgphp/user-bundle/0.10/config/packages/msgphp_user.php, msgphp/user-bundle/0.10/src/Entity/User.php
cc @chalasr (sorry i forgot to push this)
=> fix wrong classname

doctrine/doctrine-cache-bundle/1.3/config/packages/doctrine_cache.yaml, doctrine/doctrine-cache-bundle/1.3/manifest.json
Implement https://github.com/doctrine/DoctrineCacheBundle/issues/131
#SymfonyHackday2018
=> Add a recipe for DoctrineCacheBundle

php-http/httplug-bundle/1.6/config/packages/httplug.yaml, php-http/httplug-bundle/1.6/manifest.json
=> Move recipes from recipes to recipes-contrib

tattali/calendar-bundle/1.1/config/routes/calendar.yaml, tattali/calendar-bundle/1.1/manifest.json
=> Add recipe for tattali/CalendarBundle

lireincore/imgcache-bundle/0.1/config/packages/lireincore_imgcache.yaml, lireincore/imgcache-bundle/0.1/manifest.json
=> added lireincore/imgcache-bundle recipe

ro0nl/http-responder/0.1/manifest.json
=> Add HttpResponderBundle

mmucklo/grid-bundle/4.0/config/packages/dtc_grid.yaml, mmucklo/grid-bundle/4.2/config/routes/dtc_grid.yaml, mmucklo/grid-bundle/4.2/manifest.json, mmucklo/grid-bundle/4.2/post-install.txt
=> mmucklo/grid-bundle datatables bootstrap4 fix, and update for v4.2

insidestyles/swoole-bridge-bundle/0.4/config/packages/swoole_bridge.yaml, insidestyles/swoole-bridge-bundle/0.4/manifest.json
=> swoole-bridge-bundle

happyr/linkedin-api-client/1.0/manifest.json, mailgun/mailgun-php/2.3/manifest.json
=> Cleaned up manifest files from characters not needed

swarrot/swarrot-bundle/1.6/config/packages/swarrot.yaml, swarrot/swarrot-bundle/1.6/manifest.json
Integration for Swarrot AMQP bundle.
=> Add recipe for Swarrot bundle

doctrine/phpcr-bundle/2.0/config/packages/doctrine_phpcr.yaml, doctrine/phpcr-bundle/2.0/manifest.json
=> Added recipe for DoctrinePHPCRBundle

excelwebzone/recaptcha-bundle/1.5/config/packages/dev/ewz_recaptcha.yaml, excelwebzone/recaptcha-bundle/1.5/config/packages/ewz_recaptcha.yaml, excelwebzone/recaptcha-bundle/1.5/manifest.json
=> Add EWZRecaptchaBundle

theplankmeister/form-data-transposer/1.0/manifest.json
=> Create recipe for theplankmeister/form-data-transposer

disjfa/translation-bundle/0.1/config/routes/disjfa_translation.yaml, disjfa/translation-bundle/0.1/manifest.json
=> Add disjfa/translation bundle

troopers/alertify-bundle/3.0/config/packages/troopers_alertify.yaml, troopers/alertify-bundle/3.0/manifest.json, troopers/alertify-bundle/3.0/post-install.txt
=> add troopers/alertify-bundle recipe

liip/imagine-bundle/1.8/config/packages/liip_imagine.yaml
Files like this does not bring any value. 
#eu-fossa
=> [LiipImagine] Remove comments not needed

gheb/configuration-converter-bundle/0.5/config/packages/configuration_converter.yaml, gheb/configuration-converter-bundle/0.5/manifest.json, gheb/configuration-converter-bundle/0.5/post-install.txt
=> Configuration converter

league/flysystem-bundle/1.0/config/packages/flysystem.yaml, league/flysystem-bundle/1.0/manifest.json, league/flysystem-bundle/1.0/post-install.txt
Package: https://github.com/thephpleague/flysystem-bundle
=> Add flysystem-bundle recipe

wow-apps/symfony-slack-bot/4.0/config/packages/wow_apps_slack.yaml, wow-apps/symfony-slack-bot/4.0/manifest.json
Added recipe for version 4.0 of wow-apps/symfony-slack-bot
=> Added recipe for version 4.0

redirectionio/proxy-symfony/0.1/config/packages/redirectionio.yaml
=> [Redirection.io] Use default port

insidestyles/json-rpc-bundle/1.0/config/packages/json_rpc_api.yaml, insidestyles/json-rpc-bundle/1.0/config/routes/json_rpc_api_routing.yaml, insidestyles/json-rpc-bundle/1.0/manifest.json
A simple way to install json rpc api using symfony messenger and zend json server
=> json-rpc-bundle

zephyr/allmysms-bundle/1.0/config/zephyrhq_allmysms.yaml, zephyr/allmysms-bundle/1.0/manifest.json
=> Add allmysms bundle

nicohaase/twig-isbn-formatter/0.1/config/packages/twig_isbn_formatter.yaml, nicohaase/twig-isbn-formatter/0.1/manifest.json
Adding a recipe for nicohaase/twig-isbn-formatter
=> Recipe for nicohaase/twig-isbn-formatter 

notfloran/mjml-bundle/3.0/config/packages/mjml.yaml, notfloran/mjml-bundle/3.0/config/packages/prod/mjml.yaml, notfloran/mjml-bundle/3.0/manifest.json, notfloran/mjml-bundle/3.0/post-install.txt
=> Add notfloran/mjml-bundle

coka/api-bundle/4.0/config/packages/oka_api.yaml, coka/api-bundle/4.0/manifest.json, coka/cors-bundle/1.0/config/packages/oka_cors.yaml, coka/cors-bundle/1.0/manifest.json, coka/wsse-authentication-bundle/1.0/config/packages/oka_wsse_authentication.yaml, coka/wsse-authentication-bundle/1.0/manifest.json
=> Add new recipes and update old

basster/twig-base64-extension/1.0/config/packages/basster_twig_base64.yaml, basster/twig-base64-extension/1.0/manifest.json
=> add recipe for basster/twig-base64-extension

redirectionio/proxy-symfony/0.2/config/packages/redirectionio.yaml, redirectionio/proxy-symfony/0.2/manifest.json
Fixes https://github.com/redirectionio/proxy-symfony/issues/2
=> [Redirection.io] Add project_key to the configuration

teebbstudios/tuieditor-bundle/1.0/config/packages/teebb_tuieditor.yaml, teebbstudios/tuieditor-bundle/1.0/manifest.json
=> Add TeebbTuiEditorBundle recipe

netgen/content-browser/1.0/config/routes/netgen_content_browser.yaml, netgen/content-browser/1.0/manifest.json, netgen/content-browser/1.0/post-install.txt
=> Add recipe for netgen/content-browser

symfonycorp/connect-bundle/5.0/config/packages/symfony_connect.yaml, symfonycorp/connect-bundle/5.0/config/routes/symfony_connect.yaml, symfonycorp/connect-bundle/5.0/manifest.json
=> Add SymfonyConnect bundle

.travis.yml
Trying to fix https://travis-ci.org/symfony/recipes-contrib/jobs/562997589
=> Use PHP 7.4 to run the CI

kms/froala-editor-bundle/3.0/config/packages/kms_froala_editor.yaml, kms/froala-editor-bundle/3.0/config/routes/kms_froala_editor.yaml, kms/froala-editor-bundle/3.0/manifest.json
=> Added KMSFroalaEditorBundle recipe

armin/scssphp-bundle/1.0/config/packages/prod/scssphp.yaml, armin/scssphp-bundle/1.0/config/packages/scssphp.yaml, armin/scssphp-bundle/1.0/manifest.json
=> Add armin/scssphp-bundle 1.0

gpslab/geoip2/1.1/config/packages/gpslab_geoip.yaml, gpslab/geoip2/1.1/manifest.json
=> Add a Symfony Bundle for the Maxmind GeoIP2 API

ravenflux/env-in-twig/1.0/config/packages/ravenflux_env_in_twig.yaml, ravenflux/env-in-twig/1.0/manifest.json, ravenflux/php-functions/1.0/config/packages/ravenflux_php_functions.yaml, ravenflux/php-functions/1.0/manifest.json, ravenflux/sort-functions/1.0/config/packages/ravenflux_sort_functions.yaml, ravenflux/sort-functions/1.0/manifest.json
=> Add ravenflux extensions

netgen/content-browser/1.0/post-install.txt
=> netgen/content-browser: Improve post install text, fix link to docs

trikoder/oauth2-bundle/2.0/config/packages/trikoder_oauth2.yaml, trikoder/oauth2-bundle/2.0/config/routes/trikoder_oauth2.yaml, trikoder/oauth2-bundle/2.0/manifest.json, trikoder/oauth2-bundle/2.0/post-install.txt
=> Add oauth2-bundle contrib recipe

lexik/cron-file-generator-bundle/1.0/config/packages/lexik_cron_file_generator.yaml, lexik/cron-file-generator-bundle/1.0/manifest.json
=> add recipe for LexikCronFileGeneratorBundle 

basster/lazy-response-bundle/1.0/config/packages/basster_lazy_response.yaml, basster/lazy-response-bundle/1.0/manifest.json
=> added receipe for basster/lazy-response-bundle 1.0

becklyn/gluggi-bundle/3.1/config/routes/dev/gluggi.yaml, becklyn/gluggi-bundle/3.1/manifest.json
Adding the recipe for https://packagist.org/packages/becklyn/gluggi-bundle
=> Add becklyn/gluggi-bundle

becklyn/assets-bundle/2.4/config/routes/becklyn_assets.yaml, becklyn/assets-bundle/2.4/manifest.json
Adding the recipe for https://packagist.org/packages/becklyn/assets-bundle
=> Add becklyn/assets-bundle

kynno/smartbots-bundle/0.1/config/packages/smartbots.yaml, kynno/smartbots-bundle/0.1/manifest.json
=> Add kynno/smartbots-bundle

friendsofsymfony/elastica-bundle/5.0/config/packages/fos_elastica.yaml, friendsofsymfony/elastica-bundle/5.0/manifest.json
Changed connection type and added environment variable.
=> [friendsofsymfony/elastica-bundle] added environment variable and changed connection client

becklyn/translations/1.0/config/routes/becklyn_translations.yaml, becklyn/translations/1.0/manifest.json
Adding the recipe for https://packagist.org/packages/becklyn/translations
=> Add becklyn/translations

becklyn/javascript-routing/1.0/config/routes/becklyn_javascript_routing.yaml, becklyn/javascript-routing/1.0/manifest.json
Adding the recipe for https://packagist.org/packages/becklyn/javascript-routing
=> Add becklyn/javascript-routing bundle

zendesk/zendesk_api_client_php/2.2/config/packages/zendesk_api_client.yaml, zendesk/zendesk_api_client_php/2.2/manifest.json
Docs are there: https://github.com/zendesk/zendesk_api_client_php
I thought this simple setup would be enough for a basic Zendesk client.
=> Add Zendesk API recipe

mapado/rest-client-sdk-bundle/0.24/config/packages/mapado_rest_client_sdk.yaml, mapado/rest-client-sdk-bundle/0.24/manifest.json
Better compliance with flex new dotenv configuration
=> mapado/rest-client-sdk-bundle : Move from "old" configuration to env variable

antishov/doctrine-extensions-bundle/1.4/config/packages/stof_doctrine_extensions.yaml, antishov/doctrine-extensions-bundle/1.4/manifest.json
=> Added antishov/doctrine-extensions-bundle

boshurik/telegram-bot-bundle/3.1/config/packages/boshurik_telegram_bot.yaml, boshurik/telegram-bot-bundle/3.1/config/routes/boshurik_telegram_bot.yaml, boshurik/telegram-bot-bundle/3.1/manifest.json, boshurik/telegram-bot-bundle/3.1/post-install.txt
=> Recipe for boshurik/telegram-bot-bundle

coka/file-bundle/3.0/config/packages/oka_file.yaml, coka/file-bundle/3.0/manifest.json, coka/rate-limit-bundle/1.0/config/packages/oka_rate_limit.yaml, coka/rate-limit-bundle/1.0/manifest.json, coka/rest-request-validator-bundle/1.0/config/packages/oka_rest_request_validator.yaml, coka/rest-request-validator-bundle/1.0/manifest.json
=> Update coka recipes and add new recipes

symfony/apache-pack/1.0/public/.htaccess
Use simpler regex patterns, existing backreferences, and faster lexicographic test where possible.
As per [this comment](https://github.com/symfony/symfony/pull/34460#issuecomment-559417218) in my previous pull request.
=> Simplify Apache rewriting directives

odolbeau/phone-number-bundle/3.0/config/packages/misd_phone_number.yaml, odolbeau/phone-number-bundle/3.0/manifest.json, odolbeau/phone-number-bundle/3.0/post-install.txt
After lack of maintainance of the main bundle, we decided to fork the bundle, this recipe will help new users.
=> Add the fork of phone-number-bundle recipe

.travis.yml
=> Adding tests on Symfony5

ekreative/health-check-bundle/1.5/config/routes/ekreative_health_check.yaml, ekreative/health-check-bundle/1.5/manifest.json, ekreative/health-check-bundle/1.5/post-install.txt
=> Add ekreative/health-check-bundle

insidestyles/json-rpc-bundle/2.0/config/packages/json_rpc_api.yaml, insidestyles/json-rpc-bundle/2.0/config/routes/json_rpc_api_routing.yaml, insidestyles/json-rpc-bundle/2.0/manifest.json
=> Recipe for insidestyles/json-rpc-bundle V2

dekalee/pubsub-swarrot-bundle/1.0/config/packages/dekalee_pub_sub_swarrot.yaml, dekalee/pubsub-swarrot-bundle/1.0/manifest.json, dekalee/pubsub-swarrot-bundle/1.0/post-install.txt
=> [PubSubSwarrot] Add base configuration for pubsub bundle

dekalee/autopilot-bundle/1.0/config/packages/dekalee_autopilot_swarrot.yaml, dekalee/autopilot-bundle/1.0/manifest.json, dekalee/autopilot-bundle/1.0/post-install.txt
=> [AutopilotBundle] Add recepies for autopilot bundle

baldinof/roadrunner-bundle/0.1/config/packages/baldinof_road_runner.yaml, baldinof/roadrunner-bundle/0.1/manifest.json, baldinof/roadrunner-bundle/0.1/post-install.txt
=> Add baldinof/roadrunner-bundle

dekalee/enom-bundle/1.0/config/packages/dekalee_enom.yaml, dekalee/enom-bundle/1.0/manifest.json, dekalee/enom-bundle/1.0/post-install.txt
=> [EnomBundle] Add recipies for Enom Bundle

tg-bot-api/bot-api-base/1.0/config/packages/tg_bot_api.yaml, tg-bot-api/bot-api-base/1.0/manifest.json
=> Add tg-bot-api/bot-api-base

goksagun/scheduler-bundle/1.0/config/packages/scheduler.yaml, goksagun/scheduler-bundle/1.0/manifest.json, goksagun/scheduler-bundle/1.0/post-install.txt
=> Recipe for 1.0 version of goksagun/scheduler-bundle

knyk/mailbox-bundle/1.0/config/packages/knyk_mailbox.yaml, knyk/mailbox-bundle/1.0/manifest.json
=> Added 1.0 version of knyk/mailbox-bundle

mukadi/wallet-bundle/1.0/manifest.json
=> Add mukadi/wallet-bundle 1.0 support

karser/karser-recaptcha3-bundle/0.1/config/packages/karser_recaptcha3.yaml, karser/karser-recaptcha3-bundle/0.1/manifest.json, karser/karser-recaptcha3-bundle/0.1/post-install.txt
=> Add KarserRecaptcha3Bundle

thecodingmachine/graphqlite-bundle/4.0/manifest.json, thecodingmachine/graphqlite-bundle/4.0/post-install.txt
This PR upgrades the GraphQLite recipe to match the new v4 major version released a few minutes ago.
=> Upgrading GraphQLite recipe for v4 bundle

mtarld/symbok-bundle/2.0/config/packages/symbok.yaml, mtarld/symbok-bundle/2.0/manifest.json, mtarld/symbok-bundle/2.0/post-install.txt
=> Add SymbokBundle recipe

helios-ag/fm-elfinder-bundle/10.0/config/packages/fm_elfinder.yaml, helios-ag/fm-elfinder-bundle/10.0/config/routes/fm_elfinder.yaml, helios-ag/fm-elfinder-bundle/10.0/manifest.json
=> Added config for version 10

alexandret/evc-bundle/1.0/config/packages/alexandre_evc.yaml, alexandret/evc-bundle/1.0/manifest.json
=> Creating a manifest.json for alexandret/evc-bundle:1.0

jane-php/json-schema/5.0/bin/jane-generate, jane-php/json-schema/5.0/config/jane/config.php, jane-php/json-schema/5.0/config/packages/jane.yaml, jane-php/json-schema/5.0/manifest.json, jane-php/json-schema/5.0/post-install.txt
This PR bring a lot of DX around `jane-php/json-schema` package
=> Add jane-php/json-schema recipe

friendsofsymfony/elastica-bundle/5.0/config/packages/fos_elastica.yaml
=> Update documentation url in fos_elastica.yaml

mobizel/symfony-capistrano/0.2/manifest.json, mobizel/symfony-capistrano/0.2/post-install.txt
=> Recipe for mobizel/symfony-capistrano package

exercise/htmlpurifier-bundle/3.0/config/packages/exercise_html_purifier.yaml, exercise/htmlpurifier-bundle/3.0/manifest.json
Based on https://github.com/Exercise/HTMLPurifierBundle/pull/52.
=> Added config for ExerciseHTMLPurifierBundle 3.0

sebtm/inwx-api-bundle/1.0/config/packages/inwx_api.yaml, sebtm/inwx-api-bundle/1.0/manifest.json
=> Add recipe for inwx-api-bundle >= v1.0

nucleos/user-bundle/1.1/config/packages/nucleos_user.yaml, nucleos/user-bundle/1.1/config/routes/nucleos_user.yaml, nucleos/user-bundle/1.1/manifest.json, nucleos/user-bundle/1.1/src/Entity/User/Group.php, nucleos/user-bundle/1.1/src/Entity/User/User.php
=> Add nucleos/user-bundle

elao/enum/1.7/config/packages/elao_enum.yaml, elao/enum/1.7/manifest.json
=> Add elao/enum recipe

drenso/symfony-shared/0.8/manifest.json
Add recipe for the drenso/symfony-shared package
=> Add drenso/symfony-shared recipe

monsieurbiz/sylius-admin-better-login-plugin/1.0/manifest.json
=> Add manifest for monsieurbiz/sylius-admin-better-login-plugin 1.0

payum/payum-bundle/2.4/config/payum.yaml, payum/payum-bundle/2.4/manifest.json
=> Recipe for payum/payum-bundle 2.4

symfony-bundles/kafka-bundle/1.0/config/packages/sb_kafka.yaml
Q | A
-- | --
Bug fix? | yes
New feature? | no
Deprecations? | no
License | MIT
This PR fixes wrong config option "topics".
=> Fix symfony-bundles kafka-bundle config. Removed topics option

anyx/login-gate-bundle/1.0/config/packages/login_gate.yaml, anyx/login-gate-bundle/1.0/manifest.json
=> recipe for anyx/login-gate-bundle

async-aws/async-aws-bundle/0.1/config/packages/async_aws.yaml, async-aws/async-aws-bundle/0.1/manifest.json
https://github.com/async-aws/symfony-bundle
=> Adding recipe for async-aws/symfony-bundle

sonata-project/admin-bundle/3.64/config/packages/sonata_admin.yaml, sonata-project/admin-bundle/3.64/config/routes/sonata_admin.yaml, sonata-project/admin-bundle/3.64/manifest.json, sonata-project/admin-bundle/3.64/src/Admin/.gitignore
=> Set "sonata_admin.options.legacy_twig_text_extension" option

msalsas/gdpr-consent-banner-bundle/1.0/config/packages/msalsas_gdpr_consent_banner.yaml, msalsas/gdpr-consent-banner-bundle/1.0/config/routes/msalsas_gdpr_consent_banner.yaml, msalsas/gdpr-consent-banner-bundle/1.0/manifest.json
=> Add MsalsasGdprConsentBannerBundle recipe

vincentchalamon/nav-bundle/1.0/config/packages/nav.yaml, vincentchalamon/nav-bundle/1.0/manifest.json
| Related issue | https://github.com/vincentchalamon/nav-bundle/issues/5
=> Add vincentchalamon/nav-bundle

mmucklo/queue-bundle/6.0/config/routes/dtc_queue.yaml, mmucklo/queue-bundle/6.0/manifest.json, mmucklo/queue-bundle/6.0/post-install.txt
=> Updates for mmucklo/queue-bundle version 6

tilleuls/migration-bundle/1.1/config/packages/coop_tilleuls_migration.yaml, tilleuls/migration-bundle/1.1/manifest.json
| Related issue | https://github.com/coopTilleuls/CoopTilleulsMigrationBundle/issues/9
=> Add tilleuls/migration-bundle

kerox/twig-image-placeholder-extension/1.0/config/packages/kerox_twig_image_placeholder.yaml, kerox/twig-image-placeholder-extension/1.0/manifest.json
=> Add kerox/twig-image-placeholder-extension

monsieurbiz/sylius-admin-better-login-plugin/1.0/manifest.json
=> Fix path in copy-from-package

artox-lab/sms-bundle/1.0/config/packages/artox_lab_sms.yaml, artox-lab/sms-bundle/1.0/manifest.json, artox-lab/sms-bundle/1.0/post-install.txt
=> Add recipe for artox-lab/sms-bundle

synolia/sylius-scheduler-command-plugin/1.0/config/packages/sylius_scheduler_command.yaml, synolia/sylius-scheduler-command-plugin/1.0/config/routes/sylius_scheduler_command.yaml, synolia/sylius-scheduler-command-plugin/1.0/manifest.json, synolia/sylius-scheduler-command-plugin/1.0/post-install.txt
=> add synolia/sylius-scheduler-command-plugin

synolia/sylius-mail-tester-plugin/1.0/config/routes/sylius_mail_tester.yaml, synolia/sylius-mail-tester-plugin/1.0/manifest.json
=> add synolia/sylius-mail-tester-plugin

tbmatuka/editorjs-bundle/0.1/config/packages/editorjs.yaml, tbmatuka/editorjs-bundle/0.1/manifest.json
=> Add recipe for tbmatuka/editorjs-bundle

monsieurbiz/sylius-rich-editor-plugin/1.0/config/packages/monsieurbiz_sylius_rich_editor_plugin.yaml, monsieurbiz/sylius-rich-editor-plugin/1.0/config/routes/monsieurbiz_sylius_rich_editor_plugin.yaml, monsieurbiz/sylius-rich-editor-plugin/1.0/manifest.json
See https://github.com/monsieurbiz/SyliusRichEditorPlugin.
=> Add first recipe for monsieurbiz/sylius-rich-editor-plugin

jacquesndl/mailer-bundle/1.0/config/packages/jacquesndl_mailer.yaml, jacquesndl/mailer-bundle/1.0/manifest.json, jacquesndl/mailer-bundle/1.0/post-install.txt
=> [jacquesndl/mailer-bundle] add recipe

xiidea/easy-audit/1.4/config/packages/xiidea_easy_audit.yaml, xiidea/easy-audit/2.0/config/packages/xiidea_easy_audit.yaml, xiidea/easy-audit/2.0/manifest.json
This PR will add update configuration for https://github.com/xiidea/EasyAuditBundle package
=> Remove deprecated configuration from easy-audit-bundle recipe

async-aws/async-aws-bundle/0.1/config/packages/async_aws.yaml
=> [AsyncAws Bundle] Use website documentation URL

baldinof/roadrunner-bundle/1.2/config/packages/baldinof_road_runner.yaml, baldinof/roadrunner-bundle/1.2/manifest.json, baldinof/roadrunner-bundle/1.2/post-install.txt
=> Add recipe for baldinof/roadrunner-bundle v1.2.0

monsieurbiz/sylius-alert-message-plugin/1.0/config/packages/monsieurbiz_sylius_alert_message_plugin.yaml, monsieurbiz/sylius-alert-message-plugin/1.0/config/routes/monsieurbiz_sylius_alert_message_plugin.yaml, monsieurbiz/sylius-alert-message-plugin/1.0/manifest.json
=> Recipe for monsieurbiz/sylius-alert-message-plugin

akondas/symfony-consul-bundle/0.1/config/packages/consul.yaml, akondas/symfony-consul-bundle/0.1/config/routes/consul.yaml, akondas/symfony-consul-bundle/0.1/manifest.json
=> Add recipe for symfony-consul-bundle

jacquesndl/mailer-bundle/1.0/manifest.json
=> [Jacquesndl/MailerBundle] [FIX] Remove useless key

moneyphp/money-bundle/0.1/config/packages/money.yaml, moneyphp/money-bundle/0.1/manifest.json
=> Adds reciepe for moneyphp/money-bundle

payplug/sylius-payplug-plugin/0.2/config/packages/sylius_payplug.yaml, payplug/sylius-payplug-plugin/0.2/manifest.json
=> added payplug/sylius-payplug-plugin

jane-php/json-schema/6.0/bin/jane-json-schema-generate, jane-php/json-schema/6.0/config/jane/json_schema.php, jane-php/json-schema/6.0/config/packages/jane.yaml, jane-php/json-schema/6.0/manifest.json, jane-php/json-schema/6.0/post-install.txt, jane-php/open-api-common/6.0/bin/jane-open-api-generate, jane-php/open-api-common/6.0/config/jane/open_api.php, jane-php/open-api-common/6.0/config/packages/jane.yaml, jane-php/open-api-common/6.0/manifest.json, jane-php/open-api-common/6.0/post-install.txt
=> Update recipes for Jane v6.0

jurry/amqp-symfony-bundle/1.0/config/packages/jurry_rabbitmq.yaml, jurry/amqp-symfony-bundle/1.0/manifest.json
| Description | RabbitMQ Symfony Bundle
=> Add recipe for Jurry RabbitMQ Symfony Bundle

scheb/2fa-bundle/5.0/config/packages/scheb_2fa.yaml, scheb/2fa-bundle/5.0/config/routes/scheb_2fa.yaml, scheb/2fa-bundle/5.0/manifest.json
Recipe for version 5.x of https://github.com/scheb/2fa-bundle
=> Add recipe for scheb/2fa-bundle

helios-ag/fm-elfinder-bundle/10.0/manifest.json
This allow install/update elfinder assets on install/update packages
=> Add elfinder:install to composer-scripts

liip/imagine-bundle/1.8/manifest.json
See correct example:
https://github.com/symfony/recipes/blob/master/symfony/framework-bundle/4.2/manifest.json#L25
=> Public directory can be changed in project

infifni/euplatesc-plugin/1.0/config/routes/infifni_sylius_euplatesc_plugin.yaml, infifni/euplatesc-plugin/1.0/manifest.json
=> Added infifni/euplatesc-plugin flex recipe for 1.0

tienvx/mbt-bundle/1.17/config/packages/tienvx_mbt.yaml, tienvx/mbt-bundle/1.17/manifest.json
=> Update tienvx/mbt-bundle to 1.17

willdurand/hateoas-bundle/1.4/config/packages/bazinga_hateoas.yaml, willdurand/hateoas-bundle/1.4/manifest.json, willdurand/hateoas-bundle/2.0/config/packages/bazinga_hateoas.yaml, willdurand/hateoas-bundle/2.0/manifest.json
=> Added config for willdurand/hateoas-bundle

tbbc/money-bundle/4.0/config/packages/tbbc_money.yaml, tbbc/money-bundle/4.0/manifest.json
After a discussion with the bundle collaborator [here](https://github.com/TheBigBrainsCompany/TbbcMoneyBundle/issues/122) I've decided to create this PR.
=> Add recipee for tbbc/money-bundle version 4.0

lag/adminbundle/1.0/config/packages/lag_admin.yaml, lag/adminbundle/1.0/manifest.json
Q | A
-- | --
License | MIT
Add the recipe for [lag/adminbundle](https://github.com/larriereguichet/AdminBundle)
=> Add recipe for lag/adminbundle

ecphp/cas-bundle/1.0/manifest.json
=> Add ecphp/cas-bundle package for Symfony ^4.4 only

ecphp/cas-bundle/2.0/manifest.json
=> Add ecphp/cas-bundle for Symfony ^5 only

ecphp/eu-login-bundle/2.0/manifest.json
=> Add ecphp/eu-login-bundle package for Symfony 5.

ecphp/eu-login-bundle/1.0/manifest.json
=> Add ecphp/eu-login-bundle package for Symfony 4.4.

ecphp/cas-bundle/1.0/manifest.json, ecphp/cas-bundle/2.0/manifest.json, ecphp/eu-login-bundle/1.0/manifest.json, ecphp/eu-login-bundle/2.0/manifest.json
=> Fix erroneous config directory of ecphp/* bundles.

gheb/docusign-bundle/5.0/config/routes/docusign.yaml
Fixes https://github.com/GregoireHebert/docusign-bundle/issues/93
=> Add missing routing from gheb/docusign-bundle

connectholland/uptime-robot-bundle/1.0/config/packages/connectholland_uptime_robot.yaml, connectholland/uptime-robot-bundle/1.0/manifest.json, connectholland/uptime-robot-bundle/1.0/post-install.txt
=> Add recipe for connectholland/uptime-robot-bundle

sonata-project/form-extensions/1.0/config/packages/sonata_form.yaml, sonata-project/form-extensions/1.0/manifest.json, sonata-project/form-extensions/1.4/config/packages/sonata_form.yaml, sonata-project/form-extensions/1.4/manifest.json
=> Add recipe for "sonata-project/form-extensions:1.0"

symfonycorp/connect/7.0/config/packages/symfony_connect.yaml, symfonycorp/connect/7.0/config/routes/symfony_connect.yaml, symfonycorp/connect/7.0/manifest.json
=> Add support for Symfony Connect

.travis.yml, async-aws/async-aws-bundle/1.0/config/packages/async_aws.yaml, async-aws/async-aws-bundle/1.0/manifest.json, happyr/json-api-response-factory/0.1/config/packages/happyr_json_api_response_factory.yaml
There are may people asking why travis is failing and if it is okey to merge the PR without support on 3.4. 
I thought I would make it easier for them.
=> Allow jobs to fail on SF 3.4.

swag-industries/melodiia/0.7/config/packages/melodiia.yaml, swag-industries/melodiia/0.7/manifest.json
=> Adding melodiia recipe

jsor/doctrine-postgis/1.7/config/packages/jsor_doctrine_postgis.yaml, jsor/doctrine-postgis/1.7/manifest.json
=> Add jsor/doctrine-postgis

sulu/form-bundle/2.0/config/packages/sulu_form.yaml, sulu/form-bundle/2.0/config/routes/sulu_form_admin.yaml, sulu/form-bundle/2.0/manifest.json, sulu/form-bundle/2.0/post-install.txt
Link to package: https://github.com/sulu/SuluFormBundle
=> Add flex recipe for SuluFormBundle

sulu/headless-bundle/0.1/config/routes/sulu_headless_website.yaml, sulu/headless-bundle/0.1/manifest.json, sulu/headless-bundle/0.1/post-install.txt
Link to package: https://github.com/sulu/SuluHeadlessBundle
=> Add flex recipe for SuluHeadlessBundle

jbtcd/fitbit-bundle/1.0/config/packages/fitbit.yaml, jbtcd/fitbit-bundle/1.0/manifest.json
=> Add jbtcd fitbitd-bundle recipe

sulu/article-bundle/2.0/config/packages/ongr_elasticsearch.yaml, sulu/article-bundle/2.0/config/packages/sulu_article.yaml, sulu/article-bundle/2.0/config/routes/sulu_article_admin.yaml, sulu/article-bundle/2.0/manifest.json, sulu/article-bundle/2.0/post-install.txt
Link to package: https://github.com/sulu/SuluArticleBundle
=> Add flex recipe for SuluArticleBundle

coka/pagination-bundle/5.0/config/packages/oka_pagination.yaml, coka/pagination-bundle/5.0/manifest.json
=> * Add a recipe for coka/pagination-bundle version 5.0.

klaviyo/php-sdk/2.0/config/packages/klaviyo.yaml, klaviyo/php-sdk/2.0/manifest.json
A pretty simple recipe that will simplify the package installation
=> Add Klaviyo SDK recipe

hboie/jasper-report-bundle/1.1/config/packages/jasper_report.yaml, hboie/jasper-report-bundle/1.1/manifest.json
=> add recipe for hboie/jasper-report-bundle

oat-sa/bundle-lti1p3/3.0/config/packages/lti1p3.yaml, oat-sa/bundle-lti1p3/3.0/config/routes/lti1p3.yaml, oat-sa/bundle-lti1p3/3.0/manifest.json, oat-sa/bundle-lti1p3/3.0/post-install.txt
- Updated for `oat-sa/bundle-lti1p3` version `3.0.0`
- Fixed defaut LTI configuration file
- Made post script output more readable by linking doc instead of listing commands
=> version 3.0

enhavo/app-bundle/0.9/assets/services/enhavo/enhavo_app.yaml, enhavo/app-bundle/0.9/assets/theme/base.js, enhavo/app-bundle/0.9/config/packages/enhavo_app.yaml, enhavo/app-bundle/0.9/config/routes/enhavo_app.yaml, enhavo/app-bundle/0.9/manifest.json, enhavo/app-bundle/0.9/post-install.txt, enhavo/app-bundle/0.9/tsconfig.json
Adding a recipe for the enhavo/app-bundle
=> Add enhavo/app-bundle recipe

ambient-link/ability-sdk/1.0/config/packages/ability.yaml, ambient-link/ability-sdk/1.0/manifest.json, ambient-link/ability-sdk/1.0/post-install.txt
Added ambient.link ability pack.
=> added ambient-link ability sdk

mobizel/markdown-docs-bundle/0.1/config/mobizel_markdown_docs.yaml, mobizel/markdown-docs-bundle/0.1/config/routes/mobizel_markdown_docs.yaml, mobizel/markdown-docs-bundle/0.1/docs/index.md, mobizel/markdown-docs-bundle/0.1/manifest.json
=> Add Mobizel Markdown docs bundle

knplabs/packagist-api/1.6/config/packages/knp_packagist_api.yaml, knplabs/packagist-api/1.6/manifest.json
=> Add knplabs/packagist-api

cpliakas/git-wrapper/3.0/config/packages/cpliakas_git_wrapper.yaml, cpliakas/git-wrapper/3.0/manifest.json
=> Add cpliakas/git-wrapper

monsieurbiz/sylius-sales-reports-plugin/1.0/config/packages/monsieurbiz_sylius_sales_reports_plugin.yaml, monsieurbiz/sylius-sales-reports-plugin/1.0/config/routes/monsieurbiz_sylius_sales_reports_plugin.yaml, monsieurbiz/sylius-sales-reports-plugin/1.0/manifest.json
=> feat: add monsieurbiz_sylius_sales_reports_plugin as recipe

stefandoorn/sitemap-plugin/1.0/config/packages/sitemap_plugin.yaml, stefandoorn/sitemap-plugin/1.0/config/routes/sitemap_plugin.yaml, stefandoorn/sitemap-plugin/1.0/manifest.json
=> feat: add sitemap plugin as recipe

php-translation/symfony-bundle/0.10/config/routes/dev/php_translation.yaml, php-translation/symfony-bundle/0.10/config/routes/php_translation.yaml, php-translation/symfony-bundle/0.4/config/routes/dev/php_translation.yaml, php-translation/symfony-bundle/0.4/config/routes/php_translation.yaml
=> Remove extra spaces from php-translation

cpliakas/git-wrapper/3.0/config/packages/cpliakas_git_wrapper.yaml
@OskarStark WDYT? This is what i was using before to wire the GitWrapper
edit: arg, requires monolog ... so only a recommendation as comment?
=> Adding logging capabilities to GitWrapper

holadev/amp-toolbox-bundle/0.1/config/packages/amp_toolbox.yaml, holadev/amp-toolbox-bundle/0.1/manifest.json
=> Add amp-toolbox-bundle recipe

timiki/rpc-server-bundle/4.2/config/packages/rpc_server.yaml, timiki/rpc-server-bundle/4.2/config/routes/rpc_server.yaml, timiki/rpc-server-bundle/4.2/manifest.json
Update  timiki/rpc-server-bundle recipes for 4.2
=> Add recipes for timiki/rpc-server-bundle >= 4.2

README.rst
See https://github.com/symfony/recipes-contrib/issues/1076#issuecomment-758502196
=> Removing outdated information on automatic merge process

tilleuls/url-signer-bundle/1.0/config/packages/url_signer.yaml, tilleuls/url-signer-bundle/1.0/manifest.json
Bundle can be found here: https://github.com/coopTilleuls/UrlSignerBundle
=> Add recipe for tilleuls/url-signer-bundle

nucleos/dompdf-bundle/3.1/config/packages/nucleos_dompdf.yaml, nucleos/dompdf-bundle/3.1/manifest.json
https://github.com/nucleos/NucleosDompdfBundle
=> Adding nucleos/NucleosDompdfBundle

sonata-project/admin-bundle/4.0/config/packages/sonata_admin.yaml, sonata-project/admin-bundle/4.0/config/routes/sonata_admin.yaml, sonata-project/admin-bundle/4.0/manifest.json, sonata-project/admin-bundle/4.0/src/Admin/.gitignore
Fixes https://github.com/sonata-project/SonataAdminBundle/issues/6808
=> add updated recipe for SonataAdminBundle 4.0

reconnect/s3bundle/0.1/config/packages/reconnect_s3_bundle.yaml, reconnect/s3bundle/0.1/manifest.json
=> Add recipe for S3Bundle

webinarium/symfony-lazysec/2.3/config/packages/lazysec.yaml, webinarium/symfony-lazysec/2.3/manifest.json
=> Changes for webinarium/symfony-lazysec 2.3+

datana-gmbh/intercom-config/1.1/config/packages/datana_intercom_config.yaml, datana-gmbh/intercom-config/1.1/manifest.json
=> Add datana-gmbh/intercom-config

tgalopin/html-sanitizer-bundle/1.0/config/packages/html_sanitizer.yaml
Add new 'details' extension, see https://github.com/tgalopin/html-sanitizer/blob/master/docs/1-getting-started.md#extensions
=> Update tgalopin/html-sanitizer-bundle recipe: Add new 'details' extension

README.rst
=> [Readme] Syntax updates

ecphp/api-gw-authentication-bundle/1.0/config/packages/dev/api_gw_authentication.yaml, ecphp/api-gw-authentication-bundle/1.0/config/routes/dev/api_gw_authentication.yaml, ecphp/api-gw-authentication-bundle/1.0/manifest.json
The bundle is for Symfony >= 5. See the repo: https://github.com/ecphp/api-gw-authentication-bundle
=> Add new recipe ecphp/api-gw-authentication-bundle

knojector/steam-authentication-bundle/1.0/config/packages/knojector_steam_authentication.yaml, knojector/steam-authentication-bundle/1.0/manifest.json
=> Updated recipe

oneup/flysystem-bundle/3.0/config/packages/oneup_flysystem.yaml, oneup/flysystem-bundle/4.0/config/packages/oneup_flysystem.yaml, oneup/flysystem-bundle/4.0/manifest.json
=> Add recipe for version 4.x

emag-tech-labs/annotation-cache-bundle/5.0/config/packages/emag_annotation_cache.yaml, emag-tech-labs/annotation-cache-bundle/5.0/manifest.json
=> Add recipe for Annotation Cache Bundle

systemsdk/easy-log-bundle/1.10/config/packages/dev/systemsdk_easy_log.yaml, systemsdk/easy-log-bundle/1.10/config/packages/test/systemsdk_easy_log.yaml, systemsdk/easy-log-bundle/1.10/manifest.json
=> added systemsdk/easy-log-bundle

oskarstark/symfony-http-responder/0.1/config/packages/oskarstark_symfony_http_responder.yaml, oskarstark/symfony-http-responder/0.1/manifest.json
For reference:
https://github.com/OskarStark/symfony-http-responder
=> Add oskarstark/symfony-http-responder

oskarstark/symfony-http-responder/0.1/config/packages/oskarstark_symfony_http_responder.yaml
=> Add missing autowire option

helppc/supervisor-bundle/1.0/config/packages/helppc_supervisor.yaml, helppc/supervisor-bundle/1.0/config/routes/helppc_supervisor.yaml, helppc/supervisor-bundle/1.0/manifest.json, helppc/supervisor-rest-bundle/1.0/config/packages/helppc_supervisor_rest.yaml, helppc/supervisor-rest-bundle/1.0/config/routes/helppc_supervisor_rest.yaml, helppc/supervisor-rest-bundle/1.0/manifest.json
=> Add recipe for helppc/supervisor-bundle

oskarstark/readable-filesize-extension/0.1/config/packages/oskarstark_readable_filesize_extension.yaml, oskarstark/readable-filesize-extension/0.1/manifest.json
=> Add: oskarstark/readable-filesize-extension

baldinof/roadrunner-bundle/2.0/config/packages/baldinof_road_runner.yaml, baldinof/roadrunner-bundle/2.0/manifest.json, baldinof/roadrunner-bundle/2.0/post-install.txt
=> Add recipe for baldinof/roadrunner-bundle v2.0

mtarld/api-platform-ms-bundle/0.1/config/packages/api_platform_ms.yaml, mtarld/api-platform-ms-bundle/0.1/manifest.json, mtarld/api-platform-ms-bundle/0.1/post-install.txt
=> Add ApiPlatformMsBundle recipe

velhron/dadata-bundle/1.0/config/packages/dadata.yaml, velhron/dadata-bundle/1.0/manifest.json, velhron/dadata-bundle/1.0/post-install.txt
https://github.com/Velhron/dadata-bundle
=> Add recipe for DadataBundle

oskarstark/no-floc-listener/0.1/config/packages/oskarstark_symfony_no_floc_listener.yaml, oskarstark/no-floc-listener/0.1/manifest.json
=> Add oskarstark/no-floc-listener

macpaw/sentry-monolog-adapter/0.0/config/packages/sentry_monolog_adapter.yaml, macpaw/sentry-monolog-adapter/0.0/manifest.json, macpaw/sentry-monolog-adapter/0.0/post-install.txt
=> add recipes macpaw/sentry-monolog-adapter

monsieurbiz/sylius-settings-plugin/1.0/config/packages/monsieurbiz_settings_plugin.yaml, monsieurbiz/sylius-settings-plugin/1.0/config/routes/monsieurbiz_settings_plugin.yaml, monsieurbiz/sylius-settings-plugin/1.0/manifest.json
https://github.com/monsieurbiz/SyliusSettingsPlugin
=> Add recipe for Sylius Settings Plugin by @monsieurbiz

monsieurbiz/sylius-coliship-plugin/0.1/config/packages/monsieurbiz_coliship_plugin.yaml, monsieurbiz/sylius-coliship-plugin/0.1/config/routes/monsieurbiz_coliship_plugin.yaml, monsieurbiz/sylius-coliship-plugin/0.1/manifest.json
https://github.com/monsieurbiz/SyliusColishipPlugin
=> Add recipe for Sylius Coliship Plugin by @monsieurbiz

monsieurbiz/sylius-no-commerce-plugin/0.1/config/packages/monsieurbiz_sylius_nocommerce_plugin.yaml, monsieurbiz/sylius-no-commerce-plugin/0.1/manifest.json
https://github.com/monsieurbiz/SyliusNoCommercePlugin
=> Add recipe for Sylius No Commerce by @monsieurbiz

macpaw/symfony-health-check-bundle/0.1/config/packages/symfony_health_check.yaml, macpaw/symfony-health-check-bundle/0.1/config/routes/symfony_health_check.yaml, macpaw/symfony-health-check-bundle/0.1/manifest.json, macpaw/symfony-health-check-bundle/0.1/post-install.txt
=> add new bundle SymfonyHealthCheckBundle

synolia/sylius-scheduler-command-plugin/2.0/config/packages/sylius_scheduler_command.yaml, synolia/sylius-scheduler-command-plugin/2.0/config/routes/sylius_scheduler_command.yaml, synolia/sylius-scheduler-command-plugin/2.0/manifest.json, synolia/sylius-scheduler-command-plugin/2.0/post-install.txt
=> update for Synolia SyliusSchedulerCommandPlugin v2

phpzlc/admin-business/1.0/manifest.json, phpzlc/admin/1.0/manifest.json, phpzlc/auth-business/1.0/manifest.json, phpzlc/captcha-business/1.0/manifest.json, phpzlc/platform-business/1.0/manifest.json, phpzlc/rbac-business/1.0/manifest.json, phpzlc/upload-business/1.0/manifest.json
=> add phpzlc multiple packages

ecphp/eu-login-api-authentication-bundle/1.0/config/packages/dev/eu_login_api_authentication.yaml, ecphp/eu-login-api-authentication-bundle/1.0/config/routes/dev/eu_login_api_authentication.yaml, ecphp/eu-login-api-authentication-bundle/1.0/manifest.json
=> Add basic recipe for eu-login-api-authentication-bundle.

isaac/gazesymfonybundle/0.1/config/packages/isaac_gaze_symfony.yaml, isaac/gazesymfonybundle/0.1/config/routes/isaac_gaze_symfony.yaml, isaac/gazesymfonybundle/0.1/manifest.json
=> Add GazeSymfonyBundle recipe

pond5/async-request-bundle/1.1/config/packages/pond5_async_request.yaml, pond5/async-request-bundle/1.1/manifest.json
Recipe for https://github.com/PondFive/AsyncRequestBundle
=> Add pond5/async-request-bundle recipe

loophp/psr17/1.0/config/packages/loophp_psr17.yaml, loophp/psr17/1.0/manifest.json
Link: https://github.com/loophp/psr17
=> Add recipe for loophp/psr17 package.

sylius/resource-bundle/1.6/config/packages/sylius_resource.yaml, sylius/resource-bundle/1.6/manifest.json
=> Add Sylius resource bundle

siganushka/generic-bundle/0.3/config/packages/siganushka_generic.yaml, siganushka/generic-bundle/0.3/manifest.json, siganushka/region-bundle/0.1/config/routes/siganushka_region.yaml, siganushka/region-bundle/0.1/manifest.json
=> add recipe for sgianushka/generic-bundle and sgianushka/region-bundle

friendsofsymfony/ckeditor-bundle/2.0/manifest.json
See https://github.com/FriendsOfSymfony/FOSCKEditorBundle/blob/2.x/docs/migration.rst#regenerate-assets
=> Added ckeditor:install to fetch ckeditor assets

bitbag/shipping-export-plugin/1.0/config/packages/bitbag_shipping_export_plugin.yaml, bitbag/shipping-export-plugin/1.0/config/routes/bitbag_shipping_export_plugin.yaml, bitbag/shipping-export-plugin/1.0/manifest.json, bitbag/shipping-export-plugin/1.0/post-install.txt
=> Add recipe for bitbag/shipping-export-plugin

jupi007/prestashop-webservice-bundle/1.0/config/packages/jupi007_presta_shop_webservice.yaml, jupi007/prestashop-webservice-bundle/1.0/config/packages/jupi007_prestashop_webservice.yaml, jupi007/prestashop-webservice-bundle/1.0/manifest.json
=> Add recipe for Jupi007 PS Webservice Bundle

jawira/case-converter-twig/0.0/config/packages/case_converter_twig.yaml, jawira/case-converter-twig/0.0/manifest.json
This recipe installs the filters provided by https://github.com/jawira/case-converter-twig
=> Add jawira/case-converter-twig

monsieurbiz/sylius-cms-page-plugin/1.0/config/packages/monsieurbiz_sylius_cms_page_plugin.yaml, monsieurbiz/sylius-cms-page-plugin/1.0/config/routes/monsieurbiz_sylius_cms_page_plugin.yaml, monsieurbiz/sylius-cms-page-plugin/1.0/manifest.json
=> Add monsieurbiz/sylius-cms-page-plugin 1.0

player259/graphql-bundle/1.0/config/routes/player259_graphql.yaml, player259/graphql-bundle/1.0/manifest.json
Add recipe for player259/graphql-bundle
=> Add recipe for player259/graphql-bundle

numberninecms/cms/0.2/config/routes/numbernine.yaml, numberninecms/cms/0.2/manifest.json, numberninecms/cms/0.2/post-install.txt
Recipe for [NumberNine CMS](https://github.com/numberninecms/cms)
=> Add recipe for NumberNine CMS 0.1

nbgrp/env-bundle/1.0/config/packages/nbgroup_env.yaml, nbgrp/env-bundle/1.0/manifest.json
=> Add nbgrp/env-bundle 1.0

monsieursloop/woleet-bundle/1.0/config/packages/monsieur_sloop_woleet.yaml, monsieursloop/woleet-bundle/1.0/manifest.json
Recipe for https://github.com/Monsieur-SLOOP/woleet-bundle
API for woleet.io blockchain service https://www.woleet.io/
=>  Symfony Flex Recipe for Woleet-Bundle

svc/contactform-bundle/1.0/assets/styles/layout/_svc-contactform.scss, svc/contactform-bundle/1.0/config/packages/svc_contactform.yaml, svc/contactform-bundle/1.0/config/routes/svc_contactform.yaml, svc/contactform-bundle/1.0/manifest.json, svc/contactform-bundle/1.0/post-install.txt, svc/param-bundle/1.0/config/routes/svc_param.yaml, svc/param-bundle/1.0/manifest.json, svc/param-bundle/1.0/post-install.txt, svc/util-bundle/1.0/config/packages/svc_util.yaml, svc/util-bundle/1.0/config/routes/svc_util.yaml, svc/util-bundle/1.0/manifest.json, svc/util-bundle/1.0/post-install.txt
Please merge this tree recipes. Thank you very much :-)
@Nyholm :
I closed the other pull request and opened a new, clean one. The error no longer occurs here.
The bundles are only for Symfony > 5.0, which is why the one test in the CI for Symfony 4 was not successful.
=> added svc-bundles to recipes-contrib

.github/PULL_REQUEST_TEMPLATE.md
This will make it easier when reviewing the package and we need to look at the source code
=> Add link to packagist in PR template

.github/workflows/create-project.yml
=> Show what commands we execute, not only output

scheb/2fa-bundle/5.0/config/packages/scheb_2fa.yaml, scheb/2fa-bundle/5.0/config/routes/scheb_2fa.yaml, scheb/2fa-bundle/5.0/manifest.json
Must be merged only when #986 is merged.
=> Move scheb/2fa-bundle to official recipes

datana-gmbh/sendgrid-dynamic-template-mailer/1.0/config/packages/datana_sendgrid_dynamic_template_mailer.yaml, datana-gmbh/sendgrid-dynamic-template-mailer/1.0/manifest.json
| Packagist     | https://packagist.org/packages/datana-gmbh/sendgrid-dynamic-template-mailer
=> Add datana-gmbh/sendgrid-dynamic-template-mailer

pentatrion/upload-bundle/0.2/config/packages/pentatrion_upload.yaml, pentatrion/upload-bundle/0.2/config/routes/pentatrion_upload.yaml, pentatrion/upload-bundle/0.2/manifest.json, pentatrion/upload-bundle/0.2/post-install.txt
<p>Hi,<br>
This Pull Request adds the recipe for the <a href="https://github.com/lhapaipai/upload-bundle">pentatrion/upload-bundle</a>.</p>
=> add recipe for pentatrion/upload-bundle

mixpanel/mixpanel-php/2.8/config/packages/mixpanel.yaml, mixpanel/mixpanel-php/2.8/manifest.json
| Packagist     | https://packagist.org/packages/mixpanel/mixpanel-php
=> Add recipe for mixpanel/mixpanel-php

dunglas/digital-ocean-bundle/1.0/config/dunglas_digital_ocean.yaml, dunglas/digital-ocean-bundle/1.0/manifest.json
| Packagist     | https://packagist.org/packages/dunglas/digital-ocean-bundle
=> add recipe for dunglas/digital-ocean-bundle

phpzlc/document-bundle/1.1/Document/Config.php
=> PHPZlc Update Config.php

datana-gmbh/datapool-api/1.0/config/packages/datana_datapool_api.yaml
=> Add new api

datana-gmbh/datapool-api/1.0/config/packages/datana_datapool_api.yaml
=> Remove trailing spaces

.github/workflows/flex-update-archived.yml
| Packagist     | Not needed
The recipes-contrib version of https://github.com/symfony/recipes/pull/1039
=> Adding a manual action to build the archived directory

enigma972/orange-sms-notifier/6.1/manifest.json
| Packagist | https://packagist.org/packages/enigma972/orange-sms-notifier
See [symfony/symfony:44913](https://github.com/symfony/symfony/pull/44913)
=> Create recipe for symfony/orange-sms-notifier

macpaw/symfony-health-check-bundle/1.0/config/packages/symfony_health_check.yaml, macpaw/symfony-health-check-bundle/1.0/config/routes/symfony_health_check.yaml, macpaw/symfony-health-check-bundle/1.0/manifest.json, macpaw/symfony-health-check-bundle/1.0/post-install.txt
| Packagist     | https://packagist.org/packages/macpaw/symfony-health-check-bundle
=> add new version bundle SymfonyHealthCheckBundle config

datana-gmbh/datapool-api/2.3/config/packages/datana_datapool_api.yaml, datana-gmbh/datapool-api/2.3/manifest.json
=> Enhancement: Add new API

php-translation/symfony-bundle/0.10/config/routes/dev/php_translation.yaml
| Packagist     | https://packagist.org/packages/php-translation/symfony-bundle
=> Make quotes consistent - use single quotes in both places

coka/input-handler-bundle/1.0/config/packages/oka_input_handler.yaml, coka/input-handler-bundle/1.0/manifest.json
=> Added recipes for coka/input-handler-bundle

byte-artist/menu-bundle/0.1/config/packages/menu.yaml, byte-artist/menu-bundle/0.1/manifest.json
=> add byte-artist/menu-bundle v.0.1

coka/service-discovery-bundle/1.0/config/packages/oka_service_discovery.yaml, coka/service-discovery-bundle/1.0/manifest.json
=> Added recipes for coka/service-discovery-bundle

nzo/url-encryptor-bundle/6.0/config/packages/nzo_encryptor.yaml, nzo/url-encryptor-bundle/6.0/manifest.json
| Packagist     | https://packagist.org/packages/nzo/url-encryptor-bundle
=> add nzo/url-encryptor-bundle

monofony/admin-meta/0.8/manifest.json, monofony/api-meta/0.8/manifest.json, monofony/core-meta/0.8/manifest.json, monofony/front-meta/0.8/manifest.json
| Packagist     | [admin-meta](https://packagist.org/packages/monofony/admin-meta), [api-meta](https://packagist.org/packages/monofony/api-meta), [core-meta](https://packagist.org/packages/monofony/core-meta), [front-meta](https://packagist.org/packages/monofony/front-meta)
=> Recipes for Monofony metapackages

mangati/zenvia-notifier/1.0/manifest.json
| Packagist     | https://packagist.org/packages/mangati/zenvia-notifier
Adding recipe for Mangati Zenvia Notifier v1.0 (SMS message).
Zenvia website: https://zenvia.com
Zenvia API: https://zenvia.github.io/zenvia-openapi-spec/v2/
=> Adding Mangati Zenvia Notifier recipe

networking/init-cms-bundle/4.4/config/packages/dev/networking_init_cms.yaml, networking/init-cms-bundle/4.4/config/packages/networking_init_cms.yaml, networking/init-cms-bundle/4.4/config/routes/networking_init_cms.yaml, networking/init-cms-bundle/4.4/manifest.json, networking/init-cms-bundle/4.4/post-install.txt, networking/init-cms-bundle/4.4/serializer/Entity.Page.yaml, networking/init-cms-bundle/4.4/src/Entity/Page.php, networking/init-cms-bundle/4.4/src/Entity/User.php
| Packagist     | https://packagist.org/packages/networking/init-cms-bundle
=> added 4.4 config file

bitbag/product-bundle-plugin/1.2/config/packages/bitbag_product_bundle_plugin.yaml, bitbag/product-bundle-plugin/1.2/config/routes/bitbag_product_bundle_plugin.yaml, bitbag/product-bundle-plugin/1.2/manifest.json, bitbag/product-bundle-plugin/1.2/post-install.txt
| Packagist     |  https://packagist.org/packages/bitbag/product-bundle-plugin)
=> add bitbag/product-bundle-plugin

bitbag/cms-plugin/3.0/config/packages/bitbag_cms_plugin.yaml, bitbag/cms-plugin/3.0/config/routes/bitbag_cms_plugin.yaml, bitbag/cms-plugin/3.0/manifest.json, bitbag/cms-plugin/3.0/post-install.txt
| Packagist     | https://packagist.org/packages/bitbag/cms-plugin
=> Bitbag cms plugin

bitbag/mailchimp-plugin/1.2/config/packages/mailchimp.yaml, bitbag/mailchimp-plugin/1.2/config/routes/bitbag_sylius_mailchimp_plugin.yaml, bitbag/mailchimp-plugin/1.2/manifest.json, bitbag/mailchimp-plugin/1.2/post-install.txt, bitbag/shipping-export-plugin/1.0/config/packages/bitbag_shipping_export_plugin.yaml
| Packagist     | https://packagist.org/packages/bitbag/mailchimp-plugin
=> BitBag Mailchimp plugin

leapt/froala-editor-bundle/1.0/config/packages/leapt_froala_editor.yaml, leapt/froala-editor-bundle/1.0/config/routes/leapt_froala_editor.yaml, leapt/froala-editor-bundle/1.0/manifest.json
| Packagist     | https://packagist.org/packages/leapt/froala-editor-bundle
=> Add Leapt FroalaEditor bundle

.github/workflows/create-project.yml, happyr/entity-exists-validation-constraint/1.0/config/packages/happyr_entity_exists_validator.yaml, happyr/entity-exists-validation-constraint/1.0/manifest.json
See https://github.com/Happyr/entity-exists-validation-constraint
=> Adding recipe for happyr/entity-exists-validation-constraint

phpzlc/snapshot-business/1.0/manifest.json
=> add phpzlc/snapshot-business

sulu/form-bundle/2.2/config/packages/sulu_form.yaml, sulu/form-bundle/2.2/config/routes/sulu_form_admin.yaml, sulu/form-bundle/2.2/manifest.json, sulu/form-bundle/2.2/post-install.txt
| Packagist     | https://packagist.org/packages/sulu/form-bundle
Add recipe update for SuluFormBundle 2.2.
=> Add recipe for SuluFormBundle 2.2

monsieurbiz/sylius-homepage-plugin/1.0/config/packages/monsieurbiz_sylius_homepage_plugin.yaml, monsieurbiz/sylius-homepage-plugin/1.0/config/routes/monsieurbiz_sylius_homepage_plugin.yaml, monsieurbiz/sylius-homepage-plugin/1.0/manifest.json
=> Add Sylius Homepage plugin

monsieurbiz/sylius-menu-plugin/1.0/config/packages/monsieurbiz_sylius_menu_plugin.yaml, monsieurbiz/sylius-menu-plugin/1.0/config/routes/monsieurbiz_sylius_menu_plugin.yaml, monsieurbiz/sylius-menu-plugin/1.0/manifest.json
=> Add Sylius Menu plugin recipe

monsieurbiz/sylius-advanced-option-plugin/1.0/config/packages/monsieurbiz_sylius_advanced_option_plugin.yaml, monsieurbiz/sylius-advanced-option-plugin/1.0/config/routes/monsieurbiz_sylius_advanced_option_plugin.yaml, monsieurbiz/sylius-advanced-option-plugin/1.0/manifest.json
=> Add Sylius advanced option plugin recipe

monsieurbiz/sylius-shipping-slot-plugin/1.0/config/packages/monsieurbiz_sylius_shipping_slot_plugin.yaml, monsieurbiz/sylius-shipping-slot-plugin/1.0/config/routes/monsieurbiz_sylius_shipping_slot_plugin.yaml, monsieurbiz/sylius-shipping-slot-plugin/1.0/manifest.json
=> Add Sylius shipping slot plugin

kunstmaan/cookie-bundle/6.0/config/routes/kunstmaan_cookie.yaml, kunstmaan/cookie-bundle/6.0/manifest.json
| Packagist     | https://packagist.org/packages/kunstmaan/cookie-bundle
=> kunstmaan/cookie-bundle: Add recipe to setup bundle routes

defixit/anonlytics-bundle/1.0/config/packages/anonlytics.yaml, defixit/anonlytics-bundle/1.0/manifest.json
| Packagist     | https://packagist.org/packages/defixit/anonlytics-bundle
=> Added recipes for defixit/anonlytics-bundle

league/flysystem-bundle/1.0/config/packages/flysystem.yaml, league/flysystem-bundle/1.0/manifest.json, league/flysystem-bundle/1.0/post-install.txt
See https://github.com/symfony/recipes/pull/1067
=> Remove league/flysystem-bundle as it is now an official recipe

datana-gmbh/zammad-api/1.0/config/packages/datana_zammad_api.yaml, datana-gmbh/zammad-api/1.0/manifest.json
| Packagist     | https://packagist.org/packages/datana-gmbh/zammad-api
=> Add datana-gmbh/zammad-api recipe

jane-php/json-schema/7.0/bin/jane-json-schema-generate, jane-php/json-schema/7.0/config/jane/json_schema.php, jane-php/json-schema/7.0/config/packages/jane.yaml, jane-php/json-schema/7.0/manifest.json, jane-php/json-schema/7.0/post-install.txt, jane-php/open-api-common/7.0/bin/jane-open-api-generate, jane-php/open-api-common/7.0/config/jane/open_api.php, jane-php/open-api-common/7.0/config/packages/jane.yaml, jane-php/open-api-common/7.0/manifest.json, jane-php/open-api-common/7.0/post-install.txt
See changes applied for new namespaces:
- https://github.com/janephp/janephp/commit/806687e995022604dccbdd5fc83d07649abf8d30
| Packagist     | https://packagist.org/packages/jane-php/open-api-common https://packagist.org/packages/jane-php/json-schema
=> Add Jane-php recipe for v7 releases

sonata-project/block-bundle/4.11/config/packages/sonata_block.yaml, sonata-project/block-bundle/4.11/manifest.json
| Packagist     | https://packagist.org/packages/sonata-project/block-bundle
New installs should avoid enabling http cache, as changed here: https://github.com/sonata-project/SonataBlockBundle/pull/1011
=> Add SonataBlockBundle recipe to avoid deprecations

datana-gmbh/logz-io-handler/1.0/config/packages/datana_logz_io_handler.yaml, datana-gmbh/logz-io-handler/1.0/manifest.json
| Packagist     | https://packagist.org/packages/datana-gmbh/logz-io-handler
=> Add `datana-gmbh/logz-io-handler`

datana-gmbh/logz-io-handler/1.0/config/packages/datana_logz_io_handler.yaml
| Packagist     |  https://packagist.org/packages/datana-gmbh/logz-io-handler
=> Fix: Use statement

loophp/repository-monadic-helper/1.0/config/packages/loophp_repository_monadic_helper.yaml, loophp/repository-monadic-helper/1.0/manifest.json
| Packagist     | https://packagist.org/packages/loophp/repository-monadic-helper
=> Add recipe for package `loophp/repository-monadic-helper`

datana-gmbh/logz-io-handler/1.0/config/packages/datana_logz_io_handler.yaml
| Packagist     |  https://packagist.org/packages/datana-gmbh/logz-io-handler
=> Fix: Autowiring

zenstruck/redis/0.1/config/packages/zenstruck_redis.yaml, zenstruck/redis/0.1/manifest.json
| Packagist     | https://packagist.org/packages/zenstruck/redis
=> add zenstruck/redis recipe

datana-gmbh/doctrine-datetime-milliseconds-type/1.0/config/packages/datana_doctrine_datetime_milliseconds_type.yaml, datana-gmbh/doctrine-datetime-milliseconds-type/1.0/manifest.json
| Packagist     | https://packagist.org/packages/datana-gmbh/doctrine-datetime-milliseconds-type
=> Add `datana-gmbh/doctrine-datetime-milliseconds-type`

datana-gmbh/doctrine-postgres-public-schema-listener/1.0/config/packages/datana_doctrine_postgres_public_schema_listener.yaml, datana-gmbh/doctrine-postgres-public-schema-listener/1.0/manifest.json
| Packagist     | https://packagist.org/packages/datana-gmbh/doctrine-postgres-public-schema-listener
=> Add `datana-gmbh/doctrine-postgres-public-schema-listener`

.github/workflows/flex-update.yml, README.rst
| Packagist     | none
Waiting on https://github.com/symfony/recipes/pull/1078
=> Adding RECIPES.md action

fpt/stripe-bundle/0.5/config/packages/stripe.yaml, fpt/stripe-bundle/0.5/config/routes/stripe.yaml, fpt/stripe-bundle/0.5/manifest.json
| Packagist     | fpt/stripe-bundle
=> Add Fpt/Stripe-Bundle

gesdinet/jwt-refresh-token-bundle/1.0/config/packages/gesdinet_jwt_refresh_token.yaml, gesdinet/jwt-refresh-token-bundle/1.0/config/routes/gesdinet_jwt_refresh_token.yaml, gesdinet/jwt-refresh-token-bundle/1.0/manifest.json, gesdinet/jwt-refresh-token-bundle/1.0/src/Entity/RefreshToken.php
| Packagist     | [`gesdinet/jwt-refresh-token-bundle`](https://packagist.org/packages/gesdinet/jwt-refresh-token-bundle)
Note: Similar to #1119, the Q&A build can't pass because the default config requires optional dependencies that can't be installed for testing here.
=> Add a recipe for gesdinet/jwt-refresh-token-bundle

survos/barcode-bundle/1.0/config/packages/survos_barcode.yaml, survos/barcode-bundle/1.0/manifest.json
| Packagist     | https://packagist.org/packages/survos/barcode-bundle
=> add recipe for barcode bundle

fsi/files/1.5/config/packages/fsi_files.yaml, fsi/files/1.5/manifest.json
| Packagist     | [fsi/files](https://packagist.org/packages/fsi/files)
=> Add recipe for fsi/files

ablaise/meteion-bundle/1.0/config/packages/meteion.yaml, ablaise/meteion-bundle/1.0/manifest.json
| Packagist     | [ablaise/meteion-bundle](https://packagist.org/packages/ablaise/meteion-bundle)
=> Add recipes for ablaise/meteion-bundle

request-tracing/request-tracing-bundle/0.1/manifest.json
| Packagist     | https://packagist.org/packages/request-tracing/request-tracing-bundle
=> request-tracing/request-tracing-bundle

sentry/sentry-symfony/3.0/config/packages/prod/sentry.yaml, sentry/sentry-symfony/3.0/config/packages/sentry.yaml, sentry/sentry-symfony/3.0/manifest.json
- added monolog example config to omit confusion
- made sentry config for prod env only
Should resolve #1115
=> made sentry config for prod only

sonata-project/media-bundle/4.0/config/packages/sonata_media.yaml, sonata-project/media-bundle/4.0/config/routes/sonata_media.yaml, sonata-project/media-bundle/4.0/manifest.json, sonata-project/media-bundle/4.0/public/upload/media/.gitignore
| Packagist     | https://packagist.org/packages/sonata-project/media-bundle
Closes https://github.com/sonata-project/SonataMediaBundle/issues/2305
=> Add recipe for sonata-project/media-bundle 4

ajardin/blizzard-sdk-bundle/1.0/config/packages/ajardin_blizzard_sdk_bundle.yaml, ajardin/blizzard-sdk-bundle/1.0/manifest.json
| License       | MIT |
| Packagist     | [Link to package on packagist](https://packagist.org/packages/ajardin/blizzard-sdk-bundle) |
=> Add recipe for ajardin/blizzard-sdk-bundle

sentry/sentry-symfony/4.0/config/packages/sentry.yaml
=> Fix indentation

stefandoorn/sitemap-plugin/2.0/config/packages/sitemap_plugin.yaml, stefandoorn/sitemap-plugin/2.0/config/routes/sitemap_plugin.yaml, stefandoorn/sitemap-plugin/2.0/manifest.json
| Packagist     | [](https://packagist.org/packages/stefandoorn/sitemap-plugin)
=> SitemapPlugin 2.0 for Sylius flex recipe update

pixelopen/cloudflare-turnstile-bundle/0.1/config/packages/pixel_open_cloudflare_turnstile.yaml, pixelopen/cloudflare-turnstile-bundle/0.1/manifest.json, pixelopen/cloudflare-turnstile-bundle/0.1/post-install.txt
| Packagist     | https://packagist.org/packages/pixelopen/cloudflare-turnstile-bundle
=> Add recipe for Cloudflare Turnstile bundle

macpaw/behat-nelmio-describer/1.0/config/packages/behat_nelmio_describer.yaml, macpaw/behat-nelmio-describer/1.0/manifest.json, macpaw/behat-nelmio-describer/1.0/post-install.txt
| Packagist     |  https://packagist.org/packages/macpaw/behat-nelmio-describer
=> add behat-nelmio-describer config

solvrtech/symfony-logbook/1.0/config/packages/logbook.yaml, solvrtech/symfony-logbook/1.0/manifest.json
| Packagist     | [solvrtech/symfony-logbook](https://packagist.org/packages/solvrtech/symfony-logbook)
=> Add recipes for solvrtech/symfony-logbook

codeception/codeception/2.3/post-install.txt
=> fix capitialization error

routmoute/routmoute-sirene-bundle/1.0/config/packages/routmoute_sirene.yaml, routmoute/routmoute-sirene-bundle/1.0/manifest.json
| Packagist     | [routmoute/routmoute-sirene-bundle](https://packagist.org/packages/routmoute/routmoute-sirene-bundle)
=> add routmoute/routmoute-sirene-bundle

ajgl/breakpoint-twig-extension/0.3/manifest.json
| Packagist     | [ajgl/breakpoint-twig-extension](https://packagist.org/packages/ajgl/breakpoint-twig-extension)
=> Add recipe for ajgl/breakpoint-twig-extension

coka/doctrine-encrypt-bundle/1.0/config/packages/oka_doctrine_encrypt.yaml, coka/doctrine-encrypt-bundle/1.0/manifest.json
=> Added recipes for coka/doctrine-encrypt-bundle

patchlevel/event-sourcing-bundle/2.0/config/packages/dev/patchlevel_event_sourcing.yaml, patchlevel/event-sourcing-bundle/2.0/config/packages/patchlevel_event_sourcing.yaml, patchlevel/event-sourcing-bundle/2.0/manifest.json
| Packagist     | [patchlevel/event-sourcing-bundle](https://packagist.org/packages/patchlevel/event-sourcing-bundle)
Updated the recipe for patchlevel event-sourcing 2.0
=> add patchlevel event-sourcing 2.0 receipe

stefandoorn/sitemap-plugin/2.0/config/packages/sitemap_plugin.yaml, stefandoorn/sitemap-plugin/2.0/config/routes/sitemap_plugin.yaml, stefandoorn/sitemap-plugin/2.0/manifest.json
Change to yaml extension following the rename of the file
https://github.com/stefandoorn/sitemap-plugin/commits/ed68afa53164b54337c471881acc10dbc7e65ec6/src/Resources/config/config.yml?browsing_rename_history=true&new_path=src/Resources/config/config.yaml&original_branch=master
| Packagist     | [stefandoorn/sitemap-plugin](https://packagist.org/packages/stefandoorn/sitemap-plugin)
=> Adding 2.0 recipe with correct config.yaml

emag-tech-labs/annotation-cache-bundle/6.0/config/packages/emag_annotation_cache.yaml, emag-tech-labs/annotation-cache-bundle/6.0/manifest.json
=> Add new recipe for Annotation Cache Bundle 6.*

longitude-one/meta-bundle/1.0/config/packages/meta.yaml, longitude-one/meta-bundle/1.0/manifest.json, longitude-one/meta-bundle/1.0/post-install.txt
| Packagist     | [https://packagist.org/packages/longitude-one/meta-bundle](https://packagist.org/packages/longitude-one/meta-bundle)
Creating a recipe for the longitude-one/meta-bundle , a free, small and open-source bundle to manage meta tag for a better reference of your application.
=> A contrib recipe for a bundle to manage meta tags.

league/oauth2-server-bundle/0.3/config/packages/league_oauth2_server.yaml, league/oauth2-server-bundle/0.3/config/routes/league_oauth2.yaml, league/oauth2-server-bundle/0.3/manifest.json, league/oauth2-server-bundle/0.3/post-install.txt
| Packagist     | https://packagist.org/packages/league/oauth2-server-bundle
=> Add recipes for league/oauth2-server-bundle

svc/versioning-bundle/1.0/config/packages/svc_versioning.yaml, svc/versioning-bundle/1.0/manifest.json, svc/versioning-bundle/1.0/post-install.txt
=> added recipe for SvcVersioningBundle

monsieurbiz/sylius-rich-editor-plugin/2.0/config/packages/monsieurbiz_sylius_rich_editor_plugin.yaml, monsieurbiz/sylius-rich-editor-plugin/2.0/config/routes/monsieurbiz_sylius_rich_editor_plugin.yaml, monsieurbiz/sylius-rich-editor-plugin/2.0/manifest.json
=> Add Sylius RichEditor v2 recipe

monsieurbiz/sylius-search-plugin/1.0/config/packages/monsieurbiz_sylius_search_plugin.yaml, monsieurbiz/sylius-search-plugin/1.0/config/routes/monsieurbiz_sylius_search_plugin.yaml, monsieurbiz/sylius-search-plugin/1.0/manifest.json
=> Add Sylius Search Plugin recipe

artyuum/request-dto-mapper-bundle/1.0/config/packages/artyum_request_dto_mapper.yaml, artyuum/request-dto-mapper-bundle/1.0/manifest.json
| Packagist     |  [Link](https://packagist.org/packages/artyuum/request-dto-mapper-bundle)
=> Added request-dto-mapper-bundle recipe

kunstmaan/admin-bundle/6.0/config/packages/kunstmaan_admin.yaml, kunstmaan/admin-bundle/6.0/config/routes/kunstmaan_admin.yaml, kunstmaan/admin-bundle/6.0/manifest.json
| Packagist     | https://packagist.org/packages/kunstmaan/admin-bundle
=> [Kunstmaan/AdminBundle] Remove deprecated config

vincentlanglet/twig-cs-fixer/0.6/manifest.json
| Packagist     | https://packagist.org/packages/vincentlanglet/twig-cs-fixer
=> Add recipe for vincentlanglet/twig-cs-fixer

coka/doctrine-encrypt-bundle/1.0/manifest.json
| Packagist     | https://packagist.org/packages/coka/doctrine-encrypt-bundle
=> Fixed secret generation

timiki/rpc-server-bundle/5.0/config/packages/rpc_server.yaml, timiki/rpc-server-bundle/5.0/config/routes/rpc_server.yaml, timiki/rpc-server-bundle/5.0/manifest.json
| Packagist     | https://packagist.org/packages/timiki/rpc-server-bundle
=> Add recipe for timiki/rpc-server-bundle:5.*

phpsword/sword-bundle/1.0/config/packages/sword.yaml, phpsword/sword-bundle/1.0/config/routes/sword.yaml, phpsword/sword-bundle/1.0/manifest.json, phpsword/sword-bundle/1.0/post-install.txt
| Packagist     | https://packagist.org/packages/phpsword/sword-bundle
Recipe for [phpsword/sword-bundle](https://github.com/phpsword/sword-bundle).
Replaces #1433
=> Add recipe for phpsword/sword-bundle

aziz403/ux-datatable/1.0/config/packages/datatable.yaml, aziz403/ux-datatable/1.0/manifest.json
| Packagist     | [link](https://packagist.org/packages/aziz403/ux-datatable)
=> add recpies for aziz403/ux-datatable

webylum/puppeteer-server-client-bundle/1.2/config/packages/webylum_puppeteer_server_client.yaml, webylum/puppeteer-server-client-bundle/1.2/manifest.json
| Packagist     | https://packagist.org/packages/webylum/puppeteer-server-client-bundle#v1.2
Recipe for [webylum/puppeteer-server-client-bundle](https://gitlab.com/webylum/puppeteer-server-client-bundle/-/tree/v1.2)
=> Add recipe for webylum/puppeteer-server-client-bundle 1.2

phpzlc/flex/2.0/manifest.json, phpzlc/flex/2.0/phpzlc-flex.yaml, phpzlc/phpzlc/2.5/manifest.json, phpzlc/upload-business/2.0/manifest.json
=> phpzlc 2.5

wemxo/dynamic-form-bundle/1.0/config/packages/dynamic_form.yaml, wemxo/dynamic-form-bundle/1.0/manifest.json
| Packagist     | https://packagist.org/packages/wemxo/dynamic-form-bundle
=> add wemxo/dynamic-form-bundle recipe

jrmgx/interactive-bundle/1.0/manifest.json
| Packagist     | https://packagist.org/packages/jrmgx/interactive-bundle
=> Add recipe for jrmgx/interactive-bundle

youritservices/mock-server-bundle/1.0/config/packages/mock_server.yaml, youritservices/mock-server-bundle/1.0/manifest.json
| Packagist     | https://packagist.org/packages/youritservices/mock-server-bundle
=> Feature/mock server bundle recipe 1.0

openai-php/symfony/0.3/manifest.json
| Packagist     | [openai-php/symfony](https://packagist.org/packages/openai-php/symfony)
=> Add openai-php/symfony bundle

meilisearch/search-bundle/0.10/config/packages/meilisearch.yaml, meilisearch/search-bundle/0.10/manifest.json, meilisearch/search-bundle/0.10/post-install.txt
| Packagist     | https://packagist.org/packages/meilisearch/search-bundle
=> Add recipe for meilisearch/search-bundle

sylius/resource-bundle/1.9/config/packages/sylius_resource.yaml, sylius/resource-bundle/1.9/config/routes/sylius_resource.yaml, sylius/resource-bundle/1.9/manifest.json
| Packagist     | https://packagist.org/packages/sylius/resource-bundle
=> [sylius/resource-bundle] Sylius routes with attributes and default mapping paths

yousign/zdd-message-bundle/0.1/config/zdd_message.yaml, yousign/zdd-message-bundle/0.1/manifest.json
| Packagist     | https://packagist.org/packages/yousign/zdd-message-bundle
=> add zdd message bundle

datana-gmbh/url-shortener-api/1.0/config/packages/datana_url_shortener_api.yaml, datana-gmbh/url-shortener-api/1.0/manifest.json
| Packagist     | https://packagist.org/packages/datana-gmbh/url-shortener-api
=> Add recipe for `datana-gmbh/url-shortener-api`

eniams/safe-migrations/0.1/config/safe_migrations.yaml, eniams/safe-migrations/0.1/manifest.json
| Packagist     | https://packagist.org/packages/eniams/safe-migrations
=> add safe-migrations bundle

eniams/safe-migrations/1.0/config/packages/safe_migrations.yaml, eniams/safe-migrations/1.0/manifest.json
| Packagist     | https://packagist.org/packages/eniams/safe-migrations
=> update package dir

shopware/app-bundle/1.0/config/packages/shopware_app.yaml, shopware/app-bundle/1.0/config/routes/shopware_app.yaml, shopware/app-bundle/1.0/manifest.json, shopware/app-bundle/1.0/src/Entity/Shop.php
| Packagist     |  https://packagist.org/packages/shopware/app-bundle
=> feat: add shopware app sdk

formatz/fz-hosting-symfony-bundle/1.0/config/packages/formatz_fz_hosting.yaml, formatz/fz-hosting-symfony-bundle/1.0/manifest.json, formatz/fz-hosting-symfony-bundle/1.0/post-install.txt
| Packagist     |  [https://packagist.org/packages/formatz/fz-hosting-symfony-bundle](https://packagist.org/packages/formatz/fz-hosting-symfony-bundle)
=> Add FZ Hosting Symfony Bundle Recipe

web-auth/webauthn-symfony-bundle/3.0/config/packages/webauthn.yaml, web-auth/webauthn-symfony-bundle/3.0/manifest.json
=> Typo fixed

baldinof/roadrunner-bundle/3.0/config/packages/baldinof_road_runner.yaml, baldinof/roadrunner-bundle/3.0/manifest.json, baldinof/roadrunner-bundle/3.0/post-install.txt
| Packagist     | https://packagist.org/packages/baldinof/roadrunner-bundle
=> Upgrade baldinof/roadrunner-bundle recipe for v3.0

datana-gmbh/url-shortener-api/1.0/config/packages/datana_url_shortener_api.yaml
| Packagist     | https://packagist.org/datana-gmbh/url-shortener-api
=> Add service

dunglas/solid-client-php/1.0/manifest.json
| Packagist     | https://packagist.org/packages/dunglas/solid-client-php
Finishes #1393.
=> [dunglas/solid-client-php]: add recipe

dama/doctrine-test-bundle/4.0/manifest.json
=> [dama/doctrine-test-bundle] Set warn_if_missing=true when trying to add lines to phpunit.xml.dist

phpstan/phpstan/1.0/manifest.json, phpstan/phpstan/1.0/phpstan.neon, phpstan/phpstan/1.0/post-install.txt
| Packagist     | https://packagist.org/packages/phpstan/phpstan
=> Add phpstan/phpstan recipe

monsieurbiz/sylius-order-history-plugin/1.0/config/packages/monsieurbiz_sylius_order_history_plugin.yaml, monsieurbiz/sylius-order-history-plugin/1.0/config/routes/monsieurbiz_sylius_order_history_plugin.yaml, monsieurbiz/sylius-order-history-plugin/1.0/manifest.json
| Packagist     |  https://packagist.org/packages/monsieurbiz/sylius-order-history-plugin
=> Add Sylius Order History plugin by M. Biz V1.0

luzrain/workerman-bundle/0.1/config/packages/workerman.yaml, luzrain/workerman-bundle/0.1/manifest.json
| Packagist     | https://packagist.org/packages/luzrain/workerman-bundle
=> Add recipe for luzrain/workerman-bundle

datana-gmbh/fake-api-client/1.0/config/packages/datana_fake_api.yaml, datana-gmbh/fake-api-client/1.0/manifest.json
| Packagist     | https://packagist.org/packages/datana-gmbh/fake-api-client
=> Add recipe for `datana-gmbh/fake-api-client`

datana-gmbh/fake-api-client/1.0/config/packages/datana_fake_api.yaml
| Packagist     | https://packagist.org/packages/datana-gmbh/fake-api-client
=> Remove `when@dev` and `when@test`

datana-gmbh/fake-api-client/2.0/config/packages/datana_fake_api.yaml, datana-gmbh/fake-api-client/2.0/manifest.json
| Packagist     | https://packagist.org/packages/datana-gmbh/fake-api-client
=> Add `datana-gmbh/fake-api-client` version `2`

survos/command-bundle/1.5/config/packages/survos_command.yaml, survos/command-bundle/1.5/config/routes/survos_command.php, survos/command-bundle/1.5/manifest.json, survos/command-bundle/1.5/post-install.txt
| Packagist     | https://packagist.org/packages/survos/command-bundle
=> add survos/command-bundle

survos/crawler-bundle/1.5/config/packages/survos_crawler.yaml, survos/crawler-bundle/1.5/config/routes/survos_crawler.php, survos/crawler-bundle/1.5/manifest.json, survos/crawler-bundle/1.5/post-install.txt
| Packagist     | https://packagist.org/packages/survos/crawler-bundle
=> add survos/crawler-bundle

sonata-project/entity-audit-bundle/1.1/config/routes/sonata_entity_audit.yaml, sonata-project/entity-audit-bundle/1.1/manifest.json
| Packagist     | https://packagist.org/packages/sonata-project/entity-audit-bundle
=> Add recipe for "sonata-project/entity-audit-bundle"

mongodb/symfony-bundle/0.1/config/packages/mongodb.yaml, mongodb/symfony-bundle/0.1/manifest.json
| Packagist     | https://packagist.org/packages/mongodb/symfony-bundle
cc @alcaeus
=> Add `mongodb/symfony-bundle`

tales-from-a-dev/twig-tailwind-extra/0.2/manifest.json
| Packagist     | [tales-from-a-dev/twig-tailwind-extra](https://packagist.org/packages/tales-from-a-dev/twig-tailwind-extra)
=> Add tales-from-a-dev/twig-tailwind-extra

gponty/symfony-monday-api-bundle/1.0/config/packages/monday.yaml, gponty/symfony-monday-api-bundle/1.0/manifest.json
| Packagist     | https://packagist.org/packages/gponty/symfony-monday-api-bundle
=> Remove API Version

datana-gmbh/logz-io-handler/1.7/config/packages/datana_logz_io_handler.yaml, datana-gmbh/logz-io-handler/1.7/manifest.json
| Packagist     | https://packagist.org/packages/datana-gmbh/logz-io-handler
We now need to pass an enum for `$host`
=> Update recipe for `datana-gmbh/logz-io-handler`

datana-gmbh/iusta-api/3.0/config/packages/datana_iusta_api.yaml, datana-gmbh/iusta-api/3.0/manifest.json
| Packagist     | https://packagist.org/packages/datana-gmbh/iusta-api
=> Upgrade recipe

tales-from-a-dev/flowbite-bundle/0.4/manifest.json
| Packagist     | [tales-from-a-dev/flowbite-bundle](https://packagist.org/packages/tales-from-a-dev/flowbite-bundle)
=> Add recipe for FlowbiteBundle

conejerock/idempotency-bundle/1.0/config/packages/idempotency.yaml, conejerock/idempotency-bundle/1.0/manifest.json
| Packagist     | [Idempotency Bundle](https://packagist.org/packages/conejerock/idempotency-bundle)
=> Add Idempotency Bundle

leapt/im-bundle/5.0/config/packages/leapt_im.yaml, leapt/im-bundle/5.0/config/routes/leapt_im.yaml, leapt/im-bundle/5.0/manifest.json
| Packagist     | https://packagist.org/packages/leapt/im-bundle
=> Add leapt/im-bundle v5 config

otezvikentiy/json-rpc-api/1.7/config/packages/ov_json_rpc_api.yaml, otezvikentiy/json-rpc-api/1.7/config/routes/ov_json_rpc_api.yaml, otezvikentiy/json-rpc-api/1.7/manifest.json
=> Json rpc api v1.7

wedrix/watchtower-bundle/2.0/config/packages/wedrix_watchtower_bundle.yaml, wedrix/watchtower-bundle/2.0/config/routes/wedrix_watchtower_bundle_routes.yaml, wedrix/watchtower-bundle/2.0/manifest.json
| Packagist     | https://packagist.org/packages/wedrix/watchtower-bundle
=> Added recipe for wedrix/watchtower-bundle v2

21torr/hosting/2.1/config/packages/hosting.yaml, 21torr/hosting/2.1/manifest.json
| Packagist     | https://packagist.org/packages/21torr/hosting
Here are the definitions for `21torr/hosting`.
=> Add 21torr/hosting bundle

datana-gmbh/logz-io-handler/1.7/config/packages/datana_logz_io_handler.yaml
| Packagist     | https://packagist.org/packages/datana-gmbh/logz-io-handler
=> Only in `prod`

datana-gmbh/iusta-api/3.8/config/packages/datana_iusta_api.yaml, datana-gmbh/iusta-api/3.8/manifest.json
=> Add DatasetApi

datana-gmbh/zendesk-api/1.0/config/packages/datana_zendesk_api.yaml, datana-gmbh/zendesk-api/1.0/manifest.json
| Packagist     | https://packagist.org/packages/datana-gmbh/zendesk-api
=> Adds recipe for `datana-gmbh/zendesk-api`

datana-gmbh/zendesk-api/1.0/config/packages/datana_zendesk_api.yaml
| Packagist     | https://packagist.org/packages/datana-gmbh/zendesk-api
=> Fix namespace

codeception/codeception/5.0/codeception.yml, codeception/codeception/5.0/manifest.json, codeception/codeception/5.0/post-install.txt, codeception/codeception/5.0/tests/Acceptance.suite.yml, codeception/codeception/5.0/tests/Functional.suite.yml, codeception/codeception/5.0/tests/Support/AcceptanceTester.php, codeception/codeception/5.0/tests/Support/FunctionalTester.php, codeception/codeception/5.0/tests/Support/UnitTester.php, codeception/codeception/5.0/tests/Support/_generated/.gitignore, codeception/codeception/5.0/tests/Unit.suite.yml, codeception/codeception/5.0/tests/_output/.gitignore
| Packagist     | [codeception/codeception](https://packagist.org/packages/codeception/codeception)
=> Codeception 5 update

hwi/oauth-bundle/2.0/config/packages/hwi_oauth.yaml, hwi/oauth-bundle/2.0/config/routes/hwi_oauth_routing.yaml, hwi/oauth-bundle/2.0/manifest.json, hwi/oauth-bundle/2.0/post-install.txt
| Packagist     | https://packagist.org/packages/hwi/oauth-bundle
Fixes https://github.com/hwi/HWIOAuthBundle/issues/1919
=> Adjust HWIOAuthBundle recipe for version 2.x

luzrain/phprunner-bundle/0.1/config/packages/phprunner.yaml, luzrain/phprunner-bundle/0.1/manifest.json
| Packagist     | https://packagist.org/packages/luzrain/phprunner-bundle
=> Add recipe for luzrain/phprunner-bundle

odolbeau/phone-number-bundle/3.0/post-install.txt
| Packagist     | [odolbeau/phone-number-bundle](https://packagist.org/packages/odolbeau/phone-number-bundle)
=> Adjust PhoneNumberBundle recipe to use attributes

iq2i/storia-bundle/0.1/config/packages/iq2i_storia.yaml, iq2i/storia-bundle/0.1/config/routes/iq2i_storia.yaml, iq2i/storia-bundle/0.1/manifest.json
| Packagist     | https://packagist.org/packages/iq2i/storia-bundle
=> [iq2i/storia-bundle]: add recipe

corytech/php-monitoring/1.0/manifest.json
| Packagist     | [https://packagist.org/packages/corytech/php-monitoring](https://packagist.org/packages/corytech/php-monitoring)
=> add corytech/php-monitoring reciepe

luzrain/phpstreamserver-bundle/0.2/config/packages/phpstreamserver.yaml, luzrain/phpstreamserver-bundle/0.2/manifest.json
| Packagist     | https://packagist.org/packages/luzrain/phpstreamserver-bundle
=> Add recipe for luzrain/phpstreamserver-bundle

patchlevel/event-sourcing-bundle/3.0/config/packages/patchlevel_event_sourcing.yaml, patchlevel/event-sourcing-bundle/3.0/manifest.json, patchlevel/event-sourcing-bundle/3.0/post-install.txt
| Packagist     | https://packagist.org/packages/patchlevel/event-sourcing
A new release for patchlevel/event sourcing has been published.
=> add patchlevel/event-sourcing 3.0

tiime/tested-routes-checker-bundle/1.0/manifest.json
| Packagist     | https://packagist.org/packages/tiime/tested-routes-checker-bundle
=> Add tiime/tested-routes-checker-bundle

softavis/flysystem-cloudflare-bundle/0.1/manifest.json
| Packagist     | [softavis/flysystem-cloudflare-bundle](https://packagist.org/packages/softavis/flysystem-cloudflare-bundle)
=> Add softavis/flysystem-cloudflare-bundle recipe fix version

sensiolabs-de/storyblok-api/1.0/config/packages/sensiolabs_de_storyblok_api.yaml
=> Add API class

sensiolabs-de/storyblok-api/2.0/config/packages/sensiolabs_de_storyblok_api.yaml, sensiolabs-de/storyblok-api/2.0/manifest.json
| Packagist     | https://packagist.org/packages/sensiolabs-de/storyblok-api
=>  `sensiolabs-de/storyblok-api` v2

bitbag/product-bundle-plugin/1.2/config/routes/bitbag_product_bundle_plugin.yaml
| Packagist     | https://packagist.org/packages/bitbag/product-bundle-plugin
=> Remove prefix from Product Bundle configuration

kocal/biome-js-bundle/1.0/config/packages/kocal_biome_js.yaml
Following #1617, the bundle should only enabled in dev mode.
=> [KocalBiomeJsBundle] Configure the bundle only for dev

softspring/cms-bundle/5.2/config/packages/sfs_admin_menu_cms.yaml, softspring/cms-bundle/5.2/config/packages/sfs_cms.yaml, softspring/cms-bundle/5.2/config/routes/sfs_cms_admin.yaml, softspring/cms-bundle/5.2/manifest.json, softspring/cms-bundle/5.2/post-install.txt, softspring/cms-bundle/5.2/translations/sfs_components.en.yaml
| Packagist     | https://packagist.org/packages/softspring/cms-bundle
=> Add softspring cms-bundle

softspring/cms-module-collection/5.2/config/packages/sfs_cms_modules.yaml, softspring/cms-module-collection/5.2/manifest.json
| Packagist     | https://packagist.org/packages/softspring/cms-module-collection
=> Add softspring cms-module-collection

softspring/media-bundle/5.2/config/packages/sfs_media.yaml, softspring/media-bundle/5.2/manifest.json, softspring/media-bundle/5.2/post-install.txt
| Packagist     | https://packagist.org/packages/softspring/media-bundle
=> Add softspring media-bundle

softspring/permissions-bundle/5.2/manifest.json, softspring/permissions-bundle/5.2/post-install.txt
| Packagist     | https://packagist.org/packages/softspring/permissions-bundle
=> Add softspring permissions-bundle

softspring/twig-extra-bundle/5.2/manifest.json, softspring/twig-extra-bundle/5.2/post-install.txt
| Packagist     | https://packagist.org/packages/softspring/twig-extra-bundle
=> Add softspring twig-extra-bundle

huluti/doctrine-relations-analyser/0.3/manifest.json
| Packagist     | https://packagist.org/packages/huluti/doctrine-relations-analyser
=> Create manifest.json for huluti/doctrine-relations-analyser

bitbag/wishlist-plugin/4.4/config/packages/bitbag_wishlist_plugin.yaml, bitbag/wishlist-plugin/4.4/config/routes/bitbag_wishlist_plugin.yaml, bitbag/wishlist-plugin/4.4/manifest.json, bitbag/wishlist-plugin/4.4/post-install.txt
| Packagist     | https://packagist.org/packages/bitbag/wishlist-plugin
=> Add recipe for bitbag/wishlist-plugin

swag-industries/doctrine-domain-events/3.1/config/packages/doctrine_domain_event.yaml, swag-industries/doctrine-domain-events/3.1/manifest.json
| Packagist     | https://packagist.org/packages/swag-industries/doctrine-domain-events
=> Add some sample of configuration for the new version of the bundle swagind/domain

zim32/symfony-tracing-http-client/1.0/config/packages/tracing_http_client.yaml, zim32/symfony-tracing-http-client/1.0/manifest.json
| Packagist     | https://packagist.org/packages/zim32/symfony-tracing-http-client
=> Add recipe for zim32/symfony-tracing-http-client package

mezcalito/ux-filemanager/0.1/manifest.json
| Packagist     | https://packagist.org/packages/mezcalito/ux-filemanager
=> [mezcalito/ux-filemanager]: add recipe

intervention/image-symfony/1.0/config/packages/intervention_image.yaml, intervention/image-symfony/1.0/manifest.json
| Packagist     | [](https://packagist.org/packages/intervention/image-symfony)
=> Add recipe for intervention/image-symfony

dahromy/mvola-bundle/1.0/config/packages/mvola.yaml, dahromy/mvola-bundle/1.0/config/routes/mvola.yaml, dahromy/mvola-bundle/1.0/manifest.json
| Packagist     | https://packagist.org/packages/dahromy/mvola-bundle
=> Add MVola bundle configuration, manifest, and routes

sensiolabs-de/storyblok-bundle/1.0/config/packages/storyblok.yaml, sensiolabs-de/storyblok-bundle/1.0/manifest.json
| Packagist     | https://packagist.org/packages/sensiolabs-de/storyblok-bundle
=> Enhancement: Adds Recipe for `sensiolabs-de/storyblok-bundle`

manojx/encrypter-bundle/1.0/config/packages/encrypter.yaml, manojx/encrypter-bundle/1.0/manifest.json
| Packagist     | https://packagist.org/packages/manojx/encrypter-bundle
=> Add Encrypter Bundle recipes

ecphp/eu-login-bundle/3.0/config/packages/dev/cas_bundle.yaml, ecphp/eu-login-bundle/3.0/config/packages/dev/eulogin_cas_security.yaml, ecphp/eu-login-bundle/3.0/manifest.json
| Packagist     | https://packagist.org/packages/ecphp/eu-login-bundle
=> ecphp/eu-login-bundle: add recipe for version 3.0

odolbeau/phone-number-bundle/3.0/config/packages/misd_phone_number.yaml
| Packagist     | https://github.com/odolbeau/phone-number-bundle
I added soe more example configuration so the user can see what to set or not.
=> [odolbeau/phone-number-bundle] add more example configuration

sensiolabs-de/storyblok-bundle/0.3/config/packages/storyblok.yaml, sensiolabs-de/storyblok-bundle/0.3/config/routes/storyblok.yaml, sensiolabs-de/storyblok-bundle/0.3/manifest.json
| Packagist     | https://packagist.org/packages/sensiolabs-de/storyblok-bundle
Follows
* https://github.com/sensiolabs-de/storyblok-bundle/pull/10
=> `sensiolabs-de/storyblok-bundle` 0.3

sensiolabs-de/storyblok-bundle/0.3/config/packages/storyblok.yaml, sensiolabs-de/storyblok-bundle/0.3/manifest.json
| Packagist     | https://packagist.org/packages/sensiolabs-de/storyblok-bundle
=> Fix: hints

sensiolabs/minify-bundle/0.9/config/packages/sensiolabs_minify.yaml, sensiolabs/minify-bundle/0.9/manifest.json
| Packagist     | https://packagist.org/packages/sensiolabs/minify-bundle
First recipe for the [SensioLabs Minify Bundle](https://github.com/sensiolabs/minify-bundle/)
=> Add sensiolabs/minify-bundle recipe

21torr/hosting/3.2/config/packages/hosting.yaml, 21torr/hosting/3.2/config/routes/hosting.yaml, 21torr/hosting/3.2/manifest.json
| Packagist     | https://packagist.org/packages/21torr/hosting
Update config for version 3.2+ of the package.
=> Add 21torr/hosting recipe for 3.2+

21torr/storyblok/3.0/config/packages/storyblok.yaml, 21torr/storyblok/3.0/manifest.json
| Packagist     | https://packagist.org/packages/21torr/storyblok
For v3 it's only env vars and the config file.
=> Add 21torr/storyblok 

rossel/mwu-sdk/0.1/config/packages/mwu_sdk.yaml, rossel/mwu-sdk/0.1/manifest.json
| Packagist     | https://packagist.org/packages/rossel/mwu-sdk
=> Add rossel/mwu-sdk

sofascore/purgatory-bundle/1.0/config/packages/purgatory.yaml, sofascore/purgatory-bundle/1.0/manifest.json, sofascore/purgatory-bundle/1.0/post-install.txt
| Packagist     | https://packagist.org/packages/sofascore/purgatory-bundle
=> Add Sofascore Purgatory Bundle

artack/svg-inline-bundle/1.0/config/packages/artack_svg_inline.yaml, artack/svg-inline-bundle/1.0/manifest.json
| Packagist     | https://packagist.org/packages/artack/svg-inline-bundle
=> Add artack/svg-inline-bundle

otezvikentiy/json-rpc-api/1.7/config/packages/ov_json_rpc_api.yaml
=> v1.12 patch

survos/command-bundle/1.5/post-install.txt
| Packagist     | [](https://packagist.org/packages/survos/command-bundle)
tweak the post-install.txt instructions.
=> Survos command2

doctrine/mongodb-odm-bundle/4.4/manifest.json, doctrine/mongodb-odm-bundle/5.0/manifest.json
| Packagist     | https://packagist.org/packages/doctrine/mongodb-odm-bundle
Configuration inspired by [`doctrine/doctrine-bundle`](https://github.com/symfony/recipes/blob/main/doctrine/doctrine-bundle/2.9/manifest.json).
=> Add MongoDB extension and service to Docker

bizkit/versioning-bundle/1.0/config/packages/bizkit_versioning.yaml, bizkit/versioning-bundle/1.0/manifest.json, bizkit/versioning-bundle/1.0/post-install.txt
| Packagist     | https://packagist.org/packages/bizkit/versioning-bundle
=> Add Bizkit Versioning Bundle

survos/command-bundle/1.5/post-install.txt
=> fix call to open file

sylius/invoicing-plugin/1.0/config/packages/sylius_invoicing.yaml, sylius/invoicing-plugin/1.0/config/routes/sylius_invoicing.yaml, sylius/invoicing-plugin/1.0/manifest.json, sylius/paypal-plugin/2.0/config/packages/sylius_paypal.yaml, sylius/paypal-plugin/2.0/config/routes/sylius_paypal.yaml, sylius/paypal-plugin/2.0/manifest.json, sylius/refund-plugin/0.4/config/packages/sylius_refund.yaml, sylius/refund-plugin/0.4/config/routes/sylius_refund.yaml, sylius/refund-plugin/0.4/manifest.json, sylius/refund-plugin/2.0/config/packages/sylius_refund.yaml, sylius/refund-plugin/2.0/config/routes/sylius_refund.yaml, sylius/refund-plugin/2.0/manifest.json
It includes new recipes for:
- Invoicing Plugin 1.0
- Refund Plugin 2.0
- PayPal Plugin 2.0
=> Add New Sylius Recipes

inspector-apm/inspector-symfony/1.3/config/packages/inspector.yaml
| Packagist     | https://packagist.org/packages/inspector-apm/inspector-symfony
=> Update Inspector.dev ignored routes and commands

commerce-weavers/sylius-tpay-plugin/2.0/config/packages/commerce_weavers_tpay_plugin.yaml, commerce-weavers/sylius-tpay-plugin/2.0/config/routes/commerce_weavers_tpay_plugin.yaml, commerce-weavers/sylius-tpay-plugin/2.0/manifest.json, commerce-weavers/sylius-tpay-plugin/2.0/post-install.txt
| Packagist     | https://packagist.org/packages/commerce-weavers/sylius-tpay-plugin
=> Add the Commerce Weavers Tpay plugin recipe

talleu/php-redis-om/0.3/manifest.json
| Packagist     | https://packagist.org/packages/talleu/php-redis-om
=> [talleu/php-redis-om]: add recipe

talleu/php-redis-om/0.3/manifest.json
| Packagist     | https://packagist.org/packages/talleu/php-redis-om
=> Fix php redis om bundle name

boshurik/telegram-bot-bundle/3.1/config/routes/boshurik_telegram_bot.yaml, boshurik/telegram-bot-bundle/6.0/config/packages/boshurik_telegram_bot.yaml, boshurik/telegram-bot-bundle/6.0/config/routes/boshurik_telegram_bot.yaml, boshurik/telegram-bot-bundle/6.0/manifest.json, boshurik/telegram-bot-bundle/6.0/post-install.txt
| Packagist     | [boshurik/telegram-bot-bundle](https://packagist.org/packages/boshurik/telegram-bot-bundle)
yml file was deleted in [this commit](https://github.com/BoShurik/TelegramBotBundle/commit/e5f16a8be354a6689081333e0faaa4ea7129d9e9#diff-bea85dabca61a35bc31e4ed5664459656d1db5912749510152e2e40690dbfb0b), it generates bad config since then
@BoShurik
=> Fix boshurik/telegram-bot-bundle

sensiolabs/gotenberg-bundle/0.1/manifest.json
Linked issue :   https://github.com/sensiolabs/GotenbergBundle/issues/131
=> [Sensiolabs][Gotenberg Bundle] Fix : update GOTENBERG_DSN value to match docker service name

survos/crawler-bundle/1.5/config/routes/survos_crawler.php, survos/crawler-bundle/1.5/config/routes/survos_crawler.yaml
| Packagist     | https://packagist.org/packages/survos/crawler-bundle
Use yaml instead of PHP for bundle configuration
=> use yaml instead of php for config

storyblok/symfony-bundle/0.1/config/packages/storyblok.yaml, storyblok/symfony-bundle/0.1/config/routes/storyblok.yaml, storyblok/symfony-bundle/0.1/manifest.json
| Packagist     | https://packagist.org/packages/storyblok/symfony-bundle
=> Enhancement: Adds Recipe for `storyblok/symfony-bundle`

mezcalito/ux-search/0.1/config/packages/mezcalito_ux_search.yaml, mezcalito/ux-search/0.1/manifest.json
| Packagist     | https://packagist.org/packages/mezcalito/ux-search
=> [mezcalito/ux-search]: add recipe

sylius/paypal-plugin/1.7/manifest.json
=> Add new recipe for `sylius/paypal-plugin:1.7`

magenable/sylius-top-bar-notification-plugin/1.0/config/packages/magenable_top_bar_notification.yaml, magenable/sylius-top-bar-notification-plugin/1.0/config/routes/magenable_top_bar_notification.yaml, magenable/sylius-top-bar-notification-plugin/1.0/manifest.json
| Packagist     | https://packagist.org/packages/magenable/sylius-top-bar-notification-plugin
=> Add recipe for magenable/sylius-top-bar-notification-plugin

thedevopser/castor-symfony/1.0/config/packages/castor.yaml, thedevopser/castor-symfony/1.0/manifest.json, thedevopser/castor-symfony/1.0/post-install.txt
| Packagist     | https://packagist.org/packages/thedevopser/castor-symfony
[TheDevOpser/Castor-Symfony] - Add recipe
Add a recipe to copy config files and add a post install message.
=> [receipe] - create based structure to Castor Symfony receipe

agilelab-fr/captcha-bundle/1.0/config/packages/agilelab_fr_captcha.yaml, agilelab-fr/captcha-bundle/1.0/config/routes/agilelab_fr_captcha.yaml, agilelab-fr/captcha-bundle/1.0/manifest.json
| Packagist     | [https://packagist.org/packages/agilelab-fr/captcha-bundle](https://packagist.org/packages/agilelab-fr/captcha-bundle)
=> AgilelabFr CAPTCHA Bundle

php-llm/llm-chain-bundle/0.16/config/packages/llm_chain.yaml, php-llm/llm-chain-bundle/0.16/manifest.json
| Packagist     | https://packagist.org/packages/php-llm/llm-chain-bundle
cc @chr-hertel
=> Add `php-llm/llm-chain-bundle`

stogon/unleash-bundle/0.4/config/packages/unleash.yaml, stogon/unleash-bundle/0.4/manifest.json
| Packagist     | https://packagist.org/packages/stogon/unleash-bundle
As suggested at https://github.com/Stogon/unleash-bundle/issues/4
=> Add recipe for stogon/unleash-bundle

synolia/sylius-mail-tester-plugin/3.0/config/routes/sylius_mail_tester.yaml, synolia/sylius-mail-tester-plugin/3.0/manifest.json
| Packagist     | https://packagist.org/packages/synolia/sylius-mail-tester-plugin
=> add recipe for synolia/sylius-mail-tester-plugin@v3

kocal/biome-js-bundle/1.1/config/packages/kocal_biome_js.yaml
| Packagist     | https://packagist.org/packages/kocal/biome-js-bundle
I should have done this at the very first, but it's the same than https://github.com/symfony/recipes/pull/1383
=> [KocalBiomeJsBundle] Pin explicit version

rossel/rossel-kafka-php-kit/0.0/config/packages/rossel_kafka.yaml, rossel/rossel-kafka-php-kit/0.0/manifest.json
| Packagist     | https://packagist.org/packages/rossel/rossel-kafka-php-kit
=> [FEAT] Add Rossel Kafka bundle

rossel/rossel-kafka/0.0/config/packages/rossel_kafka.yaml, rossel/rossel-kafka/0.0/manifest.json
| Packagist     | https://packagist.org/packages/rossel/rossel-kafka
=> [FIX] Rename `rossel/rossel-kafka bundle`

sylius/mollie-plugin/1.0/config/packages/sylius_mollie.yaml, sylius/mollie-plugin/1.0/manifest.json, sylius/mollie-plugin/2.0/config/packages/sylius_mollie.yaml, sylius/mollie-plugin/2.0/config/routes/sylius_mollie.yaml, sylius/mollie-plugin/2.0/manifest.json
| Packagist     | https://packagist.org/packages/sylius/mollie-plugin
=> Add recipes for `sylius/mollie-plugin:2.0`

huluti/altcha-bundle/1.0/config/packages/huluti_altcha.yaml, huluti/altcha-bundle/1.0/config/routes/huluti_altcha.yaml, huluti/altcha-bundle/1.0/manifest.json
| Packagist     | [huluti/altcha-bundle](https://packagist.org/packages/huluti/altcha-bundle)
=> altcha bundle

storyblok/symfony-bundle/1.2/config/packages/storyblok.yaml, storyblok/symfony-bundle/1.2/config/routes/storyblok.yaml, storyblok/symfony-bundle/1.2/manifest.json
| Packagist     | https://packagist.org/packages/storyblok/symfony-bundle
=> feat: `storyblok/symfony-bundle` `1.2.0` recipes

synolia/sylius-scheduler-command-plugin/4.0/config/packages/sylius_scheduler_command.yaml, synolia/sylius-scheduler-command-plugin/4.0/config/routes/sylius_scheduler_command.yaml, synolia/sylius-scheduler-command-plugin/4.0/manifest.json, synolia/sylius-scheduler-command-plugin/4.0/post-install.txt
| Packagist     | https://packagist.org/packages/synolia/sylius-scheduler-command-plugin
=> add recipe for synolia/sylius-scheduler-command-plugin@v4.0.0

siganushka/generic-bundle/0.3/manifest.json, siganushka/region-bundle/0.1/config/routes/siganushka_region.yaml, siganushka/region-bundle/0.1/manifest.json
These recipes are no longer needed for these library default configurations
| Packagist     | https://packagist.org/packages/siganushka/generic-bundle, https://packagist.org/packages/siganushka/region-bundle
=> Remove generic & region bundle recipe

setono/sylius-toggle-vat-plugin/1.0/config/packages/setono_sylius_toggle_vat.yaml, setono/sylius-toggle-vat-plugin/1.0/config/routes/setono_sylius_toggle_vat.yaml, setono/sylius-toggle-vat-plugin/1.0/manifest.json
| Packagist     | https://packagist.org/packages/setono/sylius-toggle-vat-plugin
=> Add setono/sylius-toggle-vat-plugin

jawira/doctrine-diagram-bundle/1.0/config/packages/doctrine_diagram.yaml, jawira/doctrine-diagram-bundle/1.0/manifest.json
| Packagist     | <https://packagist.org/packages/jawira/doctrine-diagram-bundle>
=> feat: Add recipe for Doctrine Diagram Bundle v1

21torr/storyblok/3.15/config/packages/storyblok.yaml, 21torr/storyblok/3.15/config/routes/storyblok.yaml, 21torr/storyblok/3.15/manifest.json
| Packagist     | https://packagist.org/packages/21torr/storyblok
Just the update for a more recent version, which now needs routing.
=> Add recipe for 21torr/storyblok v3.15+

dama/doctrine-test-bundle/8.3/config/packages/dama_doctrine_test_bundle.yaml, dama/doctrine-test-bundle/8.3/manifest.json
| Packagist     | https://packagist.org/packages/dama/doctrine-test-bundle
=> Add recipe for Dama/DoctrineTestBundle v8.3

cmsig/seal-symfony-bundle/0.8/config/packages/cmsig_seal.yaml, cmsig/seal-symfony-bundle/0.8/manifest.json
| Packagist     | [cmsig/seal-symfony-bundle](https://packagist.org/packages/cmsig/seal-symfony-bundle)
=> Add recipe for cmsig/seal-symfony-bundle

sylius/wishlist-plugin/1.0/config/packages/sylius_wishlist.yaml, sylius/wishlist-plugin/1.0/config/routes/sylius_wishlist.yaml, sylius/wishlist-plugin/1.0/manifest.json
| Packagist     | https://packagist.org/packages/sylius/wishlist-plugin
=> Add recipe for sylius/wishlist-plugin

macpaw/behat-doctrine-fixtures/1.0/config/packages/test/behat_doctrine_fixtures.yaml, macpaw/behat-doctrine-fixtures/1.0/manifest.json
| Packagist     | https://packagist.org/packages/macpaw/behat-doctrine-fixtures
=> Add recipe for macpaw/behat-doctrine-fixtures bundle

sylius/product-bundle-plugin/1.0/config/packages/sylius_product_bundle.yaml, sylius/product-bundle-plugin/1.0/config/routes/sylius_product_bundle.yaml, sylius/product-bundle-plugin/1.0/manifest.json
| Packagist     |  https://packagist.org/packages/sylius/product-bundle-plugin
=> Add recipe for sylius/product-bundle-plugin

sylius/mollie-plugin/3.0/config/packages/sylius_mollie.yaml, sylius/mollie-plugin/3.0/config/routes/sylius_mollie.yaml, sylius/mollie-plugin/3.0/manifest.json
| Packagist     | https://packagist.org/packages/sylius/mollie-plugin
=> Add recipes for sylius/mollie-plugin:3.0

storyblok/symfony-bundle/1.5/config/packages/storyblok.yaml, storyblok/symfony-bundle/1.5/config/routes/storyblok.yaml, storyblok/symfony-bundle/1.5/manifest.json, storyblok/symfony-bundle/1.5/templates/base.html.twig
| Packagist     | https://packagist.org/packages/storyblok/symfony-bundle
=> feat(storyblok): bundle 1.5 recipes

hakam/multi-tenancy-bundle/2.8/config/packages/hakam_multi_tenancy.yaml, hakam/multi-tenancy-bundle/2.8/manifest.json
| Packagist     | https://packagist.org/packages/hakam/multi-tenancy-bundle
=> Add Hakam Multi Tenancy Bundle

sylius/mcp-server-plugin/0.1/config/packages/sylius_mcp_server.yaml, sylius/mcp-server-plugin/0.1/manifest.json
| Packagist     | https://packagist.org/packages/sylius/mcp-server-plugin
=> Add recipes for sylius/mcp-server-plugin

psys/order-invoice-bundle/1.2/manifest.json
| Packagist     | https://packagist.org/packages/psys/order-invoice-bundle
=> Add recipe for psys/order-invoice-bundle v1.2

kocal/oxlint-bundle/1.0/.oxlintrc.json, kocal/oxlint-bundle/1.0/config/packages/kocal_oxlint.yaml, kocal/oxlint-bundle/1.0/manifest.json
| Packagist     | https://packagist.org/packages/kocal/oxlint-bundle
Adding recipe for a new fresh package 💅🏻
=> [KocalOxlintBundle] Add recipe

ehyiah/apidoc-bundle/0.3/config/packages/ehyiah_api_doc.yaml, ehyiah/apidoc-bundle/0.3/config/routes/ehyiah_api_doc.yaml, ehyiah/apidoc-bundle/0.3/manifest.json
| Packagist     | [https://packagist.org/packages/ehyiah/apidoc-bundle](https://packagist.org/packages/ehyiah/apidoc-bundle)
=> add recipe for api doc bundle https://github.com/Ehyiah/ApiDocBundle

shipmonk/doctrine-entity-preloader/1.0/config/packages/doctrine_entity_preloader.yaml, shipmonk/doctrine-entity-preloader/1.0/manifest.json
| Packagist     | https://github.com/shipmonk-rnd/doctrine-entity-preloader
The recipe creates a service for the `EntityPreloader` class.
=> add recipe for shipmonk/doctrine-entity-preloader

doctrine/mongodb-odm-bundle/3.3/config/packages/doctrine_mongodb.yaml, doctrine/mongodb-odm-bundle/3.3/manifest.json, doctrine/mongodb-odm-bundle/4.1/config/packages/doctrine_mongodb.yaml, doctrine/mongodb-odm-bundle/4.1/manifest.json, doctrine/mongodb-odm-bundle/4.4/config/packages/doctrine_mongodb.yaml, doctrine/mongodb-odm-bundle/4.4/manifest.json, doctrine/mongodb-odm-bundle/5.0/config/packages/doctrine_mongodb.yaml, doctrine/mongodb-odm-bundle/5.0/manifest.json
| Packagist     | [doctrine/mongodb-odm-bundle](https://github.com/doctrine/DoctrineMongoDBBundle/)
This is more correct and the way it is [officially documented](https://www.mongodb.com/docs/manual/reference/connection-string/#standard-connection-string-format).
=> [DoctrineMongoDBBundle] Rename `MONGODB_URL` to `MONGODB_URI`
