symfony/recipes-contrib

- misd/phone-number-bundle/1.2/etc/packages/libphonenumber.yaml
- misd/phone-number-bundle/1.2/manifest.json
About this bundle:
* ~700,000 downloads
* https://github.com/misd-service-development/phone-number-bundle
---
This recipe is another experiment. What is the right way to register the PhoneNumberType DBAL type dynamically? I guess the provided `libphonenumber.yaml` is wrong and we'd need some PHP file that detectes if Doctrine exists and then registers the type. Can anyone help me doing that? Thanks!
> Added MisdPhoneNumberBundle

- liip/imagine-bundle/1.8/etc/packages/imagine.yaml
- liip/imagine-bundle/1.8/etc/routing/imagine.yaml
- liip/imagine-bundle/1.8/manifest.json
- liip/imagine-bundle/1.8/post-install.txt
This pull request adds a Symfony Flex recipe for [`LiipImagineBundle`](https://github.com/liip/LiipImagineBundle), a popular image manipulation bundle that leverages the [Imagine Library](https://github.com/avalanche123/Imagine) internally.
I am waiting for some reviews from my fellow bundle maintainers, so do not merge this immediately. Also, as there isn't much information or many examples on writing these recipes yet, I look forward to fielding reviews or change requests from this repository's maintainers, as well.
Hopefully, this bundle will land in the exciting Symfony Flex ecosystem shortly!
> Add Imagine Bundle Recipe

- vich/uploader-bundle/1.5/etc/packages/vich_uploader.yaml
- vich/uploader-bundle/1.5/manifest.json
* The most popular one for file uploading
* 1.2 million downloads
* https://github.com/dustin10/VichUploaderBundle
License MIT
> Added VichUploaderBundle recipe

- algolia/algolia-search-bundle/2.2/etc/packages/algolia.yaml
- algolia/algolia-search-bundle/2.2/manifest.json
* ~70,000 downloads
* It integrates the amazing Algolia search service (we use it on symfony.com for example)
* https://github.com/algolia/AlgoliaSearchBundle
---
I have a question about the env vars. As you can see, in the default config I've used "realistic values" for the APP_ID and API_KEY (the placeholders are similar to the real values that you'll put there). Do you like that ... or do you prefer to put some generic placeholder? Example:
```json
"env": {
"ALGOLIA_APP_ID": "you app ID",
"ALGOLIA_API_KEY": "your API key"
}
```
License MIT
> Added AlgoliaAlgoliaSearchBundle

- exercise/htmlpurifier-bundle/0.2/etc/packages/exercise_html_purifier.yaml
- exercise/htmlpurifier-bundle/0.2/manifest.json
* 600,000 downloads
* https://packagist.org/packages/exercise/htmlpurifier-bundle
---
I've added the `Core.Encoding` option in the default config to make it easier to chage because I guess this could be useful for legacy systems still using `ISO-8859-1` or for our Asian friends who still not use UTF-8. But this is just a guess, so I could be totally wrong.
License MIT
> Added ExerciseHTMLPurifierBundle

- willdurand/geocoder-bundle/4.1/etc/packages/bazinga_geocoder.yaml
- willdurand/geocoder-bundle/4.1/etc/packages/dev/bazinga_geocoder.yaml
- willdurand/geocoder-bundle/4.1/manifest.json
* ~550,000 downloads
* https://github.com/geocoder-php/BazingaGeocoderBundle
---
@Nyholm as you are the new maintainer of the bundle, I'd like to ask you something about the `fake_ip` config recommended for the "dev" environment. Does it have to be a wrong IP as the example showed in https://github.com/geocoder-php/BazingaGeocoderBundle/blob/master/Resources/doc/index.md#killer-feature ... or can be a valid IP?
> Added BazingaGeocoderBundle

- enqueue/async-event-dispatcher/0.7/config/packages/enqueue_async_event_dispatcher.yaml
- enqueue/async-event-dispatcher/0.7/manifest.json
- enqueue/pheanstalk/0.5/manifest.json
contains https://github.com/symfony/recipes-contrib/pull/59.
Contains recipes for enqueue packages:
* enqueue/amqp-bunny
* enqueue/amqp-lib
* enqueue/async-event-dispatcher
* enqueue/gearman
* enqueue/gps (Google PubSub)
* enqueue/sqs (Amazon SQS)
* enqueue/stomp
* enqueue/redis
> Enqueue packages

- willdurand/geocoder-bundle/4.1/manifest.json
See https://github.com/geocoder-php/BazingaGeocoderBundle/blob/4.1.0/BazingaGeocoderBundle.php
> Fix bundle namespace in BazingaGeocoderBundle 4.1

- sroze/openwhisk-bundle/0.2/index.php
- sroze/openwhisk-bundle/0.2/manifest.json
This recipe will automatically create the Openwhisk entry point for the action (or "cloud function").
This makes Symfony deployable to Openwhisk in almost one `composer req`.
Replaces #124 because of the issue #125.
> Add the sroze/openwhisk-bundle recipe

- sentry/sentry-symfony/1.0/config/packages/prod/sentry.yaml
- sentry/sentry-symfony/1.0/config/packages/sentry.yaml
- sentry/sentry-symfony/1.0/manifest.json
This adds Sentry ~0.8~ 1.0 support. 
The difference with #40 is:
* It uses ~0.8~ 1.0 instead of 0.7
* It is installed always, so not only in `prod`. This is handy, because it allows you to depend on `SentrySymfonyClient` in all environments. Only in prod it's filled with the `SENTRY_DSN` so that it will send reports to Sentry.
* It uses `curl_method: async` by default, which is better if you ask me. It doesn't block the requests for the end-user when an exception occurs, but moves it to a shutdown listener.
> Add Sentry 1.0

- aws/aws-sdk-php-symfony/1.3/config/packages/aws.yaml
- aws/aws-sdk-php-symfony/1.3/manifest.json
Manifest for AWS SDK. This one closes for an issue: https://github.com/symfony/flex/issues/193
> Added Manifest file for AWS SDK Bundle

- wisembly/amqp-bundle/1.3/config/packages/wisembly_amqp.yaml
- wisembly/amqp-bundle/1.3/manifest.json
Integration for Wisembly's AMQP bundle, which offers a slightly different (well not so different now...) than the SwarrotBundle. Works with Swarrot.
> Add recipe for Wisembly AMQP bundle

- ekino/newrelic-bundle/1.3/manifest.json
EkinoNewRelicBundle vs NewRelicBundle
See https://github.com/ekino/EkinoNewRelicBundle/blob/master/EkinoNewRelicBundle.php
> The new relic recipe is using a wrong bundle name

- spiechu/symfony-commons-bundle/0.1/config/packages/spiechu_symfony_commons.yaml
- spiechu/symfony-commons-bundle/0.1/manifest.json
Bundle allows to validate JSON / XML responses against given JSON Schema / XSD files using simple controller annotations.
Also allows API versioning and provides compatibility with JMSSerializerBundle `since-version` & `until-version` attributes.
Notice that JMSSerializerBundle and FOSRestBundle are not yet fully compatible with Symfony 4.
> Add spiechu symfony commons bundle

- eightpoints/guzzle-bundle/7.0/config/packages/eight_points_guzzle.yaml
Description: `plugin` option should be on the same level with `options`.
Reference: https://github.com/8p/EightPointsGuzzleBundle#usage
Fix issue: #145
> Fix config for eightpoints/guzzle-bundle

- mmoreram/gearman-bundle/4.1/config/packages/gearman.yaml
- mmoreram/gearman-bundle/4.1/manifest.json
Adds recipe for gearman-bundle. Adding doctrine cache provider this way is safe because this config key is merged.
> Add recipe for mmoreram/gearman-bundle 4.1+

- overblog/graphql-bundle/0.11/config/packages/graphql.yaml
- overblog/graphql-bundle/0.11/config/routes/graphql.yaml
- overblog/graphql-bundle/0.11/manifest.json
- overblog/graphql-bundle/0.11/post-install.txt
- OverblogGraphQLBundle doesn't have GraphiQL embed anymore, this version won't load the dev route
- Also updated post-install.txt
> OverblogGraphQLBundle: Updated recipe to support version 0.11.* 

- doctrine/doctrine-fixtures-bundle/2.4/manifest.json
See: https://github.com/symfony/recipes/pull/286#issuecomment-348217053
I'm not sure if removing this old recipe is strictly required, but it was requested by fabbot (perhaps it's not allowed to have recipes for the same repo on both `recipes` and `recipes-contrib`. It's a little bit confusing at the very least :).
> DoctrineFixturesBundle: Remove recipe, we have one in core

- symfony/apache-pack/1.0/public/.htaccess
This averts the following scenario:
1. Client POSTs
2. server does not support mod rewrite and 302 redirects to /index.php/theaction
3. client follows, but with a GET
4. 405
> Forbid method switching

- wouterj/eloquent-bundle/1.0/config/packages/eloquent.yaml
- wouterj/eloquent-bundle/1.0/manifest.json
This adds a recipe for the WouterJEloquentBundle 1.0.0 release, which supports Symfony 4.
* The configuration is split up in multiple env variables. Eloquent doesn't yet support a URL setting. And [Laravel](https://github.com/laravel/laravel/blob/master/.env.example#L8-L13) splits them up in these variables as well. The values of the variables are equal to the values used in the DoctrineBundle recipe.
* The `eloquent: ~` line is commented because you can use only Illuminate database with this package (just as Doctrine DBAL). However, I think most users will use Eloquent ORM when installing the bundle.
> Added recipe for WouterJEloquentBundle

- long-running/long-running/0.1/manifest.json
Adds support for https://github.com/LongRunning/LongRunning. It uses a different path for the bundle so this will help others by auto installing it :)
> Add recipe for LongRunning

- .travis.yml
We should test if the recipe actually can be installed on a Symfony 3.4 and 4.0 project. 
This travis config is reproducing the steps suggested in symfony.sh. 
If we think this is a good idea. We should enable travis on this repo, but only for pull requests. 
Depending on how fast the symfony-bot is, we might have to add a `sleep 20` command in the "before_install" section.
> Adding travis config

- php-translation/symfony-bundle/0.4/config/packages/php_translation.yaml
Got the next error about invalid path:
```text
Executing script cache:clear [KO]
[KO]
Script cache:clear returned with error code 1
!!
!!  In BaseNode.php line 348:
!!
!!    Invalid configuration for path "translation.configs.app.dirs.1": The direct
!!    ory "/Users/victor/www/symfony/src/src" does not exist.
!!
!!
!!  In Configuration.php line 127:
!!
!!    The directory "/Users/victor/www/symfony/src/src" does n
!!    ot exist.
```
> Fix path to the src/ directory: root_dir -> project_dir

- mmucklo/grid-bundle/4.0/config/packages/dtc_grid.yaml
- mmucklo/grid-bundle/4.0/config/routes/dtc_grid.yaml
- mmucklo/grid-bundle/4.0/manifest.json
- mmucklo/grid-bundle/4.0/post-install.txt
This pull request adds a recipe for DtcGridBundle which has been updated to support Symfony 4.
Former PR #186 
DtcGridBundle as of version 4.0.3 should now install cleanly on a fresh Symfony 4 installation.
> Adding mmucklo/grid-bundle

- qandidate/toggle-bundle/1.0/manifest.json
I thought it would be a good idea to also enable the SecurityBundle because it's a dependency for the QandidateToggleBundle. However when removing the QandidateToggleBundle this recipe also unregisters the SecurityBundle.
> QandidateToggleBundle: do not enable SecurityBundle

- enqueue/job-queue-pack/0.8/etc/packages/enqueue-job-queue.yaml
- enqueue/job-queue-pack/0.8/manifest.json
A pack to install Enqueue's job queue with Doctrine ORM as a storage in a Symfony Flex application
> Add Enqueue job queue pack

- bcc/cron-manager-bundle/3.1/config/packages/bcc_cron_manager_bundle.yaml
- bcc/cron-manager-bundle/3.1/config/routes/bcc_cron_manager_bundle.yaml
- bcc/cron-manager-bundle/3.1/manifest.json
- bcc/cron-manager-bundle/3.1/post-install.txt
This PR adds recipes for the BCCCronManagerBundle 3.1 (https://github.com/michelsalib/BCCCronManagerBundle/pull/82 and https://github.com/michelsalib/BCCCronManagerBundle/pull/84)
> Adding BCCCronManagerBundle 3.1 recipe

- nelmio/api-doc-bundle/3.0/config/packages/nelmio_api_doc.yaml
- nelmio/api-doc-bundle/3.0/config/routes/nelmio_api_doc.yaml
- nelmio/api-doc-bundle/3.0/manifest.json
Fixes https://github.com/symfony/recipes-contrib/issues/197 and https://github.com/symfony/recipes-contrib/pull/207
> Add NelmioApiDocBundle 3.0 support

- knplabs/github-api/2.6/config/packages/github_api.yaml
Fix the YAML configuration for `Github\Client` calls. Use this way, this will trigger an error:
> Type error: Argument 2 passed to Symfony\Component\DependencyInjection\Definition::addMethodCall() must be of the type array, string given
> Fix Github\Client calls configuration

- sonata-project/core-bundle/3.9/config/packages/sonata_core.yaml
Configuration file must be inside `config/packages` directory, not in `config/packages/sonata_project`.
With this PR i moved `config/packages/sonata_project/sonata_core.yaml` file to `config/packages/` and removed redundant parameter.
Travis was green in https://github.com/symfony/recipes-contrib/pull/240, because `sonata-project/core-bundle` does not need any additional configuration
> Fix sonata-project/core-bundle config

- algolia/search-bundle/3.0/config/packages/algolia_search.yaml
- algolia/search-bundle/3.0/manifest.json
- algolia/search-bundle/3.0/post-install.txt
There is already a recipe for the Algolia Search Bundle and I have just released the version 3.0. Version 2 will be maintained (patch-only) but should not be installed for new projects.
This version introduce many new features but mostly:
* **Simple**: You can get started with only 5 lines of YAML
* **Extensible**: It let’s you easily replace services by implementing Interfaces
* **Standard**: It leverages `Normalizers` to convert entities for indexing
* **Dev-friendly**: It lets you disable HTTP calls easily (while running tests for examples)
* **Futur-ready**: It let’s you unsubscribe from doctrine events easily to use a messaging/queue system.
Documentation can be found …
> Introduce algolia/search-bundle v3

- roukmoute/hashids-bundle/1.4/config/packages/roukmoute_hashids.yaml
- roukmoute/hashids-bundle/1.4/manifest.json
> Add support for Roukmoute Hashids bundle

- hillrange/ckeditor/0.1/manifest.json
Add default option for install of CKEditor Scripts.
> Change manifest to install CKEditor Scripts by default.

- msgphp/user-bundle/0.2/src/Entity/User/User.php
Looking at some other entity-providing bundles..., they all do this: enable doctrine mapping by default. It doesnt break without doctrine (it's metadata-ish).. so seems a good DX improvement :)
> [MsgPhpUserBundle] enable doctrine mapping

- snc/redis-bundle/2.0/config/packages/snc_redis.yaml
The recipe should not be opinionated about using phpredis or predis as the bundle supports both.
Fixes #335
> Fix RedisBundle recipe to always work out of the box

- nelmio/api-doc-bundle/3.0/config/routes/nelmio_api_doc.yaml
After applying this recipe, the route "/api/doc" was loaded by default, but it requires two component (`asset` and `twig`) that are usually not require for API only project.
The json route works of the box so it can be provided without additional action.
I faced it and it felt strange, and it seems that others have too : https://github.com/nelmio/NelmioApiDocBundle/issues/1220
> Make the nelmio/api-doc-bundle recipe works out of the box

- msgphp/eav-bundle/0.2/src/Entity/Eav/Attribute.php
- msgphp/eav-bundle/0.2/src/Entity/Eav/AttributeValue.php
`msgphp_*_id` resolves to integer by default, so adding `@ORM\GeneratedValue()` seems a good DX improvement. At least it's more obvious to remove then to add.
>  [MsgPhpEavBundle] Add ORM GeneratedValue annotation

- sonata-project/notification-bundle/3.4/config/packages/sonata_notification.yaml
- sonata-project/notification-bundle/3.4/manifest.json
> Add sonata-project/notification-bundle recipe

- .travis.yml
With this PR will `composer req` command will ignore `php`, `hhvm`, `lib-*` and `ext-*` requirements and force the installation.
This is helpful for testing recipes of packages, that provide platform via their dependencies. For example, [sonata-project/media-odm-pack](https://packagist.org/packages/sonata-project/media-odm-pack) depends on [alcaeus/mongo-php-adapter](https://packagist.org/packages/alcaeus/mongo-php-adapter), which provides `ext-mongo`. `sonata-project/media-odm-pack` cannot be installed just with `composer require sonata-project/media-odm-pack`, only after executing after `composer config platform.ext-mongo 1.6.16`
See also https://github.com/composer/composer/issues/5030, a similar issue was described there …
> Add --ignore-platform-reqs option to composer require command

- sonata-project/media-odm-pack/1.0/config/packages/sonata_media_odm.yaml
- sonata-project/media-odm-pack/1.0/manifest.json
- sonata-project/media-odm-pack/1.0/src/Document/SonataMediaGallery.php
- sonata-project/media-odm-pack/1.0/src/Document/SonataMediaGalleryHasMedia.php
- sonata-project/media-odm-pack/1.0/src/Document/SonataMediaMedia.php
To test a recipe execute following commands:
```bash
composer create-project symfony/skeleton .
composer config extra.symfony.allow-contrib true
export SYMFONY_ENDPOINT=https://symfony.sh/r/github.com/symfony/recipes-contrib/410
composer config platform.ext-mongo 1.6.16
composer require sonata-project/media-odm-pack
```
Create `docker-compose.yaml`
```yaml
version: '3.4'
services:
mongo:
image: mongo:3.6
ports:
- "27017:27017"
environment:
MONGO_DATA_DIR: /data/db
volumes:
- database:/data/db
volumes:
database:
```
Execute commands:
```bash
docker-compose up -d
bin/console doctrine:mongodb:schema:create
php -S 127.0.0.1:80 -t public
```
Under Windows (for Docker Toolbox) update `.env` file: change `localhost` in …
> Add sonata-project/media-odm-pack recipe

- contao/core-bundle/4.6/config/packages/contao_core.yaml
- contao/core-bundle/4.6/manifest.json
- contao/core-bundle/4.6/post-install.txt
- contao/installation-bundle/4.6/config/routes/contao_installation.yaml
- contao/installation-bundle/4.6/manifest.json
> Add contao/core-bundle and contao/installation-bundle

- liip/imagine-bundle/1.8/manifest.json
> Add LiipImagineBundle's cache folder to .gitignore

- dunglas/doctrine-json-odm/0.1/manifest.json
- dunglas/doctrine-json-odm/0.1/post-install.txt
https://github.com/dunglas/doctrine-json-odm
A recipe is mandatory because the bundle is provided in the library, thus cannot be auto-discovered by Flex.
> Add a recipe for dunglas/doctrine-json-odm

- symfony-cmf/cmf-phpcr-dbal-pack/1.0/config/packages/cmf_phpcr_dbal.yaml
Changed `routder` to `router`; this should fix an error while installing:
```  - Configuring symfony-cmf/cmf-phpcr-dbal-pack (>=1.0): From github.com/symfony/recipes-contrib:master
Executing script cache:clear [KO]
[KO]
Script cache:clear returned with error code 1
!!
!!  In CheckExceptionOnInvalidReferenceBehaviorPass.php line 31:
!!
!!    The service "router" has a dependency on a non-existent service "routder.de
!!    fault".
```
> Fixes typo in symfony-cmf/cmf-phpcr-dbal-pack

- msgphp/eav-bundle/0.2/src/Entity/Eav/Attribute.php
- msgphp/eav-bundle/0.2/src/Entity/Eav/AttributeValue.php
- msgphp/user-bundle/0.6/src/Entity/User/User.php
Key columns only support a max length of 191 characters in mysql/maria db on default, using the `utf8mb4` charset and `utf8mb4_unicode_ci` collate.
This change ensures that msgphp user bundle will work out of the box as well as prepare for https://github.com/msgphp/msgphp/pull/214
> updating msgphp user receipt for mysql/maria db as well as msgphp pull 214

- doctrine/phpcr-dbal-symfony-pack/1.0/config/packages/doctrine_phpcr_dbal.yaml
As part of the solution in https://github.com/doctrine/DoctrinePHPCRBundle/pull/330, offer recipe based `App\Document` resolution.
> Offer default \App\Document\ resolution

- .travis.yml
The different packages need to be passed as separate arguments to `composer require`
#SymfonyConHackday2018
> Fix the travis build when changing multiple recipes

- nyholm/psr7/1.0/config/packages/nyholm_psr7.yaml
HTTPlug factories are deprecated.
And PSR-17 should work out of the box when needed since that's the only sane entry point to PSR-7 world, from DI perspective.
See https://github.com/symfony/recipes-contrib/pull/329#issuecomment-376473240 for past discussion about this.
> Register nyholm/psr7 services for autowiring with PSR-17 (HTTP factories)

- friendsofsymfony/jsrouting-bundle/2.3/config/routes/fos_js_routing.yaml
- friendsofsymfony/jsrouting-bundle/2.3/manifest.json
See https://github.com/FriendsOfSymfony/FOSJsRoutingBundle/issues/327, we added a new routing.xml with the new syntax to keep BC. New installations should automatically use the new xml file which is done in this recipe.
> Add recipe for FOSJSRoutingBundle >2.3, to fix deprecation on Symfony >4.1

- tienvx/mbt-api-bundle/1.0/config/packages/tienvx_mbt_api.yaml
- tienvx/mbt-api-bundle/1.0/config/routes/tienvx_mbt_api.yaml
- tienvx/mbt-api-bundle/1.0/manifest.json
1. Add recipe for [tienvx/mbt-api-bundle](https://packagist.org/packages/tienvx/mbt-api-bundle)
2. The bundle only support symfony 4.2, so Travis CI build failed for Symfony 3.4, but passed for Symfony 4.2
> Add recipe tienvx/mbt-api-bundle

- deamon/logger-extra-bundle/4.0/config/packages/deamon_logger_extra.yaml
- deamon/logger-extra-bundle/4.0/manifest.json
Add manifest for logger extra bundle
| ---------- | ---
| License    | MIT
> Add deamon-logger-extra-bundle recipe

- sentry/sentry-symfony/3.0/config/packages/sentry.yaml
- sentry/sentry-symfony/3.0/manifest.json
This is a WIP, the v3 of the bundle in under development.
When this is merged, will it impact beta releases too?
> Add different recipe for Sentry bundle v3

- kunstmaan/media-bundle/5.2/manifest.json
We use the `public/uploads` directory for all cms uploads. This will make sure the folder is there after install and the content is ignored.
> Create the cms upload folder during install of kunstmaan/media-bundle

- knplabs/github-api/2.6/config/packages/github_api.yaml
Related to https://github.com/symfony/recipes/pull/613 (but not a blocker)
/cc @Nyholm let's use this style as much as possible instead of relying on `Http\Discovery\*`, OK?
> [knplabs/github-api] Wire existing HTTPlug factories when possible

- sroze/messenger-enqueue-transport/0.1/manifest.json
Hi! The package was renamed from the enqueue organization - https://github.com/sroze/messenger-enqueue-transport/commit/222138523c9f30991bca0199f3479531fe8b40b9
I duplicated the old recipe, which should fix: https://github.com/sroze/messenger-enqueue-transport/issues/73
Cheers!
> Adding recipe for sroze/messenger-enqueue-transport

- thecodingmachine/graphqlite-bundle/3.0/config/packages/graphqlite.yaml
- thecodingmachine/graphqlite-bundle/3.0/manifest.json
This PR adds the Graphqlite bundle to list of recipes.
Graphqlite is a new GraphQL library for PHP that aims at simplifying the use of Webonix/GraphQL.
> Adding Graphqlite bundle

- netgen/layouts-core/1.0/config/routes/netgen_layouts.yaml
- netgen/layouts-core/1.0/manifest.json
- netgen/layouts-core/1.0/post-install.txt
> Add recipe for netgen/layouts-core

- doctrine/phpcr-dbal-symfony-pack/1.0/config/packages/doctrine_phpcr_dbal.yaml
- doctrine/phpcr-dbal-symfony-pack/1.0/config/packages/prod/doctrine_phpcr_dbal.yaml
> Tweak default cache conf to rely on Symfony Cache and only in prod

- tienvx/mbt-bundle/1.7/config/packages/tienvx_mbt.yaml
- tienvx/mbt-bundle/1.7/manifest.json
1. Add recipe for [tienvx/mbt-bundle](https://packagist.org/packages/tienvx/mbt-bundle)
2. The bundle only support symfony 4.3, so Travis CI build failed for Symfony 3.4, but passed for Symfony 4.3
> Add tienvx/mbt-bundle

- kunicmarko/jms-messenger-adapter/0.1/config/packages/jms_messenger.yaml
Somehow it was wrong,  see docs https://github.com/kunicmarko20/jms-messenger-adapter
/cc @kunicmarko20
> Use `default_serializer` instead of `id`

- mmucklo/grid-bundle/5.0/config/routes/dtc_grid.yaml
- mmucklo/grid-bundle/5.0/manifest.json
Removes requirement on deprecated twig-engine as of mmucklo/grid-bundle 5.0
> mmucklo/grid-bundle (5.0): Removed dependency on deprecated twig-engine

- tienvx/mbt-api-bundle/1.12/config/packages/tienvx_mbt_api.yaml
- tienvx/mbt-api-bundle/1.12/config/routes/tienvx_mbt_api.yaml
- tienvx/mbt-api-bundle/1.12/manifest.json
This bundle does not work with Symfony 3.x
> tienvx/mbt-api-bundle (1.12): Replace java and plantuml by dot

- snc/redis-bundle/2.0/config/packages/snc_redis.yaml
Predis is not maintained anymore
> Prefer phpredis by default on the recipe

- kunstmaan/node-bundle/5.2/config/packages/kunstmaan_node.yaml
Enabling node locking is a better and more sensible default config
> KunstmaanNodeBundle - Enable node locking by default

- php-http/httplug-bundle/1.6/config/packages/httplug.yaml
preserving headers on redirects includes a potential security risk because on redirect to a different domain credential headers would be leaked.
resurrected https://github.com/symfony/recipes/pull/524
> avoid dangerous example config in recipe

- prooph/event-store-bus-bridge/3.1/config/packages/prooph_event_store_bus_bridge.yaml
The TransactionManager service is not compatible with the preconfigured
event store from the prooph/pdo-event-store [flex recipe](https://github.com/symfony/recipes-contrib/blob/master/prooph/pdo-event-store/1.7/config/packages/prooph_pdo_event_store.yaml#L7-L12).
In order to use it, one must first reconfigure the event store
definition to use the PostgresEventStore implementation (instead of the
MySqlEventStore implementation).
See https://github.com/prooph/pdo-event-store/issues/39
> [prooph/event-store-bus-bridge] Removes incompatible service

- php-translation/symfony-bundle/0.10/config/packages/dev/php_translation.yaml
- php-translation/symfony-bundle/0.10/config/packages/php_translation.yaml
- php-translation/symfony-bundle/0.10/config/routes/dev/php_translation.yaml
- php-translation/symfony-bundle/0.10/config/routes/php_translation.yaml
- php-translation/symfony-bundle/0.10/manifest.json
The only change is `.yml` to `.yaml` for the routing files.
> PHP-Translations version 0.10.0

- tilleuls/sylius-quick-import-plugin/0.1/config/routes/sylius_quick_import.yaml
- tilleuls/sylius-quick-import-plugin/0.1/manifest.json
> This plugin has been written during the COVID-19 pandemic. The goal was to allow shoppers to build quick website and to import catalog without effort.
https://github.com/coopTilleuls/CoopTilleulsSyliusQuickImportPlugin
> Add tilleuls/sylius-quick-import-plugin

- kunstmaan/node-bundle/5.5/config/packages/kunstmaan_node.yaml
- kunstmaan/node-bundle/5.5/config/routes/kunstmaan_node.yaml
- kunstmaan/node-bundle/5.5/manifest.json
This feature is not required by default and will provide a better user experience with symfony 4.4 (trackingUsageTokenStorage changes)
> KunstmaanNodeBundle: Disable permissions by default for v5.5+

- symfony/apache-pack/1.0/public/.htaccess
`.htaccess` has a commented out `Options FollowSymlinks` suggestion. When uncommented, it overwrites options defined in any prior `Options` directive (for instance in the main Apache configuration). See [Apache doc](https://httpd.apache.org/docs/current/fr/mod/core.html#options).
I think it should rather be `Options +FollowSymlinks` so that it enables that option without disabling others.
> [symfony/apache-pack] Better FollowSymlinks suggestion

- gpslab/geoip2/2.0/config/packages/gpslab_geoip.yaml
- gpslab/geoip2/2.0/manifest.json
The [`gpslab/geoip2`](https://github.com/gpslab/geoip2) package has a [new major release](https://github.com/gpslab/geoip2/releases/tag/v2.0.0) and needs update the recipe configuration for this release.
Before
```yml
gpslab_geoip:
cache: '%kernel.cache_dir%/GeoLite2-City.mmdb'
url: 'https://geolite.maxmind.com/download/geoip/database/GeoLite2-City.mmdb.gz'
locales: [ 'en' ]
```
After
```yml
gpslab_geoip:
license: 'XXXXXXXXXXXXXXXX'
edition: 'GeoLite2-City'
path: '%kernel.cache_dir%/GeoLite2-City.mmdb'
url: 'https://download.maxmind.com/app/geoip_download?edition_id=%s&license_key=%s&suffix=tar.gz'
locales: [ 'en' ]
```
> Configure gpslab/geoip2:~2.0

- meteo-concept/hcaptcha-bundle/1.0/config/meteo_concept_hcaptcha.yaml
- meteo-concept/hcaptcha-bundle/1.0/manifest.json
This is the recipe for new bundle MeteoConcept/HCaptchaBundle (available https://github.com/Meteo-Concept/hcaptcha-bundle and on Packagist here: https://packagist.org/packages/meteo-concept/hcaptcha-bundle).
> Create recipe for MeteoConcept/HCaptchaBundle

- meteo-concept/hcaptcha-bundle/1.0/config/packages/meteo_concept_h_captcha.yaml
The package expects a meteo_concept_h_captcha.yaml file to exist instead of meteo_concept_hcaptcha.yaml
> Rename meteo_concept_hcaptcha.yaml to meteo_concept_h_captcha.yaml

- kunstmaan/search-bundle/5.6/config/packages/kunstmaan_search.yaml
- kunstmaan/search-bundle/5.6/manifest.json
In Kunstmaan/KunstmaanBundlesCMS#2695 we added support for Elasticsearch 7. This recipe change add the correct config to get the user up and running and some info to switch to a lower version.
> Kunstmaan/search-bundle: Setup parameter for ES7 support in v5.6

- misd/phone-number-bundle/1.3/config/packages/misd_phone_number.yaml
- misd/phone-number-bundle/1.3/post-install.txt
Following https://github.com/misd-service-development/phone-number-bundle/issues/217
This PR adds a warning in the post_install script of `misd/phone-number-bundle` that indicate the package `abandoned`
> Mark the misd/phone-number-bundle abandoned

- kerox/twig-image-placeholder-extension/1.0/config/packages/kerox_twig_image_placeholder.yaml
> Fix wrong class name for kerox/twig-image-placeholder-extension

- payum/payum-bundle/2.4/config/payum.yaml
The current recipe for [PayumBundle](https://github.com/Payum/PayumBundle) uses the old directory structure of Symfony < 4. This update changes the location of the storage to use `kernel.project_dir` instead of `kernel.root_dir`, and also uses the `var` folder for storage instead of `app/Resources`.
This ensures compatibility with all the latest versions of Symfony.
> Update storage directory for PayumBundle

- sonata-project/page-bundle/3.9/config/packages/sonata_page.yaml
Using the correct service id for the slugify service configuration.
The service id is available in the page bundle itself and this also removes a dependency on the now deprecated and abandoned sonata core bundle.
> Corrected service id in configuration file

- bref/symfony-bridge/0.1/manifest.json
- bref/symfony-bridge/0.1/post-install.txt
- bref/symfony-bridge/0.1/serverless.yaml
Following #1127, this is the first draft of the recipe.
Ping @t-richard, @mnapoli
> Add recipe for bref/symfony-bridge

- sulu/sylius-consumer-bundle/0.4/config/packages/sulu_sylius_consumer.yaml
- sulu/sylius-consumer-bundle/0.4/manifest.json
- sulu/sylius-producer-plugin/0.2/config/packages/sulu_sylius_producer.yaml
- sulu/sylius-producer-plugin/0.2/manifest.json
Linked to packages:
* https://github.com/sulu/SuluSyliusConsumerBundle
* https://github.com/sulu/SuluSyliusProducerPlugin
The CI is failing because there is no phpcr/phpcr-implementation available. This is required in sulu's skeleton, see https://github.com/sulu/skeleton/blob/2.x/composer.json#L38
Already explained here #995 (comment) by @alexander-schranz
> Sulu sylius integration

- friendsofsymfony/oauth-server-bundle/1.6/config/packages/fos_oauth_server.yaml
- friendsofsymfony/oauth-server-bundle/1.6/config/routes/fos_oauth_server.yaml
- friendsofsymfony/oauth-server-bundle/1.6/manifest.json
- friendsofsymfony/oauth-server-bundle/1.6/src/Entity/AccessToken.php
- friendsofsymfony/oauth-server-bundle/1.6/src/Entity/AuthCode.php
- friendsofsymfony/oauth-server-bundle/1.6/src/Entity/Client.php
- friendsofsymfony/oauth-server-bundle/1.6/src/Entity/RefreshToken.php
Follow-up of https://github.com/symfony/recipes-contrib/pull/364
Fixes https://github.com/FriendsOfSymfony/FOSOAuthServerBundle/issues/501 and https://github.com/FriendsOfSymfony/FOSOAuthServerBundle/issues/638
It is my first recipe so I may have missed some things.
FTR entities properties are `protected` because their parent’s are.
> Add recipe for FOSOAuthServerBundle

- squizlabs/php_codesniffer/3.6/manifest.json
- squizlabs/php_codesniffer/3.6/phpcs.xml.dist
Wasn't sure about the version bump but _think_ this is right...
* Added `3.6` (as that's the latest version of `php_codesniffer`) due to 'BC break' of changing the coding standard.
* Symlinked manifest file to `3.0` version (as didn't change)
I realise the vast majority of people using symfony will use php-cs-fixer, but for those who do wish to use `php_codesniffer` the Symfony standard isn't easily supported (there are [community efforts](https://github.com/djoos/Symfony-coding-standard) I believe). However, for simplicity and to be in line with the previous version I think it makes sense to just keep this to PSR12.
> [PHP_CodeSniffer] Update php_codesniffer recipe to use PSR12.

- .travis.yml
The problem when the project uses symfony/framework-bundle.
composer require --ignore-platform-reqs install  psr/cache 2.0, his support only PHP 8, but in Travis use PHP 7.4.
1) Remove --ignore-platform-reqs 
or 
2) Use in build PHP 8.0
PHP 8.0 now many libraries does not use this version, because I think good idea remove --ignore-platform-reqs
> Run Travis on PHP 8 and drop SF 3.4

- bref/symfony-bridge/0.1/serverless.yaml
At the moment the whole `public/build` directory is excluded. 
This means the `entrypoints.json` and `manifest.json` files are also excluded but are required by Symfony to resolve filenames correctly and load Encore entrypoints in Twig.
Without this, people would get a 500 error when deploying on Lambda.
> Fix compatibility with Webpack-Encore in bref/symfony-bridge

- league/flysystem-bundle/1.0/post-install.txt
This will fix #1101
These instructions are not needed and they will differ from Flysystem v1 vs v2. Fyi @tgalopin
> Remove invalid Flysystem instructions

- kunstmaan/admin-bundle/5.9/config/packages/kunstmaan_admin.yaml
- kunstmaan/admin-bundle/5.9/config/routes/kunstmaan_admin.yaml
- kunstmaan/admin-bundle/5.9/manifest.json
The upcoming 5.9 version allows to disable the exception logging module and this is a more sensible default config. The 5.9 version is not yet released, but this PR prepare the recipe already
> kunstmaan/admin-bundle: Disable exception logging by default

- zenstruck/signed-url-bundle/0.1/manifest.json
| Packagist     | https://packagist.org/packages/zenstruck/signed-url-bundle
Flex's auto-configure bundle doesn't work because of the bundle's namespace.
> Add zenstruck/signed-url-bundle

- hautelook/alice-bundle/2.1/config/packages/dev/hautelook_alice.yaml
- hautelook/alice-bundle/2.1/config/packages/test/hautelook_alice.yaml
- hautelook/alice-bundle/2.1/manifest.json
- hautelook/alice-bundle/2.1/post-install.txt
This package has been an official recipe for more than 3 years, see https://github.com/symfony/recipes/tree/master/hautelook/alice-bundle/2.1
Thus, it does not belong here as this is misleading and could cause unexpected behaviour. For example, the now retired Flex Server displays a contrib package with aliases which should not happen.
It seems the files were only partially removed in https://github.com/symfony/recipes-contrib/pull/523
> Delete Hautelook from contrib

- qossmic/deptrac-shim/0.19/deptrac.yaml
- qossmic/deptrac-shim/0.19/manifest.json
| Packagist     | [qossmic/deptrac](https://packagist.org/packages/qossmic/deptrac)
In version 0.19 the default config filename and format has changed
> Update qossmic/deptrac recipe for version 0.19

- doctrine/mongodb-odm-bundle/4.1/config/packages/doctrine_mongodb.yaml
- doctrine/mongodb-odm-bundle/4.1/manifest.json
> Upgrade mongodb-odm-bundle for doctrine/cache 1.11+

- snc/redis-bundle/2.0/config/packages/snc_redis.yaml
| Packagist     | https://packagist.org/packages/snc/redis-bundle
The link for further instructions in the SncRedisBundle configuration no longer works.
Corrected it so that it leads to the docs again.
> Update broken SncRedisBundle instructions link

- drenso/symfony-oidc-bundle/2.0/config/packages/drenso_oidc.yaml
- drenso/symfony-oidc-bundle/2.0/manifest.json
| Packagist     | https://packagist.org/packages/drenso/symfony-oidc-bundle
Adds a recipe for v2 of `drenso/symfony-oidc-bundle`, which should be released soon. The configuration options won't change anymore between the now (the current master branch) and the v2 release.
> Add recipe for drenso/symfony-oidc-bundle v2

- kunstmaan/admin-bundle/5.10/config/packages/kunstmaan_admin.yaml
- kunstmaan/admin-bundle/5.10/config/routes/kunstmaan_admin.yaml
- kunstmaan/admin-bundle/5.10/manifest.json
| Packagist     | https://packagist.org/packages/kunstmaan/admin-bundle
The old system is deprecated, this recipe makes sure that new installs will use the new authentication system
> kunstmaan/admin-bundle: Use new authentication system by default

- rikudou/psr6-dynamo-db-bundle/2.0/config/packages/prod/rikudou_dynamo_db_cache.yaml
- rikudou/psr6-dynamo-db-bundle/2.0/manifest.json
| Packagist     | https://packagist.org/packages/rikudou/psr6-dynamo-db-bundle
This bundle provides a PSR-6 cache adapter for Symfony + a Session handler both storing data in AWS DynamoDB.
I enabled it only in `prod` because it would otherwise require a local DynamoDB emulator (probably using Docker) or a real DynamoDB table for local development which is not ideal.
Also, `AWS_REGION` is commented because
* it could already be defined if using another AWS-related package 
* it might be predefined in an AWS environment (eg. variables exists in AWS Lambda).
@RikudouSage would love your thoughts on this before going further.
> Add recipe for rikudou/psr6-dynamo-db-bundle

- stof/doctrine-extensions-bundle/1.2/config/packages/stof_doctrine_extensions.yaml
The package changed its `main` branch and moved to a new GitHub organization.
This fixes the URL to the new package.
> fixing docu url

- .github/workflows/qa.yml
It was removed from the callable workflow https://github.com/symfony/recipes/commit/07cc58ffd13fe05406b7dd23b9e5034c6dfd82fa
It currently breaks the workflow: https://github.com/symfony/recipes-contrib/actions/runs/1962132102/workflow
> Remove create_project_php parameter

- sonata-project/doctrine-extensions/1.8/manifest.json
- sonata-project/exporter/2.4/manifest.json
- sonata-project/twig-extensions/1.2/manifest.json
| Packagist     | https://packagist.org/packages/sonata-project/doctrine-extensions https://packagist.org/packages/sonata-project/exporter https://packagist.org/packages/sonata-project/twig-extensions
This PRs attempts to fix this problem: https://github.com/sonata-project/SonataAdminBundle/issues/7784
We tried to add a hack around flex to be able to auto discover the bundle file for our bridges: 
https://github.com/sonata-project/twig-extensions/pull/100
https://github.com/sonata-project/exporter/pull/345
https://github.com/sonata-project/sonata-doctrine-extensions/pull/209
It was not a really good idea since not only is confusing to have a file like this: 
https://github.com/sonata-project/twig-extensions/blob/1.x/src/Bridge …
> Add Sonata bridges recipes

- nucleos/dompdf-bundle/3.1/config/packages/nucleos_dompdf.yaml
See https://github.com/dompdf/dompdf/issues/2810#issuecomment-1070927239 for the reason and https://github.com/dompdf/dompdf/issues/1709#issuecomment-466717959 for the solution
| Packagist     | https://repo.packagist.org/packages/nucleos/dompdf-bundle
> Adding `logOutputFile: '/dev/null'`

- zenstruck/twig-service-bundle/0.2/manifest.json
| Packagist     | https://packagist.org/packages/zenstruck/twig-service-bundle
Bundle isn't auto-configured by flex.
> add zenstruck/twig-service-bundle recipe

- jane-php/json-schema/7.0/bin/jane-json-schema-generate
| Packagist     | https://packagist.org/packages/jane-php/json-schema
> Fix Jane-php json schema recipe binary for v7 releases

- leapt/im-bundle/4.1/config/packages/leapt_im.yaml
- leapt/im-bundle/4.1/config/routes/leapt_im.yaml
- leapt/im-bundle/4.1/manifest.json
| Packagist     | https://packagist.org/packages/leapt/im-bundle
> leapt/im-bundle: import PHP routing instead of YAML

- doctrine/mongodb-odm-bundle/4.4/config/packages/doctrine_mongodb.yaml
- doctrine/mongodb-odm-bundle/4.4/manifest.json
| Packagist     | [doctrine/mongodb-odm-bundle](https://packagist.org/packages/doctrine/mongodb-odm-bundle)
The recipe fixes the following deprecation:
Since doctrine/mongodb-odm-bundle 4.4: Configuring doctrine/cache is deprecated. Please update the cache service "doctrine_mongodb.system_cache_provider" to use a PSR-6 cache.
> Add mongodb-odm-bundle recipe for version 4.4

- sentry/sentry-symfony/3.0/config/packages/prod/sentry.yaml
- sentry/sentry-symfony/4.0/config/packages/sentry.yaml
- sentry/sentry-symfony/4.0/manifest.json
> use when@prod for sentry

- pasaiakoudala/authbundle/0.1/config/packages/security.yaml.dist
The `security.yaml.dist` is not following the 4 spaces indention which it should.
> Fix indention of example yaml file

- jms/serializer-bundle/4.0/config/packages/jms_serializer.yaml
- jms/serializer-bundle/4.0/manifest.json
| Packagist     | jms/serializer-bundle
/cc @goetas 
Symfony switch to use `when@env` everywhere in there core bundle configuraitons.
This will update jms serializer to use als `when@prod` and `when@dev` instead of splitting it into seperate files.
> Use when@env for jms serializer configuration

- sonata-project/page-bundle/4.0/config/packages/sonata_page.yaml
- sonata-project/page-bundle/4.0/config/routes/sonata_page.yaml
- sonata-project/page-bundle/4.0/manifest.json
- sonata-project/page-bundle/4.0/post-install.txt
- sonata-project/page-bundle/4.0/src/Entity/SonataPageBlock.php
- sonata-project/page-bundle/4.0/src/Entity/SonataPagePage.php
- sonata-project/page-bundle/4.0/src/Entity/SonataPageSite.php
- sonata-project/page-bundle/4.0/src/Entity/SonataPageSnapshot.php
| Packagist     | https://packagist.org/packages/sonata-project/page-bundle
> Sonata Page Bundle 4

- vich/uploader-bundle/1.13/config/packages/vich_uploader.yaml
- vich/uploader-bundle/1.13/manifest.json
| Packagist     | [uploader-bundle](https://packagist.org/packages/vich/uploader-bundle)
Since version 1.13, UploaderBundle deprecated not using a namer. This new configuration reflects the new behaviour.
See also [UPGRADE.md](https://github.com/dustin10/VichUploaderBundle/blob/master/UPGRADE.md#upgrading-from-v1120-to-1130) on bundle repo.
> update VichUploaderBundle recipe

- contao/installation-bundle/4.10/config/routes/contao_installation.yaml
- contao/installation-bundle/4.10/manifest.json
| Packagist     | https://packagist.org/packages/contao/installation-bundle
Changed the included `routes.yml` which changed from `routing.yml` to `routes.yml` in Contao 4.10.
See: https://github.com/contao/installation-bundle/commit/6a6567fd4985c9fc4ddd02bb40a6060359bfc9a2
> Since Contao 4.10, the path for the routes configuration changed

- google/apiclient/2.10/config/packages/google_apiclient.yaml
- google/apiclient/2.10/manifest.json
| Packagist     | https://packagist.org/packages/google/apiclient
Since 2.10, Google API Client use namespaces: `Google\Client`
`Google_Client` will be deprecated in the future.
See https://github.com/googleapis/google-api-php-client/blob/main/UPGRADING.md#2x-to-2100
> Update google/apiclient recipe

- sulu/form-bundle/2.4/config/packages/sulu_form.yaml
- sulu/form-bundle/2.4/config/routes/sulu_form_admin.yaml
- sulu/form-bundle/2.4/manifest.json
- sulu/form-bundle/2.4/post-install.txt
| Packagist     | [sulu/form-bundle](github.com/sulu/suluformbundle)
The 2.4 not longer requires enabling of the esi and fragments configuration. So the following was removed: https://github.com/symfony/recipes-contrib/blob/7645718b41e85fdadea21149322cbabf9c2d4840/sulu/form-bundle/2.2/config/packages/sulu_form.yaml#L9-L11
> Add sulu form bundle 2.4 recipe

- monsieurbiz/sylius-rich-editor-plugin/2.0/config/packages/monsieurbiz_sylius_rich_editor_plugin.yaml
- monsieurbiz/sylius-rich-editor-plugin/2.0/config/routes/monsieurbiz_sylius_rich_editor_plugin.yaml
- monsieurbiz/sylius-rich-editor-plugin/2.0/manifest.json
See https://github.com/symfony/recipes-contrib/pull/914 for the v1.
The recipe is almost the same. The routing is a bit different and needs a new version of the recipe.
> Add recipe for monsieurbiz/sylius-rich-editor-plugin in v2

- symfony/apache-pack/1.0/public/.htaccess
RewriteRule needs FollowSymlinks to be enabled at any times
without the Option you get:
> AH00670: Options FollowSymLinks and SymLinksIfOwnerMatch are both off, so the RewriteRule directive is also forbidden due to its similar ability to circumvent directory restrictions
> `FollowSymlinks` to be enabled at any times

- aziz403/ux-zoom/1.0/manifest.json
| Packagist     | `Aziz403/ux-zoom`
Fix issue of failing CI in the recipe update: https://github.com/schranz-php-recipes/symfony-recipes-php-contrib/actions/runs/3725022578/jobs/6317565427
FYI @Aziz403, requires https://github.com/Aziz403/ux-zoom/pull/1
Related PR: #1466
> Fix not defined bundle class in Aziz403/ux-zoom bundle

- doctrine/mongodb-odm-bundle/4.4/config/packages/doctrine_mongodb.yaml
| Packagist     | https://packagist.org/packages/doctrine/mongodb-odm-bundle
Similar to https://github.com/symfony/recipes/pull/971
> Rely on default mapping type

- prooph/event-store-symfony-bundle/0.10/config/packages/prooph_event_store.yaml
- prooph/event-store-symfony-bundle/0.10/manifest.json
- prooph/pdo-event-store/1.15/config/packages/prooph_pdo_event_store.yaml
- prooph/pdo-event-store/1.15/manifest.json
- prooph/pdo-event-store/1.15/post-install.txt
event store interface should alias instance which wraps the internal event store client 
wrapper gets registered by bundle package due it is the proper place to define an alias
| Packagist     | https://packagist.org/packages/prooph/event-store-symfony-bundle https://packagist.org/packages/prooph/pdo-event-store
> prooph event store recipes

- sentry/sentry-symfony/3.0/config/packages/prod/sentry.yaml
- sentry/sentry-symfony/4.6/config/packages/sentry.yaml
- sentry/sentry-symfony/4.6/manifest.json
| Packagist     | https://packagist.org/packages/sentry/sentry-symfony
Adds the `register_error_handler` options added in https://github.com/getsentry/sentry-symfony/pull/687 and the `hub_id` option added in https://github.com/symfony/monolog-bundle/pull/393 .
cc @cleptric
> Add `register_error_handler` and `hub_id` options for sentry/sentry-symfony

- friendsofsymfony/rest-bundle/3.0/config/packages/fos_rest.yaml
- friendsofsymfony/rest-bundle/3.0/manifest.json
| Packagist     | https://packagist.org/packages/friendsofsymfony/rest-bundle
Addresses https://github.com/FriendsOfSymfony/FOSRestBundle/issues/2367#issuecomment-1449522043
> Disable routing load in friendsofsymfony/rest-bundle:^3

- monsieurbiz/sylius-homepage-plugin/1.0/config/routes/monsieurbiz_sylius_homepage_plugin.yaml
| Packagist     | [monsieurbiz/sylius-homepage-plugin](https://packagist.org/packages/monsieurbiz/sylius-homepage-plugin)
I've added a semicolon missing in the route of this plugin.
> [monsieurbiz/sylius-homepage-plugin] Add missing semicolon in routes

- pentatrion/vite-bundle/1.0/manifest.json
- pentatrion/vite-bundle/1.0/post-install.txt
| Packagist     | [pentatrion/vite-bundle](https://packagist.org/packages/pentatrion/vite-bundle)
Update the `manifest.json`
> update pentatrion/vite-bundle recipe

- monsieurbiz/sylius-search-plugin/2.0/config/packages/monsieurbiz_sylius_search_plugin.yaml
- monsieurbiz/sylius-search-plugin/2.0/config/routes/monsieurbiz_sylius_search_plugin.yaml
- monsieurbiz/sylius-search-plugin/2.0/manifest.json
| Packagist     | [monsieurbiz/sylius-search-plugin](https://packagist.org/packages/monsieurbiz/sylius-search-plugin)
It's a Sylius plugin it will not works with Symfony only.
See our [Recipe workflow](https://github.com/monsieurbiz/SyliusSearchPlugin/blob/master/.github/workflows/recipe.yaml) which test it in our custom recipes repository.
> Add Sylius Search Plugin v2 recipe

- bref/symfony-bridge/0.1/serverless.yaml
| Packagist     | [https://packagist.org/packages/bref/symfony-bridge](https://packagist.org/packages/bref/symfony-bridge)
Since the last version of Symfony requires php8.1, I propose to match it in the config to avoid issues related to composer on deployment.
[https://github.com/symfony/symfony/blob/6.3/composer.json#L36](https://github.com/symfony/symfony/blob/6.3/composer.json#L36)
> Upgrade PHP version to 8.1 to match the required version in Symfony 6.3

- datana-gmbh/formulario-api/1.0/config/packages/datana_formulario_api.yaml
- datana-gmbh/formulario-api/1.0/manifest.json
| Packagist     | https://packagist.org/packages/datana-gmbh/formulario-api
> Enhancement: Add recipe for `datana-gmbh/formulario-api`

- monsieurbiz/sylius-media-manager-plugin/1.0/config/packages/monsieurbiz_media_manager_plugin.yaml
- monsieurbiz/sylius-media-manager-plugin/1.0/config/routes/monsieurbiz_media_manager_plugin.yaml
- monsieurbiz/sylius-media-manager-plugin/1.0/manifest.json
| Packagist     | [monsieurbiz/sylius-media-manager-plugin](https://packagist.org/packages/monsieurbiz/sylius-media-manager-plugin)
It's a Sylius plugin it will not works with Symfony only.
See our [Recipe workflow](https://github.com/monsieurbiz/SyliusMediaManagerPlugin/blob/master/.github/workflows/recipe.yaml) which test it in our custom recipes repository.
> Add recipe for Sylius Media Manager plugin

- phpstan/phpstan/1.0/post-install.txt
| Docs Issue/PR     | https://github.com/symfony/recipes-contrib/issues/1555
The file in the repo is `phpstan.dist.neon` but the text said `phpstan.neon.dist`.
According to the docs, either `phpstan.dist.neon` or `phpstan.neon.dist` are acceptable (see: https://phpstan.org/config-reference#config-file). I'm sticking with `phpstan.dist.neon` since text editors that recognize the `.neon` extension will render the contents of the file nicely.
> Match install directions to actual filename for phpstan config file

- omines/antispam-bundle/0.1/config/packages/antispam.yaml
- omines/antispam-bundle/0.1/manifest.json
| Packagist     | https://packagist.org/packages/omines/antispam-bundle
> Add omines/antispam-bundle

- datana-gmbh/datapool-api/3.16/config/packages/datana_datapool_api.yaml
- datana-gmbh/datapool-api/3.16/manifest.json
| Packagist     | https://packagist.org/packages/datana-gmbh/datapool-api
> Update recipe for `datana-gmbh/datapool-api`

- symfony/apache-pack/1.0/public/.htaccess
`Options +SymLinksIfOwnerMatch` is more secure than `Options +FollowSymlinks`.
With the `FollowSymlinks` option enabled, you could easily mistakenly create a symlink to a file outside the web root folder and Apache would follow it. The owner of files for the web application usually differs from other system files. This additional owner check reduces the risk of exposing files.
> Use SymLinksIfOwnerMatch by default.

- nelmio/solarium-bundle/5.0/config/packages/nelmio_solarium.yaml
- nelmio/solarium-bundle/5.0/manifest.json
| Packagist     | https://packagist.org/packages/nelmio/solarium-bundle
Fixes https://github.com/nelmio/NelmioSolariumBundle/issues/131
> fix recipe for nelmio/solarium-bundle ^5.0

- arad021/entity-already-exists-validation-constraint/1.0/config/packages/arad021_entity_already_exists_validator.yaml
- arad021/entity-already-exists-validation-constraint/1.0/manifest.json
| Packagist     | https://packagist.org/packages/arad021/entity-already-exists-validation-constraint
> - adds recipe for arad021/entity-already-exists-validation-constraint

- doctrine/mongodb-odm-bundle/5.0/config/packages/doctrine_mongodb.yaml
- doctrine/mongodb-odm-bundle/5.0/manifest.json
| Packagist     | [](https://packagist.org/packages/doctrine/mongodb-odm-bundle)
The `is_bundle` and `alias` configs are not required by default.
> Add doctrine/mongodb-odm-bundle v5 without is_bundle (default to false)

- sentry/sentry-symfony/4.6/config/packages/sentry.yaml
| Packagist     | https://packagist.org/packages/sentry/sentry-symfony
Updated the recipe according to:
* https://docs.sentry.io/platforms/php/guides/symfony/performance/instrumentation/automatic-instrumentation/
* https://docs.sentry.io/platforms/php/guides/symfony/
~I know that `tracing.enabled: true` is the default option and we try to not add the default values to recipes to make them simpler. But this is a very important option that can impact the performance of your application, so I think it's fair to show this option prominently.~ Update: we set this option to `false` by default
> Update the Sentry recipe

- dama/doctrine-test-bundle/7.2/config/packages/dama_doctrine_test_bundle.yaml
- dama/doctrine-test-bundle/7.2/manifest.json
| Packagist     | https://packagist.org/packages/dama/doctrine-test-bundle
Symfony 5.3 introduced the `when@...` special key for configuring multiple environments in a single file. DAMADoctrineTestBundle 7.2 was the first version to only support Symfony 5.3 or newer, so it should be safe to create a new recipe for version 7.2.
> [dama/doctrine-test-bundle] Use when@ keyword

- codeception/codeception/5.0/tests/Functional.suite.yml
| Packagist     | [codeception/codeception](https://packagist.org/packages/codeception/codeception)
https://github.com/Codeception/module-doctrine is the successor of https://github.com/Codeception/module-doctrine2
> Replace Doctrine2 with Doctrine in Codeception recipe

- liip/monitor-bundle/3.0/manifest.json
- liip/monitor-bundle/3.0/post-install.txt
| Packagist     | [](https://packagist.org/packages/liip/monitor-bundle)
> update recipe for LiipMonitorBundle 3

- sentry/sentry-symfony/5.0/config/packages/sentry.yaml
- sentry/sentry-symfony/5.0/manifest.json
Q | A
-- | --
License | MIT
Packagist | https://packagist.org/packages/sentry/sentry-symfony
We released a [new major version](https://github.com/getsentry/sentry-symfony/releases/tag/5.0.0) of our Sentry Symfony SDK.
> Sentry Symfony SDK 5.0.0

- gesdinet/jwt-refresh-token-bundle/1.0/src/Entity/RefreshToken.php
Use attributes on the entity instead of annotations as they are fully removed from ORM 3.0 and no will longer work with new setups
| Packagist     | https://packagist.org/packages/gesdinet/jwt-refresh-token-bundle
> Adjust JWT Refresh Token Bundle recipe to use attributes

- kocal/biome-js-bundle/1.0/biome.json
- kocal/biome-js-bundle/1.0/config/packages/kocal_biome_js.yaml
- kocal/biome-js-bundle/1.0/manifest.json
| Packagist     | https://packagist.org/packages/kocal/biome-js-bundle
This PR add the recipe for the fresh package https://github.com/Kocal/BiomeJsBundle :)
The "Run updated recipes" fails because the package does not support PHP 7.4, but works fine with PHP >= 8.1
> Add kocal/biome-js-bundle recipe

- endeavour/groeigids-api-client-bundle/0.1/config/packages/groeigids_api_client.yaml
- endeavour/groeigids-api-client-bundle/0.1/manifest.json
| Packagist     | https://packagist.org/packages/endeavour/groeigids-api-client-bundle
The "Run updated recipes" fails because the package does not support PHP 7.4, but works fine with PHP >= 8.1
> Added recipe for endeavour/groeigids-api-client-bundle

- qossmic/deptrac/2.0/deptrac.yaml
- qossmic/deptrac/2.0/manifest.json
| Packagist     | [qossmic/deptrac](https://packagist.org/packages/qossmic/deptrac)
`qossmic/deptrac-shim` is deprecated and has been replaced by `qossmic/deptrac`.
> Add qossmic/deptrac recipe

- kocal/biome-js-bundle/1.0/biome.json
- kocal/biome-js-bundle/1.1/biome.json
- kocal/biome-js-bundle/1.1/config/packages/kocal_biome_js.yaml
- kocal/biome-js-bundle/1.1/manifest.json
I've released a new version https://github.com/Kocal/BiomeJsBundle/releases/tag/v1.1.0, which needs some recipe adjustments
> [KocalBiomeJsBundle] Add recipe for 1.1, update biome.json from 1.0 aswell

- zim32/symfony-tracing-core/1.0/config/packages/tracing.yaml
- zim32/symfony-tracing-core/1.0/manifest.json
| Packagist     | https://packagist.org/packages/zim32/symfony-tracing-core
> Add recipe for zim32/symfony-tracing-core package

- shopware/app-bundle/4.0/config/packages/shopware_app.yaml
- shopware/app-bundle/4.0/config/routes/shopware_app.yaml
- shopware/app-bundle/4.0/manifest.json
- shopware/app-bundle/4.0/post-install.txt
- shopware/app-bundle/4.0/src/Entity/Shop.php
| Packagist     | https://packagist.org/packages/shopware/app-bundle
We changed the schema of the yaml, therefore need a new recipe version
> feat: add shopware/app-bundle 4.0 variant

- shopware/app-bundle/4.0/config/packages/shopware_app.yaml
| Packagist     | https://packagist.org/packages/shopware/app-bundle
Instead of using hard-code in-memory, we let auto detect the storage so it's more convenient for users to install
> feat: add storage to auto for shopware app bundle

- sylius/admin-ui/0.4/config/routes/sylius_admin_ui.yaml
- sylius/admin-ui/0.4/manifest.json
- sylius/bootstrap-admin-ui/0.4/config/packages/sylius_bootstrap_admin_ui.yaml
- sylius/bootstrap-admin-ui/0.4/manifest.json
- sylius/resource-bundle/1.12/config/packages/sylius_resource.yaml
- sylius/resource-bundle/1.12/config/routes/sylius_resource.yaml
- sylius/resource-bundle/1.12/manifest.json
- sylius/twig-extra/0.4/manifest.json
- sylius/twig-hooks/0.4/manifest.json
- sylius/ui-translations/0.4/manifest.json
| Packagist     | [BootstrapAdminUi](https://packagist.org/packages/sylius/bootstrap-admin-ui), [AdminUi](https://packagist.org/packages/sylius/admin-ui), [TwigExtra](https://packagist.org/packages/sylius/twig-extra), [TwigHooks](https://packagist.org/packages/sylius/twig-hooks), [UiTranslations](https://packagist.org/packages/sylius/ui-translations)
> Init Sylius Stack Flex recipes

- ecphp/cas-bundle/3.0/config/packages/dev/cas_bundle.yaml
- ecphp/cas-bundle/3.0/config/packages/dev/cas_security.yaml
- ecphp/cas-bundle/3.0/config/routes/cas.yaml
- ecphp/cas-bundle/3.0/manifest.json
| Packagist     | https://packagist.org/packages/ecphp/cas-bundle
> ecphp/cas-bundle: add recipe for version 3.0

- 21torr/task-manager/2.0/config/packages/task_manager.yaml
- 21torr/task-manager/2.0/manifest.json
| Packagist     | https://packagist.org/packages/21torr/task-manager
For v2 it's only the default config file for now.
> Add 21torr/task-manager

- jeandanyel/crud-bundle/0.1/config/routes/jeandanyel_crud.yaml
- jeandanyel/crud-bundle/0.1/manifest.json
| Packagist     | https://packagist.org/packages/jeandanyel/crud-bundle
> Add recipe for jeandanyel/crud-bundle

- kocal/biome-js-bundle/1.0/biome.json
- kocal/biome-js-bundle/1.1/biome.json
| Packagist     | https://packagist.org/packages/kocal/biome-js-bundle
The new Symfony 7.2 produce more files that Biome.js can lint, **but** we don't want that.
I've synced the configuration from [the bundle's recommended configuration](https://github.com/Kocal/BiomeJsBundle/blob/main/README.md#configuration) for Symfony
> [BiomeJsBundle] Ignore more directories for linting

- vincentlanglet/twig-cs-fixer/3.0/manifest.json
- vincentlanglet/twig-cs-fixer/3.0/post-install.txt
| Packagist     | vincentlanglet/twig-cs-fixer
add default config and add message
> [vincentlanglet/twig-cs-fixer] add default config and add message

- fluffydiscord/roadrunner-symfony-bundle/3.0/config/packages/fluffy_discord_road_runner.yaml
| Packagist     |  https://packagist.org/packages/fluffydiscord/roadrunner-symfony-bundle
> fix: default invalid key

- patchlevel/event-sourcing-bundle/3.6/config/packages/patchlevel_event_sourcing.yaml
- patchlevel/event-sourcing-bundle/3.6/manifest.json
- patchlevel/event-sourcing-bundle/3.6/post-install.txt
| Packagist     | https://packagist.org/packages/patchlevel/event-sourcing
> upgrade recipe for patchlevel/event-sourcing 3.6

- commerce-weavers/sylius-tpay-plugin/2.0/config/routes/commerce_weavers_tpay_plugin.yaml
| Packagist     | [packagist.org/packages/commerce-weavers/sylius-tpay-plugin](https://packagist.org/packages/commerce-weavers/sylius-tpay-plugin)
The recipe is missing admin routes import.
> Add admin routes to Commerce Weavers Tpay plugin recipe

- oskarstark/doctrine-datetime-milliseconds-type/2.1/config/packages/oskarstark_doctrine_datetime_milliseconds_type.yaml
- oskarstark/doctrine-datetime-milliseconds-type/2.1/manifest.json
- oskarstark/doctrine-postgres-milliseconds-platform/2.1/config/packages/oskarstark_doctrine_postgres_milliseconds_platform.yaml
- oskarstark/doctrine-postgres-milliseconds-platform/2.1/manifest.json
- oskarstark/doctrine-postgres-public-schema-listener/1.2/config/packages/oskarstark_doctrine_postgres_public_schema_listener.yaml
- oskarstark/doctrine-postgres-public-schema-listener/1.2/manifest.json
| Packagist     | https://packagist.org/packages/datana-gmbh/doctrine-datetime-milliseconds-type
> Add recipes for libs

- sylius/refund-plugin/2.0/config/packages/sylius_refund.yaml
- sylius/refund-plugin/2.0/config/routes/sylius_refund.yaml
- sylius/refund-plugin/2.0/manifest.json
| Packagist     | https://packagist.org/packages/sylius/refund-plugin#v2.0.0
Replaces #1728
> Add Sylius/RefundPlugin 2.0 recipe

- survos/bunny-bundle/1.5/config/packages/survos_bunny.yaml
- survos/bunny-bundle/1.5/config/routes/survos_bunny.yaml
- survos/bunny-bundle/1.5/manifest.json
- survos/bunny-bundle/1.5/post-install.txt
| Packagist     | https://packagist.org/packages/survos/bunny-bundle
> initial version for survos/bunny-bundle

- kunstmaan/seo-bundle/7.3/config/routes/kunstmaan_seo.yaml
- kunstmaan/seo-bundle/7.3/manifest.json
| Packagist     | https://packagist.org/packages/kunstmaan/seo-bundle
In the upcoming 7.3 version the route config in the controller is switched to attributes
> Fix kunstmaan/seo-bundle route config for 7.3 version

- symfony/apache-pack/1.0/public/.htaccess
| Packagist     | [symfony/apache-pack](https://packagist.org/packages/symfony/apache-pack)
Fix method switching when the path starts with `/index.php` and `mod_rewrite` is available.
Related #165
> Fix method switching

- sylius/mollie-plugin/1.0/config/packages/sylius_mollie.yaml
- sylius/mollie-plugin/1.0/config/routes/sylius_mollie.yaml
- sylius/mollie-plugin/1.0/manifest.json
| Packagist     | https://packagist.org/packages/sylius/mollie-plugin
> Add recipes for `sylius/mollie-plugin:1.0`

- sentry/sentry-symfony/4.6/config/packages/sentry.yaml
- sentry/sentry-symfony/5.0/config/packages/sentry.yaml
| Packagist     | https://packagist.org/packages/sentry/sentry-symfony
There's no need to manually register the `PsrLogMessageProcessor`, this is done automatically since https://github.com/symfony/monolog-bundle/commit/8f0012305b01ebb81332ffa413edbb4352646b4b . It's enabled by default, but can be disabled by setting the `process_psr_3_messages` option to `false`.
I've also opened a PR in the Sentry docs repo: https://github.com/getsentry/sentry-docs/pull/11063
cc @javiereguiluz
> Update Sentry PSR3 information

- gurtok/seo-bundle/1.0/config/packages/gurtok_seo.yaml
- gurtok/seo-bundle/1.0/manifest.json
| Packagist     | https://packagist.org/packages/gurtok/seo-bundle
This recipe provides default configuration for Gurtok SeoBundle,
a flexible SEO metadata manager for Symfony 6/7.
✅ Automatically registers the bundle  
✅ Creates `config/packages/gurtok_seo.yaml` with default settings
> Add recipe for gurtok/seo-bundle

- contao/core-bundle/5.0/config/packages/contao_core.yaml
- contao/core-bundle/5.0/manifest.json
- contao/core-bundle/5.0/post-install.txt
| Packagist     | https://packagist.org/packages/contao/core-bundle
> WIP: Update recipe for Contao 5.x

- macpaw/behat-http-mock-context/1.0/config/packages/test/behat_http_mock_context.yaml
- macpaw/behat-http-mock-context/1.0/manifest.json
| Packagist     | https://packagist.org/packages/macpaw/behat-http-mock-context
> Add recipe for macpaw/behat-http-mock-context bundle

- calliostro/last-fm-client-bundle/1.0/config/calliostro_last_fm_client.yaml
- calliostro/last-fm-client-bundle/1.0/manifest.json
| Packagist     | https://packagist.org/packages/calliostro/last-fm-client-bundle
This adds a recipe for the calliostro/last-fm-client-bundle package.
The recipe:
- Registers the bundle in config/bundles.php
- Creates a configuration file with sensible defaults
- Adds necessary environment variables to .env
The recipe supports version 1.0+.
Package: https://packagist.org/packages/calliostro/last-fm-client-bundle
Repository: https://github.com/calliostro/last-fm-client-bundle
> [calliostro/last-fm-client-bundle] Add recipe

- sylius/resource-bundle/1.13/config/packages/sylius_resource.yaml
- sylius/resource-bundle/1.13/config/routes/sylius_resource.yaml
- sylius/resource-bundle/1.13/manifest.json
| Packagist     | https://packagist.org/packages/sylius/resource-bundle
> [SyliusResourceBundle] Update routing configuration

- calliostro/discogs-bundle/4.0/config/calliostro_discogs.yaml
- calliostro/discogs-bundle/4.0/manifest.json
- Add recipe for calliostro/discogs-bundle v4.0
- Supports Personal Access Token and OAuth authentication
- Includes configuration options with detailed comments
- Symfony bundle for Discogs API integration
| Packagist     | https://packagist.org/packages/calliostro/discogs-bundle
> Add Discogs Bundle recipe v4.0

- liquidrazor/dto-api-bundle/0.1/config/packages/liquidrazor_dto_api.yaml
- liquidrazor/dto-api-bundle/0.1/config/routes/liquidrazor_dto_api.yaml
- liquidrazor/dto-api-bundle/0.1/manifest.json
| Packagist     | https://packagist.org/packages/liquidrazor/dto-api-bundle
This adds a Symfony Flex recipe for `liquidrazor/dto-api-bundle`.
Package: https://packagist.org/packages/liquidrazor/dto-api-bundle
Minimum version: 0.1
Type: symfony-bundle
What the recipe does:
- Enables `LiquidRazor\DtoApiBundle\LiquidRazorDtoApiBundle` for all envs.
- Drops default config at `config/packages/liquidrazor_dto_api.yaml`.
- Registers routes at `config/routes/liquidrazor_dto_api.yaml` pointing to the bundle's route resource.
Out-of-the-box endpoints exposed by the bundle:
- `/_schema/openapi.json`
- `/_docs/swagger`
- `/_docs/redoc`
Tested on a fresh Symfony 7 skeleton by requiring the package and verifying the endpoints.
> Add initial recipe for LiquidRazor DTO API bundle
